import {provinceDirection} from '../mjs/geography.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';
import {spawnBattle,neighbors,distance,reachable,DIRECTIONS,direction,terrainCost,dailyMobility,placementCells,aiBattle,reinforcementOptions,ambushAdjacent,ambushCells,entryEdge,retreatOptions,fireChance,WEATHER} from '../mjs/battle.mjs';
const scenarios=JSON.parse(fs.readFileSync(new URL('../config/scenarios.json',import.meta.url))),terrains=JSON.parse(fs.readFileSync(new URL('../config/province-terrain.json',import.meta.url)));
let checks=0;const test=(label,fn)=>{fn();checks++;console.log('PASS',label);};
const fresh=()=>new Game(createCampaign(scenarios[0],[0]),{},structuredClone(terrains));
function begin(g=fresh(),ids=[0,34],deploy=true){g.invade({province:9,target:8,governor:33,officers:ids,food:20000});if(deploy)while(g.s.battle?.phase==='deployment')aiBattle(g,60);return g;}
function arena(){const g=begin(),b=g.s.battle,u=b.units.find(u=>u.id===0),f=b.units.find(u=>u.id===34),v=b.units.find(u=>u.side==='defend'&&u.id!==b.rulers.defend),king=b.units.find(u=>u.id===b.rulers.defend);assert(v&&king);b.units=[u,f,v,king];b.terrain=Array(156).fill(0);b.terrain[155]=6;g.terrains[b.target-1]=[...b.terrain];b.palace={q:12,r:11};b.food={attack:1000000,defend:1000000};b.weather='sunny';b.wind=0;b.windStrength=0;for(const x of b.units)Object.assign(x,{soldiers:5000,startSoldiers:5000,morale:100,war:80,int:80,training:20,weapons:5000,mobility:2,ordered:false,orderDay:0,routed:false,captured:false,fled:false,placed:true});Object.assign(u,{q:6,r:6});Object.assign(f,{q:7,r:5});Object.assign(v,{q:7,r:6});Object.assign(king,{q:0,r:1});g.random=()=>0;return {g,b,u,f,v,king};}
test('Hex geometry provides six vertical and diagonal directions for both column parities',()=>{for(const q of [5,6]){const ns=neighbors(q,6);assert.equal(ns.length,6);assert.deepEqual(ns,DIRECTIONS.map((_,i)=>direction(q,6,i)));for(const n of ns)assert.equal(distance({q,r:6},n),1);}assert.equal(distance({q:6,r:6},{q:7,r:7}),2);});
test('All 41 original province terrain layouts are retained exactly',()=>{const g=fresh();for(const p of g.s.provinces){const source=g.province(p.neighbors[0]);if(source.owner===255)source.owner=0;if(p.owner===255)p.owner=1;const id=source.officers[0]??0;assert.deepEqual(spawnBattle(g,source,p,[id],20000,terrains[p.id-1]).terrain,terrains[p.id-1]);}});
test('Deployment highlights passable edge hexes for attackers and rejects illegal placements atomically',()=>{const g=begin(fresh(),[0,34],false),b=g.s.battle,u=b.units[0],before=JSON.stringify(b);assert.equal(b.phase,'deployment');assert(b.units.every(u=>!u.placed&&u.mobility===dailyMobility(g.officer(u.id).training)));for(const cell of placementCells(b,'attack')){assert(entryEdge(cell.q,cell.r,b.entryDirection,b.target));assert(Number.isFinite(terrainCost(b.terrain[cell.r*13+cell.q])));}assert.throws(()=>g.battleAction('place',{unit:u.id,q:6,r:6}));assert.throws(()=>g.battleAction('deploy'));assert.equal(JSON.stringify(b),before);const cell=placementCells(b,'attack')[0];g.battleAction('place',{unit:u.id,...cell});assert(u.placed);assert.equal(u.mobility,dailyMobility(g.officer(u.id).training));validateSave(g.s,scenarios,g.terrains);});
test('Both armies must finish placement before day one begins; deployment saves restore',()=>{const g=begin(fresh(),[0,34],false);while(g.s.battle.phase==='deployment'&&g.s.battle.side==='attack')aiBattle(g,60);assert.equal(g.s.battle.side,'defend');assert.equal(g.s.battle.phase,'deployment');const h=new Game(validateSave(g.s,scenarios,g.terrains),{},g.terrains);assert.deepEqual(h.s.battle,g.s.battle);while(g.s.battle.phase==='deployment')aiBattle(g,60);assert.equal(g.s.battle.day,1);assert(g.s.battle.units.every(u=>u.placed));});
test('Terrain costs match the requested mobility table and mountains are impassable',()=>{assert.deepEqual([0,1,2,4,5,6].map(terrainCost),[2,3,3,5,3,3]);assert.equal(terrainCost(3),Infinity);const {b,u}=arena();u.mobility=100;for(let r=0;r<12;r++)b.terrain[r*13+8]=3;assert(!reachable(b,u).some(p=>p.q>8));});
test('Normal movement consumes the actual terrain cost and only one daily order',()=>{const {g,b,u}=arena(),move=reachable(b,u).find(p=>p.q===6&&p.r===5);assert(move);g.battleAction('move',{unit:u.id,...move});assert.equal(u.mobility,0);assert(u.ordered);const before=JSON.stringify(b);assert.throws(()=>g.battleAction('wait',{unit:u.id}));assert.equal(JSON.stringify(b),before);});
test('Wait holds position, banks one mobility and enables three-point terrain on the next turn',()=>{const {g,b,u}=arena();b.terrain[5*13+6]=1;assert(!reachable(b,u).some(p=>p.q===6&&p.r===5));g.battleAction('wait',{unit:u.id});assert.equal(u.mobility,3);assert.deepEqual({q:u.q,r:u.r},{q:6,r:6});g.battleAction('end');g.battleAction('end');assert.equal(u.mobility,3);assert(!u.ordered);assert(reachable(b,u).some(p=>p.q===6&&p.r===5));});
test('Finishing orders makes uncommanded units wait once, without doubling a chosen Wait',()=>{const {g,b,u,f}=arena();g.battleAction('wait',{unit:u.id});g.battleAction('end');assert.equal(u.mobility,3);assert.equal(f.mobility,3);assert.equal(b.day,1);g.battleAction('end');assert.equal(b.day,2);assert.equal(u.mobility,3);});
test('Attacks use only six adjacent hexes; charge trades larger damage for larger own losses',()=>{const n=arena(),c=arena();n.g.random=()=>.5;c.g.random=()=>.5;n.g.battleAction('attack',{unit:n.u.id,target:n.v.id});c.g.battleAction('charge',{unit:c.u.id,target:c.v.id});assert(c.v.soldiers<n.v.soldiers);assert(c.u.soldiers<n.u.soldiers);const x=arena();x.v.q=7;x.v.r=7;assert.throws(()=>x.g.battleAction('attack',{unit:x.u.id,target:x.v.id}));});
test('Simultaneous attacks consume each ready neighbouring unit’s daily order',()=>{const {g,u,f,v}=arena(),troops=v.soldiers;g.battleAction('simultaneous',{unit:u.id,target:v.id});assert(v.soldiers<troops);assert(u.ordered&&f.ordered);assert.equal(u.mobility,2);});
test('Simultaneous attacks reject an exhausted ally without spending another order',()=>{const {g,b,u,f,v}=arena();f.ordered=true;const before=JSON.stringify(b);assert.throws(()=>g.battleAction('simultaneous',{unit:u.id,target:v.id}));assert.equal(JSON.stringify(b),before);});
test('Move enemy taunts a hostile unit into a feasible hex and spends its mobility',()=>{const {g,u,v}=arena();v.q=10;v.r=5;const before=distance(u,v);g.battleAction('moveEnemy',{unit:u.id,target:v.id});assert(distance(u,v)<before);assert.equal(v.mobility,0);assert(u.ordered);});
test('Friendly View is free; each enemy inspection spends 100 from the field purse',()=>{const {g,b,u,v}=arena(),bank=b.gold,gold=bank.attack;g.battleAction('view',{target:u.id});assert.equal(bank.attack,gold);g.battleAction('view',{target:v.id});g.battleAction('view',{target:v.id});assert.equal(bank.attack,gold-200);assert(!u.ordered);bank.attack=99;const before=JSON.stringify(g.s);assert.throws(()=>g.battleAction('view',{target:v.id}));assert.equal(JSON.stringify(g.s),before);});
test('Day-one personal challenge requires the configurable war threshold and cannot repeat',()=>{const {g,b,u,v}=arena();u.war=79;assert.throws(()=>g.battleAction('challenge',{unit:u.id,target:v.id}));u.war=80;b.day=2;b.completedDays=1;assert.throws(()=>g.battleAction('challenge',{unit:u.id,target:v.id}));b.day=1;b.completedDays=0;g.battleAction('challenge',{unit:u.id,target:v.id});assert(b.challenge);assert(u.ordered);assert.throws(()=>g.battleAction('end'));});
test('Refusing a personal challenge causes five-percent desertion across the responding army',()=>{const {g,b,u,v,king}=arena();g.battleAction('challenge',{unit:u.id,target:v.id});g.battleAction('challengeResponse',{accept:false});assert.equal(v.soldiers,4750);assert.equal(king.soldiers,4750);assert.equal(u.soldiers,5000);assert.equal(b.challenge,null);});
test('Challenge control passes to the responding human and accepted combat captures the loser',()=>{const {g,b,u,v}=arena();g.s.humanRulers=[b.attacker,b.defender];u.war=100;v.war=50;g.battleAction('challenge',{unit:u.id,target:v.id});assert.equal(g.battleOwner(),b.defender);assert(g.battleHuman());assert.equal(g.aiStep(),false);validateSave(g.s,scenarios,g.terrains);g.battleAction('challengeResponse',{accept:true});assert(v.captured);assert.equal(g.battleOwner(),b.attacker);});
test('Accepted duellists do not receive a second daily order when their army phase starts',()=>{const {g,b,f,v}=arena();f.war=80;v.war=100;g.battleAction('challenge',{unit:f.id,target:v.id});g.battleAction('challengeResponse',{accept:true});assert(v.ordered);g.battleAction('end');assert.equal(b.side,'defend');assert(v.ordered);});
test('Individual Flee withdraws one unit; commander flight requires confirmation and withdraws all',()=>{const {g,b,u,f}=arena(),before=JSON.stringify(b);assert.throws(()=>g.battleAction('flee',{unit:u.id}));assert.equal(JSON.stringify(b),before);g.random=()=>0;g.battleAction('flee',{unit:f.id,province:b.source});assert(f.fled);assert(!u.fled);assert(g.s.battle);g.battleAction('flee',{unit:u.id,confirmArmy:true});assert(!g.s.battle);assert.equal(g.s.lastBattle.winner,'defend');assert(b.units.filter(v=>v.side==='attack').every(v=>v.fled));validateSave(g.s,scenarios,g.terrains);});
test('Palace occupation wins immediately without siege or wall damage',()=>{const {g,b,u}=arena();u.q=12;u.r=10;u.mobility=3;g.battleAction('move',{unit:u.id,q:12,r:11});assert.equal(g.s.battle,null);assert.equal(g.s.lastBattle.reason,'The palace was occupied.');assert.equal(g.province(b.target).owner,b.attacker);validateSave(g.s,scenarios,g.terrains);});
test('Capturing the ruler wins even when another enemy unit still has soldiers',()=>{const {g,b,u,v,king}=arena();Object.assign(king,{q:6,r:5,soldiers:1,war:0});assert(v.soldiers>0);g.battleAction('attack',{unit:u.id,target:king.id});assert(!g.s.battle);assert.equal(g.s.lastBattle.reason,'The opposing ruler was captured.');assert.equal(g.officer(king.id).owner,255);assert.equal(g.officer(king.id).prisonerOf,b.attacker);validateSave(g.s,scenarios,g.terrains);});
test('An army with no soldiers loses; unresolved day 30 suspends warfare without awarding victory',()=>{const x=arena();x.v.soldiers=0;x.king.soldiers=0;x.g.battleAction('wait',{unit:x.u.id});assert.equal(x.g.s.lastBattle.winner,'attack');const {g,b}=arena();b.day=30;b.completedDays=29;g.battleAction('end');assert(g.s.battle);g.battleAction('end');assert.equal(g.s.battle,null);assert.equal(g.s.wars.length,1);assert.equal(g.s.lastBattle,undefined);assert.equal(b.day,30);validateSave(g.s,scenarios,g.terrains);});
test('Burning units lose a random amount below thirty percent without a forced minimum',()=>{const {g,b,u}=arena();g.random=()=>.5;b.fire[u.r*13+u.q]=3;b.side='defend';g.battleAction('end');assert.equal(u.soldiers,4250);g.battleAction('end');g.battleAction('end');assert.equal(u.soldiers,3613);});
test('Legacy strength cannot multiply fire spread beyond the adjacent downwind hex',()=>{const {g,b}=arena();b.fire={68:3};b.wind=2;b.windStrength=3;b.side='defend';g.battleAction('end');assert(b.fire[55]);assert(!b.fire[42]&&!b.fire[29]);assert.equal(Object.keys(b.fire).length,2);});
test('Directional fire does not fan into flank or opposite hexes for either column parity',()=>{const cycle=[0,1,2,5,4,3];for(const q of [5,6])for(let i=0;i<6;i++){const {g,b}=arena(),origin={q,r:5};b.fire={[origin.r*13+origin.q]:3};b.wind=i+1;b.windStrength=3;b.side='defend';g.battleAction('end');const c=cycle.indexOf(i),forward=direction(origin.q,origin.r,i);assert(b.fire[forward.r*13+forward.q]);for(const offset of [-1,1,3]){const flank=direction(origin.q,origin.r,cycle[(c+offset+6)%6]);assert(!b.fire[flank.r*13+flank.q]);}}});
test('Wind uses all six absolute directions; calm and map edges never wrap fire',()=>{for(let i=0;i<6;i++){const {g,b}=arena(),origin={q:3,r:3},index=origin.r*13+origin.q;b.fire={[index]:3};b.wind=i+1;b.windStrength=1;b.side='defend';g.battleAction('end');const cell=direction(origin.q,origin.r,i);assert(b.fire[cell.r*13+cell.q]);}const {g,b}=arena();b.fire={38:3};b.wind=6;b.windStrength=3;b.side='defend';g.battleAction('end');assert(!b.fire[39]);});
test('Rain clears every fire immediately and rejects ignition atomically',()=>{const {g,b,u}=arena();b.fire={12:3,44:2,100:1};g.cheat('battle',u.id,{weather:'rain'});assert.deepEqual(b.fire,{});const before=JSON.stringify(g.s);assert.throws(()=>g.battleAction('fireball',{unit:u.id,q:6,r:5}));assert.equal(JSON.stringify(g.s),before);validateSave(g.s,scenarios,g.terrains);});
test('A rainy new day extinguishes the complete fire map',()=>{const {g,b}=arena();b.fire={12:3,44:2,100:1};b.side='defend';g.random=()=>.99;g.battleAction('end');assert.equal(b.weather,'rain');assert.deepEqual(b.fire,{});});
test('Jungle ambush covers the native three forward hexes for both column parities',()=>{for(const q of [5,6])for(let d=0;d<6;d++){const {g,b,u,f,v,king}=arena();const start={q,r:5},dest=direction(q,5,d),forest=ambushCells(start,dest).find(p=>distance(p,start)>1);assert(forest);Object.assign(u,start,{mobility:20});Object.assign(v,forest,{mobility:0,ordered:true});Object.assign(f,{q:0,r:0});Object.assign(king,{q:0,r:1});b.terrain[v.r*13+v.q]=1;const troops=u.soldiers;g.battleAction('move',{unit:u.id,...dest});assert(u.soldiers<troops);assert.equal(v.mobility,0);assert(v.ordered);assert(b.events.some(t=>t.includes('ambushed')));}});
test('Ambush fires while traversing a path toward a jungle defender',()=>{const {g,b,u,f,v,king}=arena();Object.assign(u,{q:1,r:5,mobility:20});Object.assign(v,{q:5,r:5});Object.assign(f,{q:0,r:0});Object.assign(king,{q:0,r:1});b.terrain[v.r*13+v.q]=1;const move=reachable(b,u).find(p=>p.path.length>1&&p.path.some(step=>ambushAdjacent(step,v)));assert(move);g.battleAction('move',{unit:u.id,...move});assert.equal(b.events.filter(t=>t.includes('ambushed')).length,1);});
test('Reinforcements spend reserve rice, enter legally and settle officers in the victorious province',()=>{const {g,b,u}=arena();const support=g.province(6);support.owner=b.attacker;for(const id of support.officers)Object.assign(g.officer(id),{owner:b.attacker,acted:false,soldiers:1000});g.normalize();const option=reinforcementOptions(g)[0];assert(option);const bank=g.province(option.province),rice=bank.food,armyRice=b.food.attack;g.battleAction('reinforce',{unit:u.id,...option,food:1000});const unit=b.units.find(v=>v.id===option.officer);assert(unit.placed);assert(entryEdge(unit.q,unit.r,provinceDirection(g.province(b.target),bank),b.target));assert.equal(unit.mobility,2);assert.equal(bank.food,rice-1000);assert.equal(b.food.attack,armyRice+1000);assert(g.officer(unit.id).acted);validateSave(g.s,scenarios,g.terrains);b.side='defend';assert.throws(()=>g.battleAction('retreat'),/retreat province/);b.outcome={winner:'attack',reason:'Defending commander defeated'};g.resolveBattle();assert(g.province(b.target).officers.includes(unit.id));assert(!bank.officers.includes(unit.id));validateSave(g.s,scenarios,g.terrains);});
test('Successful and failed bribes spend gold; successful allegiance survives settlement',()=>{const x=arena(),bank=x.b.gold,gold=bank.attack;x.g.battleAction('bribe',{unit:x.u.id,target:x.v.id,gold:100});assert.equal(bank.attack,gold-100);assert.equal(x.v.side,'attack');validateSave(x.g.s,scenarios,x.g.terrains);x.b.side='defend';x.b.outcome={winner:'attack',reason:'Defending commander defeated'};x.g.resolveBattle();assert.equal(x.g.officer(x.v.id).owner,x.b.attacker);assert(x.g.province(x.b.target).officers.includes(x.v.id));validateSave(x.g.s,scenarios,x.g.terrains);const y=arena();y.g.random=()=>.999;const before=y.b.gold.attack;y.g.battleAction('bribe',{unit:y.u.id,target:y.v.id,gold:100});assert.equal(y.v.side,'defend');assert.equal(y.b.gold.attack,before-100);});
test('Bribery rejects rulers and reinforcement failures leave campaign resources unchanged',()=>{const {g,b,u,king}=arena();const before=JSON.stringify(g.s);assert.throws(()=>g.battleAction('bribe',{unit:u.id,target:king.id,gold:100}));assert.throws(()=>g.battleAction('reinforce',{unit:u.id,province:9,officer:34,food:1000}));assert.equal(JSON.stringify(g.s),before);});
test('Viewing defaults resolve remote wars but retain personal defense and All battles',()=>{const personal=begin();assert(personal.battleDetailed());const remote=begin(fresh(),[34],false);assert(!remote.s.battle);validateSave(remote.s,scenarios,remote.terrains);const defend=new Game(createCampaign(scenarios[1],[0]),{},terrains),target=defend.province(11),source=target.neighbors.map(id=>defend.province(id)).find(p=>p.owner!==255&&p.owner!==0&&p.officers.length>1&&p.officers.some(id=>defend.officer(id).soldiers>0));defend.s.player=source.owner;defend.ruler().alliances=[];source.food=50000;defend.invade({province:source.id,target:11,officers:[source.officers.find(id=>defend.officer(id).soldiers)],food:20000});assert(!defend.s.battle);assert(defend.s.lastBattle);validateSave(defend.s,scenarios,terrains);});
test('All default AI scenarios resolve wars automatically with valid checkpoints',()=>{let reports=0;for(const scenario of scenarios){const g=new Game(createCampaign(scenario,[]),{},terrains);g.s.ai.aggression=100;g.s.seed=42;let last;for(let i=0;i<500;i++){assert(g.aiStep());assert(!g.s.battle);if(g.s.lastBattle!==last){last=g.s.lastBattle;reports++;assert(last.day<=30);}}validateSave(g.s,scenarios,terrains);}assert(reports>0);});
test('Legacy square checkpoints migrate to hex mobility and relocate mountain positions',()=>{const g=begin(),raw=structuredClone(g.s);raw.battle.rulesVersion=2;delete raw.battle.phase;delete raw.battle.deployment;raw.battle.city=raw.battle.palace;raw.battle.walls=1000;raw.battle.wind=8;for(const u of raw.battle.units){u.ap=2;delete u.mobility;delete u.placed;}const mountain=raw.battle.terrain.indexOf(3);if(mountain>=0){raw.battle.units[0].q=mountain%13;raw.battle.units[0].r=Math.floor(mountain/13);}const loaded=validateSave(raw,scenarios,terrains);assert.equal(loaded.battle.rulesVersion,6);assert.equal(loaded.battle.wind,6);assert(loaded.battle.units.every(u=>Number.isFinite(terrainCost(loaded.battle.terrain[u.r*13+u.q]))&&u.mobility===2));const corrupt=structuredClone(loaded);corrupt.battle.day=31;assert.throws(()=>validateSave(corrupt,scenarios,terrains));const corruptMap=structuredClone(loaded);corruptMap.battle.terrain[0]=(corruptMap.battle.terrain[0]+1)%6;assert.throws(()=>validateSave(corruptMap,scenarios,terrains));});
test('Every original province link chooses the opposite approach and legal directional edge',()=>{const g=fresh(),opposites=[5,4,3,2,1,0];for(const p of g.s.provinces)for(const id of p.neighbors){const source=g.province(id),entry=provinceDirection(p,source);assert.equal(entry,opposites[provinceDirection(source,p)]);const b={target:p.id,terrain:terrains[p.id-1],fire:{},units:[],entryDirection:entry};assert.equal(b.entryDirection,entry);assert(placementCells(b,'attack').length);for(const c of placementCells(b,'attack'))assert(entryEdge(c.q,c.r,entry,p.id));}});
test('Charge occupies the defeated enemy hex without consuming normal-move mobility',()=>{const {g,b,u,v}=arena();v.soldiers=1;const target={q:v.q,r:v.r},mp=u.mobility;g.battleAction('charge',{unit:u.id,target:v.id});assert.equal(v.soldiers,0);assert.deepEqual({q:u.q,r:u.r},target);assert.equal(u.mobility,mp);assert(u.ordered);validateSave(g.s,scenarios,g.terrains);});
test('Surviving enemies allow a probabilistic straight charge breakthrough in all six directions',()=>{for(const q of [5,6])for(let i=0;i<6;i++){const {g,b,u,f,v,king}=arena();Object.assign(u,{q,r:6});Object.assign(f,{q:0,r:0});Object.assign(king,{q:0,r:1});Object.assign(v,direction(u.q,u.r,i));const beyond=direction(v.q,v.r,i);g.random=()=>0;g.battleAction('charge',{unit:u.id,target:v.id});assert(v.soldiers>0&&!v.routed);assert.deepEqual({q:u.q,r:u.r},beyond);validateSave(g.s,scenarios,g.terrains);}});
test('Charge does not land beyond the enemy on failure, occupied hexes, mountains or outside the map',()=>{for(const blocked of ['chance','friendly','enemy','mountain','outside']){const {g,b,u,f,v,king}=arena();if(blocked==='chance')g.random=()=>.99;if(blocked==='friendly')Object.assign(f,{q:8,r:7});if(blocked==='enemy')Object.assign(king,{q:8,r:7});if(blocked==='mountain')b.terrain[7*13+8]=3;if(blocked==='outside'){Object.assign(u,{q:11,r:6});Object.assign(v,{q:12,r:7});}const start={q:u.q,r:u.r};g.battleAction('charge',{unit:u.id,target:v.id});assert(v.soldiers>0);assert.deepEqual({q:u.q,r:u.r},start,blocked);}});
test('Charge landings trigger jungle ambush and immediate palace occupation',()=>{const a=arena();Object.assign(a.f,{q:0,r:0});Object.assign(a.king,{q:8,r:8});a.b.terrain[8*13+8]=1;a.g.battleAction('charge',{unit:a.u.id,target:a.v.id});assert(a.b.events.some(t=>t.includes('ambushed')));const x=arena();x.v.soldiers=1;x.b.terrain[x.b.palace.r*13+x.b.palace.q]=0;x.b.palace={q:x.v.q,r:x.v.r};x.b.terrain[x.v.r*13+x.v.q]=6;x.g.battleAction('charge',{unit:x.u.id,target:x.v.id});assert.equal(x.g.s.lastBattle.reason,'The palace was occupied.');});
test('Old all-edge deployment saves migrate and forged directional placement is rejected',()=>{const g=begin(fresh(),[0,34],false),b=g.s.battle,u=b.units[0];const wrong=[];for(let r=0;r<12;r++)for(let q=0;q<13;q++)if((q===0||q===12||r===0||r===11)&&!entryEdge(q,r,b.entryDirection,b.target)&&Number.isFinite(terrainCost(b.terrain[r*13+q])))wrong.push({q,r});assert(wrong.length);Object.assign(u,{...wrong[0],placed:true});assert.throws(()=>validateSave(g.s,scenarios,g.terrains));b.rulesVersion=3;delete b.entryDirection;const loaded=validateSave(g.s,scenarios,g.terrains);assert.equal(loaded.battle.rulesVersion,6);assert.equal(loaded.battle.units[0].placed,false);const forged=structuredClone(loaded);forged.battle.entryDirection=(forged.battle.entryDirection+1)%6;assert.throws(()=>validateSave(forged,scenarios,g.terrains));});
test('Personal units cannot override the approach in a saved deployment',()=>{const g=begin(fresh(),[0,34],false),b=g.s.battle,u=b.units[0];let spot,entry;for(let dir=0;dir<6;dir++){spot=placementCells(b,'attack',null,dir).find(c=>!entryEdge(c.q,c.r,b.entryDirection));if(spot){entry=dir;break;}}assert(spot);Object.assign(u,{...spot,placed:true,entryDirection:entry});assert.throws(()=>validateSave(g.s,scenarios,g.terrains),/deployment direction/);});
test('Forged allegiance and remote origins cannot be restored; legitimate bribery still can',()=>{for(const field of ['betrayed','side','origin']){const {g,b,v}=arena();if(field==='betrayed')v.betrayed='yes';else if(field==='side')v.side='attack';else{const remote=g.s.provinces.find(p=>p.id!==b.target&&!g.province(b.target).neighbors.includes(p.id)&&p.officers.length);remote.owner=b.attacker;for(const id of remote.officers)g.officer(id).owner=b.attacker;g.normalize();v.origin=remote.id;v.id=remote.officers[0];v.side=v.originalSide='attack';}assert.throws(()=>validateSave(g.s,scenarios,g.terrains),field==='origin'?/connected province/:field==='side'?/betrayal record/:/allegiance/);}const {g,u,v}=arena();g.battleAction('bribe',{unit:u.id,target:v.id,gold:100});assert.equal(validateSave(g.s,scenarios,g.terrains).battle.units.find(x=>x.id===v.id).betrayed,true);});
test('A defeated charge target is occupied in every direction even when breakthrough would fail',()=>{for(const q of [5,6])for(let i=0;i<6;i++){const {g,b,u,f,v,king}=arena();Object.assign(u,{q,r:6,war:0});Object.assign(f,{q:0,r:0});Object.assign(king,{q:0,r:1});Object.assign(v,{...direction(q,6,i),soldiers:1});const dest={q:v.q,r:v.r};g.random=()=>.999;g.battleAction('charge',{unit:u.id,target:v.id});assert.equal(v.soldiers,0);assert.deepEqual({q:u.q,r:u.r},dest);validateSave(g.s,scenarios,g.terrains);}});
test('A surviving-defender breakthrough uses attacker War rather than a fixed fifty-percent roll',()=>{for(const war of [0,100]){const {g,u,v}=arena(),start={q:u.q,r:u.r},i=DIRECTIONS.findIndex((_,i)=>{const x=direction(u.q,u.r,i);return x.q===v.q&&x.r===v.r;}),beyond=direction(v.q,v.r,i);u.war=war;g.random=()=>.75;g.battleAction('charge',{unit:u.id,target:v.id});assert(v.soldiers>0);assert.deepEqual({q:u.q,r:u.r},war===100?beyond:start);}});

test('Army equipment changes actual combat losses and purchasing equips a recipient without creating soldiers',()=>{
 const bare=arena(),armed=arena(),partial=arena();bare.u.weapons=0;partial.u.weapons=2500;
 for(const x of [bare,partial,armed]){x.g.random=()=>.5;x.g.battleAction('attack',{unit:x.u.id,target:x.v.id});}
 assert(bare.v.soldiers>partial.v.soldiers);assert(partial.v.soldiers>armed.v.soldiers);
 const g=fresh(),p=g.province(9),buyer=g.officer(34),recipient=g.officer(33);g.s.monthlyReview=null;p.merchant=true;buyer.acted=false;recipient.weapons=0;const men=recipient.soldiers,gold=p.gold;
 g.execute('trade',{province:p.id,officer:buyer.id,recipient:recipient.id,mode:'arms',amount:17});
 assert.equal(p.gold,gold-17);assert.equal(recipient.weapons,1700);assert.equal(recipient.soldiers,men);assert(buyer.acted);validateSave(g.s,scenarios,terrains);
});
test('Battle HUD weapons validate atomically and persist through settlement and suspended wars',()=>{
 const x=arena();x.g.cheat('battle',x.u.id,{weapons:1234});assert.equal(x.u.weapons,1234);const before=JSON.stringify(x.g.s);assert.throws(()=>x.g.cheat('battle',x.u.id,{weapons:10001}));assert.equal(JSON.stringify(x.g.s),before);
 const y=arena();y.u.weapons=2345;y.b.suspended=true;y.g.suspendBattle();assert.equal(y.g.officer(y.u.id).weapons,2345);assert.equal(validateSave(y.g.s,scenarios,y.g.terrains).wars[0].units.find(u=>u.id===y.u.id).weapons,2345);
 const z=arena();z.u.weapons=3456;z.b.outcome={winner:'attack',reason:'Test victory'};z.g.resolveBattle();assert.equal(z.g.officer(z.u.id).weapons,3456);validateSave(z.g.s,scenarios,z.g.terrains);
});
test('A terminal commander charge keeps the occupation coordinate in the victory report',()=>{
 const {g,b,u,f,v,king}=arena();Object.assign(f,{q:0,r:0});Object.assign(v,{q:0,r:2});Object.assign(king,{q:7,r:6,soldiers:1});b.leaders.defend=king.id;const target={q:king.q,r:king.r};
 g.battleAction('charge',{unit:u.id,target:king.id});assert.equal(king.soldiers,0);assert.deepEqual({q:u.q,r:u.r},target);assert.equal(g.s.battle,null);assert(g.s.triumph);assert.equal(g.s.lastBattle.chargeLanding.kind,'occupation');assert.deepEqual({q:g.s.lastBattle.chargeLanding.q,r:g.s.lastBattle.chargeLanding.r},target);validateSave(g.s,scenarios,g.terrains);
});
console.log(checks+' revised battle checks passed.');
