import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';
import {aiBattle,retreatOptions,WEATHER,setWeather,fireChance} from '../mjs/battle.mjs';
import {runMonthlyEvents,disaster,triggerEvent,incomeFactor,officerDeath} from '../mjs/monthly-events.mjs';
import {OFFICER_ROSTER} from '../mjs/officer-roster.mjs';import {portraitIndex,portraitFrame} from '../mjs/portraits.mjs';import {eventFrame,EVENT_ART} from '../mjs/events.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));
let checks=0;const test=(label,fn)=>{fn();checks++;console.log('PASS',label);},report=()=>({events:[],details:[]}),fresh=(i=0)=>{const s=createCampaign(scenarios[i],[0]);s.seed=12345;const g=new Game(s,{},structuredClone(terrains));g.random=()=>.99;return g;};
function arena(){const g=fresh();g.invade({province:9,target:8,governor:33,officers:[0,34],food:20000});while(g.s.battle.phase==='deployment')aiBattle(g);const b=g.s.battle,u=b.units.find(x=>x.id===0),f=b.units.find(x=>x.id===34),v=b.units.find(x=>x.side==='defend'&&x.id!==b.leaders.defend),king=b.units.find(x=>x.id===b.leaders.defend);b.units=[u,f,v,king];b.terrain=Array(156).fill(0);b.terrain[155]=6;g.terrains[b.target-1]=[...b.terrain];b.palace={q:12,r:11};b.food={attack:1000000,defend:1000000};setWeather(b,'sunny');for(const [i,x] of b.units.entries())Object.assign(x,{q:6+i%2,r:5+Math.floor(i/2),placed:true,mobility:10,ordered:false,orderDay:0,morale:100,soldiers:5000,startSoldiers:5000,int:80});return {g,b,u,f,v,king};}
function neutral(g,b){const p=g.province(g.province(b.target).neighbors.find(id=>id!==b.source));for(const id of p.officers){g.officer(id).owner=255;p.unclaimed.push(id);}p.officers=[];p.owner=255;p.governor=null;g.normalize();return p;}
test('General retreat requires a valid choice and rejects occupied, remote and missing destinations atomically',()=>{const {g,b,f}=arena();const before=JSON.stringify(g.s);for(const province of [undefined,b.target,36]){assert.throws(()=>g.battleAction('flee',{unit:f.id,province}));assert.equal(JSON.stringify(g.s),before);}g.battleAction('flee',{unit:f.id,province:b.source});assert(f.fled);assert.equal(f.retreatProvince,b.source);assert(!b.units.find(x=>x.id===b.leaders.attack).fled);const s=validateSave(g.s,scenarios,g.terrains);assert.equal(s.battle.units.find(x=>x.id===f.id).retreatProvince,b.source);});
test('Empty neighbour retreat reserves the province and settles surviving troops after restored defeat',()=>{const {g,b,u,f,v}=arena(),p=neutral(g,b);g.battleAction('flee',{unit:f.id,province:p.id});assert(!retreatOptions(g,v).some(q=>q.id===p.id));const saved=validateSave(g.s,scenarios,g.terrains),loaded=new Game(saved,{},g.terrains);loaded.battleAction('flee',{unit:u.id,confirmArmy:true});assert.equal(loaded.province(p.id).owner,b.attacker);assert(loaded.province(p.id).officers.includes(f.id));assert.equal(loaded.officer(f.id).soldiers,5000);assert.equal(loaded.province(p.id).governor,f.id);validateSave(loaded.s,scenarios,g.terrains);});
test('Defenders exclude the attacker source and can settle an empty connected province after conquest',()=>{const {g,b,v,king}=arena(),p=neutral(g,b);b.side='defend';assert(!retreatOptions(g,v).some(q=>q.id===b.source));assert(retreatOptions(g,v).some(q=>q.id===p.id));assert.throws(()=>g.battleAction('flee',{unit:v.id,province:b.source}));g.battleAction('flee',{unit:v.id,province:p.id});g.battleAction('flee',{unit:king.id,confirmArmy:true});assert.equal(g.province(p.id).owner,b.defender);assert(g.province(p.id).officers.includes(v.id));assert.equal(g.province(b.target).owner,b.attacker);validateSave(g.s,scenarios,g.terrains);});
test('Forged retreat reservations and destinations cannot be restored',()=>{const {g,b,f}=arena();f.fled=true;f.retreatProvince=b.target;assert.throws(()=>validateSave(g.s,scenarios,g.terrains));f.retreatProvince=b.source;f.fled=false;assert.throws(()=>validateSave(g.s,scenarios,g.terrains));});
test('Four complete weather states give clear the best fire chance and rain none',()=>{assert.deepEqual(Object.values(WEATHER),['Clear','Few clouds','Cloudy','Rain']);assert(fireChance(80,'sunny')>fireChance(80,'fewclouds'));assert(fireChance(80,'fewclouds')>=fireChance(80,'cloudy'));assert.equal(fireChance(100,'rain'),0);for(const weather of Object.keys(WEATHER)){const {g,b,u}=arena();g.random=()=>.65;setWeather(b,weather);if(weather==='rain'){b.fire={3:2};setWeather(b,weather);assert.deepEqual(b.fire,{});const before=JSON.stringify(b);assert.throws(()=>g.battleAction('fireball',{unit:u.id,q:6,r:4}));assert.equal(JSON.stringify(b),before);}else{g.battleAction('fireball',{unit:u.id,q:6,r:4});assert.equal(!!b.fire[4*13+6],weather==='sunny');}}});
test('Old stormy battlefield saves migrate to cloudy while retaining wind and units',()=>{const {g,b}=arena();b.rulesVersion=4;b.weather='stormy';b.wind=6;b.windStrength=3;const s=validateSave(g.s,scenarios,g.terrains);assert.equal(s.battle.rulesVersion,5);assert.equal(s.battle.weather,'cloudy');assert.equal(s.battle.wind,6);assert.equal(s.battle.windStrength,3);assert.deepEqual(s.battle.units,b.units);});
test('Locust famine lowers gold and rice income and expires after a year',()=>{const g=fresh(),p=g.province(9),gold=p.gold,food=p.food;disaster(g,p,'locust',report());assert.equal(p.gold,Math.floor(gold*.85));assert.equal(p.food,Math.floor(food*.75));assert.equal(incomeFactor(g.s,p),.75);g.s.year++;g.s.month++;assert.equal(incomeFactor(g.s,p),1);});
test('Random typhoons stay in Jiao/Yang, floods in the Yellow River regions',()=>{const g=fresh();g.s.month=5;for(const p of g.s.provinces)p.flood=0;g.random=()=>.05;const r=report();runMonthlyEvents(g,r);const affected=r.details.filter(e=>['typhoon','flood'].includes(e.art));assert(affected.some(e=>e.art==='typhoon'));assert(affected.some(e=>e.art==='flood'));for(const e of affected){const region=g.province(e.province).region;assert((e.art==='typhoon'?[11,13]:[1,2,3,4,5,6,7,9]).includes(region));}validateSave(g.s,scenarios,g.terrains);});
test('Uprising and plague reduce loyalty; each has its matching scene',()=>{for(const type of ['uprising','epidemic']){const g=fresh(),p=g.province(9),loyalty=p.loyalty,pop=p.population,r=report();g.random=()=>0;disaster(g,p,type,r);assert(p.loyalty<loyalty);assert(p.population<pop);assert.equal(r.details[0].art,type);assert.equal(eventFrame(r.details[0]).atlas,type==='uprising'?'disasters':'omens');}});
test('Hua Tuo book changes three-month sickness and injury to one month and persists',()=>{for(const key of ['sick','injured']){const ordinary=fresh(),medical=fresh();for(const g of [ordinary,medical]){g.officer(34)[key]=true;g.officer(34).illMonths=3;}const r=report();assert(triggerEvent(medical,'medical',r,{officer:34}));assert.equal(medical.officer(34).illMonths,1);assert.equal(r.details[0].art,'medical');const saved=validateSave(medical.s,scenarios,terrains);assert(saved.officers[34].medicalBook);for(let month=2;month<=4;month++){for(const g of [ordinary,medical]){g.s.month=month;runMonthlyEvents(g,report());}assert.equal(!!medical.officer(34)[key],false);assert.equal(!!ordinary.officer(34)[key],month<4);}}});
test('an unaffiliated officer still recovers after leaving service',()=>{const g=fresh(),o=g.officer(34),p=g.s.provinces.find(p=>p.officers.includes(o.id));p.officers=p.officers.filter(id=>id!==o.id);p.unclaimed.push(o.id);o.owner=255;o.injured=true;o.medicalBook=true;o.illMonths=1;g.s.month=2;runMonthlyEvents(g,report());assert.equal(o.injured,false);assert.equal(o.illMonths,0);});
test('A named comet omen persists, can cause an actual death and repairs officer references',()=>{const g=fresh(),o=g.officer(34),r=report();assert(triggerEvent(g,'meteor',r,{officer:o.id}));assert(r.details[0].text.includes(o.name));assert.equal(r.details[0].art,'meteor');assert(validateSave(g.s,scenarios,terrains).monthlyState.omens.some(x=>x.officer===o.id));g.s.month=2;g.random=()=>0;const next=report();runMonthlyEvents(g,next);assert(o.dead);assert(next.details.some(e=>e.art==='death'&&e.officer===o.id));assert(!g.s.provinces.some(p=>p.officers.includes(o.id)));g.normalize();validateSave(g.s,scenarios,terrains);});
test('Named ruler death creates a valid successor rather than stranding a realm',()=>{const g=fresh(),sun=g.s.officers.find(o=>o.name==='Sun Jian'),r=g.ruler(sun.owner),result=report();assert(officerDeath(g,sun.id,result));assert(sun.dead);assert.notEqual(r.leader,sun.id);assert(result.details.some(e=>e.art==='death'&&e.text.includes('Sun Jian')));g.normalize();validateSave(g.s,scenarios,terrains);});
test('Xun Yu stratagem raises rival hostility and Diaochan chain lowers subordinate loyalty',()=>{const g=fresh(1),r=report();assert(triggerEvent(g,'tiger',r));assert.equal(r.details[0].art,'tiger');assert(r.details[0].text.includes('Xun Yu'));assert(r.details[0].text.includes('mutual hostility'));const z=fresh(),dong=z.s.officers.find(o=>o.name==='Dong Zhuo'),ids=z.s.provinces.filter(p=>p.owner===dong.owner).flatMap(p=>p.officers).filter(id=>id!==dong.id),c=report(),wang=z.s.officers.find(o=>o.name==='Wang Yun');for(const p of z.s.provinces)for(const key of ['officers','hidden','unclaimed'])p[key]=p[key].filter(id=>id!==wang.id);wang.owner=dong.owner;z.province(10).officers.push(wang.id);ids.push(wang.id);const before=ids.map(id=>z.officer(id).loyalty);assert(triggerEvent(z,'chain',c));assert.equal(c.details[0].art,'chain');ids.forEach((id,i)=>assert.equal(z.officer(id).loyalty,Math.max(0,before[i]-20)));z.normalize();validateSave(z.s,scenarios,terrains);});
test('352 distinct officer identities map bijectively to352 unique portrait cells across six scenarios',()=>{assert.equal(OFFICER_ROSTER.length,352);const seen=new Set,frames=new Set;for(const s of scenarios)for(const o of s.officers)if(o.name!=='Unnamed'){assert.equal(portraitIndex(o),o.rosterId);seen.add(o.rosterId);const f=portraitFrame(o);assert(f.cell>=0&&f.cell<16);frames.add(f.atlas+':'+f.cell);}assert.equal(seen.size,352);assert.equal(frames.size,352);for(const s of scenarios)assert.equal(new Set(s.officers.filter(o=>o.name!=='Unnamed').map(o=>o.rosterId)).size,s.officers.filter(o=>o.name!=='Unnamed').length);});
test('Recovered late officers enter only at their original arrival date and older saves upgrade safely',()=>{const g=fresh(5),o=g.s.officers.find(o=>o.name==='Jiang Wei');assert(o.pendingArrival);assert(!g.s.provinces.some(p=>p.officers.includes(o.id)||p.hidden.includes(o.id)||p.unclaimed.includes(o.id)));g.s.year=o.appearanceYear-1;g.s.month=12;runMonthlyEvents(g,report());assert(o.pendingArrival);g.s.year++;g.s.month=1;const r=report();runMonthlyEvents(g,r);assert(!o.pendingArrival);assert(g.province(o.arrivalProvince).unclaimed.includes(o.id));assert(r.details.some(e=>e.officer===o.id));validateSave(g.s,scenarios,terrains);const old=createCampaign(scenarios[0],[0]);for(const t of scenarios[0].officers.filter(o=>o.pendingArrival))Object.assign(old.officers[t.id],{name:'Unnamed',int:0,war:0,charm:0,birth:0});const loaded=validateSave(old,scenarios,terrains);assert(loaded.officers.find(o=>o.name==='Bao Xin').pendingArrival);});
test('Each of the twelve requested event types has a separate artwork frame and real occupation reports retain it',()=>{assert.equal(Object.keys(EVENT_ART).length,12);assert.equal(new Set(Object.values(EVENT_ART).map(([a,c])=>a+':'+c)).size,12);const g=fresh(),p=g.s.provinces.find(p=>p.owner===0&&p.officers.length>1&&p.neighbors.some(id=>g.province(id).owner===255)),target=g.province(p.neighbors.find(id=>g.province(id).owner===255));g.execute('move',{province:p.id,officer:p.officers.find(id=>id!==g.ruler().leader),target:target.id,gold:0,food:0});assert.equal(g.s.lastEvent.art,'occupation');assert.equal(target.owner,0);const loaded=validateSave(g.s,scenarios,terrains);assert.equal(loaded.lastEvent.art,'occupation');});
console.log(`${checks} expansion checks passed.`);
