import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';import {aiBattle,planBattleRoute,distance,at,neighbors,living,reachable} from '../mjs/battle.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));
const fresh=()=>{const state=createCampaign(scenarios[0],[],3);state.seed=6;state.ai={intelligence:90,aggression:75};state.settings.battleView='all';state.familyMode='expanded';return new Game(state,{},structuredClone(terrains));};
function arena(){const g=fresh();g.invade({province:9,target:8,officers:[0,34],governor:33,food:20000});while(g.s.battle.phase==='deployment')aiBattle(g,60);const b=g.s.battle,u=b.units.find(u=>u.id===0);b.terrain=Array(156).fill(0);b.palace={q:8,r:2};b.terrain[2*13+8]=6;b.weather='sunny';b.fire={};b.challengeIssued=[34];b.food={attack:1000000,defend:1000000};Object.assign(u,{q:3,r:2,mobility:2,war:99,ordered:false});const positions=[{q:0,r:0},{q:12,r:11},{q:12,r:10},{q:11,r:10}];for(const v of b.units.filter(v=>v!==u))Object.assign(v,positions.shift(),{war:30,ordered:false});return {g,b,u};}
{
 const {g,b,u}=arena();for(let r=0;r<11;r++)b.terrain[r*13+4]=3;const before=distance(u,b.palace),route=planBattleRoute(b,u);assert(route);assert(route.path.some(p=>p.q===4&&p.r===11));assert(route.path.every(p=>b.terrain[p.r*13+p.q]!==3));aiBattle(g,90);assert.equal(b.lastAction.type,'move');assert(distance(u,b.palace)>=before,'First detour step must not need to reduce straight-line distance');for(let turn=0;turn<45&&(u.q!==b.palace.q||u.r!==b.palace.r);turn++){u.ordered=false;u.mobility=Math.max(2,u.mobility);aiBattle(g,90);}assert.equal(u.q,b.palace.q);assert.equal(u.r,b.palace.r);console.log('PASS Hard AI crosses a distant mountain gap, including initial sideways/away steps, and reaches the palace');
}
{
 const {b,u}=arena();for(let r=0;r<12;r++)b.terrain[r*13+4]=3;b.units=b.units.filter(v=>v.side===u.side);assert.equal(planBattleRoute(b,u),null);for(const n of neighbors(u.q,u.r))b.fire[n.r*13+n.q]=3;assert.equal(planBattleRoute(b,u),null);const x=arena();const ally=x.b.units.find(v=>v.side===x.u.side&&v!==x.u);Object.assign(ally,{q:4,r:2});x.b.fire[3*13+4]=3;const route=planBattleRoute(x.b,x.u);assert(route);assert(route.path.every(p=>!x.b.fire[p.r*13+p.q]&&at(x.b,p.q,p.r)?.id!==ally.id));assert(reachable(x.b,x.u).some(p=>p.q===route.path[0].q&&p.r===route.path[0].r));console.log('PASS Route planning respects mountains, active fires and occupied hexes, returning no route for a sealed destination');
}
{
 const {g,b,u}=arena();const enemy=b.units.find(v=>v.side!==u.side);Object.assign(enemy,{q:4,r:2});b.side='defend';for(const v of b.units.filter(v=>v.side==='defend'))Object.assign(v,{ordered:true});Object.assign(enemy,{ordered:false,mobility:2,war:79});const route=planBattleRoute(b,enemy);assert(route);assert.equal(distance(route, u),1);assert(route.path.every(p=>at(b,p.q,p.r)?.id!==u.id));console.log('PASS Defender plans toward reachable enemy contact rather than trying to enter an occupied enemy hex');
}
{
 const raw=JSON.parse(fs.readFileSync('tests/fixtures/v19-hard-second-battle.json')),g=new Game(validateSave(raw,scenarios,terrains),{},terrains),b=g.s.battle;assert.equal(g.s.difficulty,3);assert.deepEqual(g.s.humanRulers,[]);assert.equal(g.s.ai.intelligence,90);assert.equal(g.s.settings.battleView,'all');assert.equal(b.day,1);assert(b.challengeIssued.length);for(let n=0;n<80&&g.s.battle===b&&b.day===1;n++)assert(g.aiStep());assert(!g.s.battle||g.s.battle!==b||b.day>1,'Previously stalled second battle must advance beyond day one');assert.equal(b.challengeIssued.length,1);validateSave(g.s,scenarios,terrains);console.log('PASS V19 second-battle Hard checkpoint advances past day one without attempting another challenge, including save/load');
}
{
 let completed=0,days=0;for(const scenario of scenarios){const state=createCampaign(scenario,[],3);state.seed=6;state.ai={intelligence:90,aggression:75};state.settings.battleView='all';state.familyMode='expanded';const g=new Game(state,{},terrains);let previous=null,seen=0;for(let i=0;i<2500;i++){if(g.s.battle&&g.s.battle!==previous){previous=g.s.battle;seen++;}g.aiStep();if(g.s.battle?.day>1)days++;if(i%500===0)validateSave(g.s,scenarios,terrains);}validateSave(g.s,scenarios,terrains);assert(seen>=2,'Every scenario must exercise consecutive visible AI battles');completed+=seen;}assert(days>0);console.log(`PASS Zero-player Hard/all-battles campaigns complete 15,000 actions across six scenarios (${completed} battle starts) with valid saves and no tactical exceptions`);
}
