import fs from 'node:fs';import assert from 'node:assert/strict';import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';import {aiBattle,at,direction,distance,palaceGuard,minimumStrikeLoss,aiAttackTarget,living} from '../mjs/battle.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
function arena(multiple=false){const s=createCampaign(scenarios[0],[],3);s.seed=6;s.ai={intelligence:90,aggression:75};s.settings.battleView='all';const g=new Game(s,{},structuredClone(terrains));g.invade({province:9,target:8,officers:[0,34],governor:33,food:20000});while(g.s.battle.phase==='deployment')aiBattle(g,60);const b=g.s.battle,u=b.units.find(v=>v.id===0),f=b.units.find(v=>v.id===34),guard=b.units.find(v=>v.id===b.leaders.defend),reserve=b.units.find(v=>v.side==='defend'&&v!==guard);b.units=b.units.filter(v=>v.side==='attack'||v===guard||multiple&&v===reserve);b.terrain=Array(156).fill(0);b.palace={q:6,r:6};b.terrain[6*13+6]=6;g.terrains[b.target-1]=[...b.terrain];b.day=2;b.completedDays=1;b.side='defend';b.challengeIssued=[];b.fire={};b.food={attack:1000000,defend:1000000};b.weather='sunny';for(const v of b.units)Object.assign(v,{soldiers:5000,startSoldiers:5000,war:90,int:80,training:80,weapons:5000,morale:100,mobility:4,ordered:false,orderDay:0,placed:true,routed:false,fled:false,captured:false});Object.assign(guard,b.palace);Object.assign(u,{q:0,r:0});Object.assign(f,{q:1,r:0});if(multiple)Object.assign(reserve,{q:3,r:3,war:80});for(const o of g.s.officers)o.acted=true;g.random=()=>.5;return {g,b,u,f,guard,reserve};}
test('Lone defender holds the palace against multiple distant attackers at every AI level',()=>{for(const intelligence of [25,60,90]){const {g,b,guard}=arena();for(let day=0;day<8;day++){guard.ordered=false;b.side='defend';aiBattle(g,intelligence);assert.deepEqual({q:guard.q,r:guard.r},b.palace);assert.equal(b.lastAction.type,'wait');assert.equal(palaceGuard(b).id,guard.id);}}});
test('Palace guard attacks adjacent enemies in place and does not charge onto a defeated noncommander tile',()=>{const {g,b,f,guard}=arena();Object.assign(f,direction(guard.q,guard.r,5),{soldiers:100});Object.assign(guard,{soldiers:10000,weapons:10000,war:99});aiBattle(g,90);assert.equal(b.lastAction.type,'attack');assert.equal(f.soldiers,0);assert.deepEqual({q:guard.q,r:guard.r},b.palace);assert.equal(at(b,b.palace.q,b.palace.r).id,guard.id);});
test('Defender prioritises a guaranteed attacking-commander kill and wins without abandoning palace',()=>{const {g,b,u,f,guard}=arena();Object.assign(u,direction(guard.q,guard.r,5),{soldiers:1});Object.assign(f,direction(guard.q,guard.r,2),{soldiers:1});assert.equal(minimumStrikeLoss(b,guard,u),u.soldiers);assert.equal(aiAttackTarget(b,guard,[f,u]).id,u.id);aiBattle(g,90);assert.equal(u.soldiers,0);assert.equal(b.outcome.winner,'defend');assert.deepEqual({q:guard.q,r:guard.r},b.palace);});
test('Multiple defenders retain a palace garrison while another unit intercepts approaching enemies',()=>{const {g,b,u,f,guard,reserve}=arena(true);guard.ordered=true;Object.assign(u,{q:6,r:2});Object.assign(f,{q:0,r:1});aiBattle(g,90);assert.equal(b.lastAction.unit,reserve.id);assert.equal(b.lastAction.type,'move');assert.equal(at(b,b.palace.q,b.palace.r).id,guard.id);assert(distance(reserve,u)<5);});
test('An out-of-position sole defender returns toward an empty palace instead of pursuing distant attackers',()=>{const {g,b,guard}=arena();Object.assign(guard,{q:6,r:8});aiBattle(g,90);assert.equal(b.lastAction.type,'move');assert(distance(guard,b.palace)<2);});
test('Attackers advance on an empty palace and prioritise its guard over unrelated weak neighbours',()=>{const {g,b,u,f,guard}=arena();b.side='attack';guard.placed=true;Object.assign(guard,{q:12,r:11});aiBattle(g,90);assert.equal(b.lastAction.type,'move');assert(distance(u,b.palace)<distance({q:0,r:0},b.palace));const x=arena(true);x.b.side='attack';Object.assign(x.u,{q:5,r:6});Object.assign(x.reserve,direction(x.u.q,x.u.r,4),{soldiers:1});assert.equal(aiAttackTarget(x.b,x.u,[x.reserve,x.guard]).id,x.guard.id);});
test('Palace guard refuses uncertain personal combat but can challenge a commander it is certain to defeat',()=>{const {g,b,u,guard}=arena();b.day=1;b.completedDays=0;Object.assign(u,{war:95});Object.assign(guard,{war:95});b.challenge={challenger:u.id,target:guard.id};b.challengeIssued=[u.id];aiBattle(g,90);assert.equal(b.challenge,null);assert(!guard.captured);assert.deepEqual({q:guard.q,r:guard.r},b.palace);const x=arena();x.b.day=1;x.b.completedDays=0;x.u.war=50;x.guard.war=90;aiBattle(x.g,90);assert.equal(x.b.challenge.target,x.u.id);});
console.log(`${checks} v21 tactical checks passed.`);
