import fs from 'node:fs';import assert from 'node:assert/strict';import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';import {aiBattle,at,direction,distance,palaceGuard,minimumStrikeLoss,aiAttackTarget,living,neighbors,safeFireTarget,tacticalPosition,outcome} from '../mjs/battle.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
function arena(multiple=false){const s=createCampaign(scenarios[0],[],3);s.seed=6;s.ai={intelligence:90,aggression:75};s.settings.battleView='all';const g=new Game(s,{},structuredClone(terrains));g.invade({province:9,target:8,officers:[0,34],governor:33,food:20000});while(g.s.battle.phase==='deployment')aiBattle(g,60);const b=g.s.battle,u=b.units.find(v=>v.id===0),f=b.units.find(v=>v.id===34),guard=b.units.find(v=>v.id===b.leaders.defend),reserve=b.units.find(v=>v.side==='defend'&&v!==guard);b.units=b.units.filter(v=>v.side==='attack'||v===guard||multiple&&v===reserve);b.terrain=Array(156).fill(0);b.palace={q:6,r:6};b.terrain[6*13+6]=6;g.terrains[b.target-1]=[...b.terrain];b.day=2;b.completedDays=1;b.side='defend';b.challengeIssued=[];b.fire={};b.food={attack:1000000,defend:1000000};b.weather='sunny';for(const v of b.units)Object.assign(v,{soldiers:5000,startSoldiers:5000,war:90,int:80,training:80,weapons:5000,morale:100,mobility:4,ordered:false,orderDay:0,placed:true,routed:false,fled:false,captured:false});Object.assign(guard,b.palace);Object.assign(u,{q:0,r:0});Object.assign(f,{q:1,r:0});if(multiple)Object.assign(reserve,{q:3,r:3,war:80});for(const o of g.s.officers)o.acted=true;g.random=()=>.5;return {g,b,u,f,guard,reserve};}

test('Outnumbered palace guard uses safe fire without abandoning palace',()=>{const {g,b,f,guard}=arena();b.wind=0;b.windStrength=0;Object.assign(guard,{soldiers:1000,weapons:1000});Object.assign(f,direction(guard.q,guard.r,5));aiBattle(g,90);assert.equal(b.lastAction.type,'fireball');assert.deepEqual({q:guard.q,r:guard.r},b.palace);});
test('Fire refuses rain and wind spreading into own commander',()=>{const {b,f,guard}=arena();Object.assign(f,direction(guard.q,guard.r,5));b.weather='rain';assert.equal(safeFireTarget(b,guard,[f]),null);b.weather='sunny';for(const c of neighbors(guard.q,guard.r))b.terrain[c.r*13+c.q]=4;b.terrain[f.r*13+f.q]=0;b.wind=Array.from({length:6},(_,i)=>i).find(i=>distance(direction(f.q,f.r,i),guard)===0)+1;b.windStrength=3;assert.equal(safeFireTarget(b,guard,[f]),null);});
test('Defender selects nearby jungle concealment and holds an ambush',()=>{const {b,u,reserve}=arena(true);Object.assign(u,{q:5,r:2});const c={q:5,r:4};b.terrain[c.r*13+c.q]=1;reserve.mobility=6;const choice=tacticalPosition(b,reserve,[u],[c],true);assert(choice);assert.equal(choice.q,c.q);assert.equal(choice.r,c.r);Object.assign(reserve,c);assert.equal(tacticalPosition(b,reserve,[u],[],true).wait,true);});
test('Weak attacker selects dry river bank, never water, and resumes after bounded waiting',()=>{const {b,u,guard}=arena();b.side='attack';Object.assign(u,{q:3,r:3});Object.assign(guard,{q:6,r:3});b.terrain[3*13+5]=4;const c={q:4,r:3};assert.equal(tacticalPosition(b,u,[guard],[c],true).q,4);Object.assign(u,c);assert.equal(tacticalPosition(b,u,[guard],[],true).wait,true);b.day=3;assert.equal(tacticalPosition(b,u,[guard],[],true),null);});
test('Attacking commander refuses uncertain duel with army still intact',()=>{const {g,b,u,guard}=arena();b.day=1;b.completedDays=0;b.side='defend';u.war=90;guard.war=89;b.challenge={challenger:guard.id,target:u.id};b.challengeIssued=[guard.id];aiBattle(g,90);assert(!u.captured);assert.equal(b.challenge,null);});
test('Remaining soldiers do not disguise morale routing as empty army',()=>{const {b}=arena();for(const v of b.units.filter(v=>v.side==='defend')){v.routed=true;v.morale=0;}assert.match(outcome(b).reason,/remaining soldiers/);});
console.log(`${checks} v22 tactical checks passed.`);
