import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';
import {aiBattle,living,direction,outcome} from '../mjs/battle.mjs';
import {validateAIConfig,DEFAULT_AI} from '../mjs/ai-parameters.mjs';
import {messageDuration,MESSAGE_SPEEDS,createMessagePlayer} from '../mjs/message-playback.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
function clock(){let time=0,id=0;const timers=new Map;return {now:()=>time,setTimeout(fn,ms){timers.set(++id,{at:time+ms,fn});return id;},clearTimeout:id=>timers.delete(id),tick(ms){const until=time+ms;while(true){const next=[...timers].filter(([,t])=>t.at<=until).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;time=next[1].at;timers.delete(next[0]);next[1].fn();}time=until;}};}
function arena(){const s=createCampaign(scenarios[0],[0,12]);s.monthlyReview=null;s.settings.battleView='all';const g=new Game(s,{},structuredClone(terrains));g.s.monthlyReview=null;g.invade({province:9,target:8,officers:[0,34],governor:33,food:20000});while(g.s.battle.phase==='deployment')aiBattle(g);const b=g.s.battle,u=b.units.find(x=>x.id===0),v=b.units.find(x=>x.id===34),defender=b.units.find(x=>x.side==='defend');b.terrain=Array(156).fill(0);b.palace={q:12,r:11};b.terrain[155]=6;g.terrains[b.target-1]=[...b.terrain];b.day=2;b.completedDays=1;b.side='attack';b.weather='sunny';b.fire={};b.food={attack:100000,defend:100000};for(const [i,x]of b.units.entries())Object.assign(x,{q:i*2,r:0,morale:100,mobility:20,ordered:false,soldiers:5000,startSoldiers:5000,weapons:5000});Object.assign(u,{q:5,r:5,int:100});Object.assign(v,{q:5,r:4});Object.assign(defender,direction(u.q,u.r,2));return {g,b,u,v,defender};}
test('Every Message Speed lasts exactly 3, 2, 1 or 0.5 seconds without dropped queued messages',()=>{for(const [ms]of MESSAGE_SPEEDS){const c=clock(),seen=[],done=[];const p=createMessagePlayer({clock:c,duration:()=>messageDuration({settings:{messageSpeed:ms}}),show:x=>seen.push(x.text),hide:x=>done.push(x.text)});p.enqueue('first');p.enqueue('second');assert.deepEqual(seen,['first']);c.tick(ms-1);assert.deepEqual(done,[]);c.tick(1);assert.deepEqual(seen,['first','second']);c.tick(ms);assert.deepEqual(done,['first','second']);assert(!p.busy);}});
test('Message pause retains unread time, resume does not restart it and cancellation prevents stale callbacks',()=>{const c=clock(),seen=[],p=createMessagePlayer({clock:c,duration:()=>2000,show:x=>seen.push(x.text)});p.enqueue({text:'monthly',onDone:()=>seen.push('orders')});c.tick(800);p.pause();c.tick(9000);assert(p.busy);p.resume();c.tick(1199);assert.deepEqual(seen,['monthly']);c.tick(1);assert.deepEqual(seen,['monthly','orders']);p.enqueue({text:'old save',onDone:()=>assert.fail('Stale timer')});p.clear();c.tick(3000);assert(!p.busy);});
test('AI tuning validates and merges partial groups while preserving default battlefield policy',()=>{assert.deepEqual(validateAIConfig(JSON.parse(fs.readFileSync('config/ai-config.json'))),DEFAULT_AI);const t=validateAIConfig({battle:{outnumberedPowerRatio:.95}});assert.equal(t.battle.outnumberedPowerRatio,.95);assert.equal(t.battle.safeDuelWarMargin,20);assert.throws(()=>validateAIConfig({battle:{ambushAdvanceEveryDays:0}}));assert.throws(()=>validateAIConfig({governance:{maxInvaders:11}}));assert.throws(()=>validateAIConfig({governance:{politicsChance:1.1}}));assert.throws(()=>validateAIConfig({unknown:{}}));});
test('Both armies lose immediately at zero food while their morale and soldiers remain high',()=>{for(const side of ['attack','defend']){const {b}=arena();b.food[side]=0;const men=living(b).filter(u=>u.side===side).reduce((n,u)=>n+u.soldiers,0);assert(men>0);assert(living(b).filter(u=>u.side===side).every(u=>u.morale===100));assert.equal(outcome(b).winner,side==='attack'?'defend':'attack');assert.match(b.outcome.reason,/food/);}});
test('Food input accepts all available province stock through 3,000,000 and rejects excess atomically',()=>{const s=createCampaign(scenarios[0],[0]);s.settings.battleView='all';const g=new Game(s,{},terrains);g.s.monthlyReview=null;g.province(9).food=3000000;const before=JSON.stringify(g.s);assert.throws(()=>g.invade({province:9,target:8,officers:[0,34],governor:33,food:3000001}));assert.equal(JSON.stringify(g.s),before);g.invade({province:9,target:8,officers:[0,34],governor:33,food:3000000});assert.equal(g.s.battle.food.attack,3000000);assert.equal(g.province(9).food,0);const zero=new Game(createCampaign(scenarios[0],[0]),{},terrains);zero.s.monthlyReview=null;zero.s.settings.battleView='all';zero.invade({province:9,target:8,officers:[0,34],governor:33,food:0});assert.equal(zero.s.battle.food.attack,0);zero.s.battle.phase='battle';assert.equal(outcome(zero.s.battle).winner,'defend');});
test('Fire success/failure and simultaneous attacks identify initiating generals and retain ordered event serials',()=>{for(const fail of [false,true]){const {g,b,u,defender}=arena();g.random=()=>fail?.99:0;const t=g.battleAction('fireball',{unit:u.id,q:defender.q,r:defender.r});assert(t.includes(g.officer(u.id).name));assert.match(t,fail?/failed/:/success/);assert.equal(b.messages.at(-1).text,t);}const {g,b,u,v,defender}=arena();Object.assign(v,direction(defender.q,defender.r,1));const text=g.battleAction('simultaneous',{unit:u.id,target:defender.id});assert(text.includes(g.officer(u.id).name));assert.match(text,/simultaneous/);assert(b.messages.every((m,i)=>!i||m.serial>b.messages[i-1].serial));const restored=validateSave(g.s,scenarios,g.terrains);assert.deepEqual(restored.battle.messages,b.messages);});
test('Legacy saves receive Message Speed from their former speed and malformed message queues are rejected',()=>{for(const [old,ms]of [[1200,3000],[600,2000],[300,1000],[100,500]]){const s=createCampaign(scenarios[0],[0]);delete s.settings.messageSpeed;s.speed=old;assert.equal(validateSave(s,scenarios,terrains).settings.messageSpeed,ms);}const {g,b}=arena();b.messages.push({serial:b.eventSerial+1,text:'future',day:2});assert.throws(()=>validateSave(g.s,scenarios,g.terrains),/battle messages/);});
console.log(`${checks} v23 regression groups passed.`);
