import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';
import {aiBattle,dailyMobility,fireLoss,terrainCost,reachable} from '../mjs/battle.mjs';
import {messageDuration} from '../mjs/message-playback.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS',name);};
function arena(){const g=new Game(createCampaign(scenarios[0],[0]),{},terrains);g.s.monthlyReview=null;g.s.settings.battleView='all';g.invade({province:9,target:8,officers:[0,34],governor:33,food:20000});while(g.s.battle.phase==='deployment')aiBattle(g);const b=g.s.battle,u=b.units[0];b.terrain=Array(156).fill(0);b.terrain[155]=6;b.palace={q:12,r:11};b.food={attack:1000000,defend:1000000};b.wind=0;b.windStrength=0;b.weather='sunny';for(const [i,v]of b.units.entries())Object.assign(v,{q:i+1,r:i?1:6,ordered:false,training:20,mobility:2,soldiers:5000,morale:100});return {g,b,u};}
test('A spent move restores two next turn; Wait then banks three, four and up to six',()=>{const {g,b,u}=arena();const move=reachable(b,u).find(p=>p.q===u.q&&p.r===u.r-1);g.battleAction('move',{unit:u.id,...move});assert.equal(u.mobility,0);g.battleAction('end');g.battleAction('end');assert.equal(u.mobility,2);for(const expected of [3,4,5,6,6]){g.battleAction('wait',{unit:u.id});assert.equal(u.mobility,expected);g.battleAction('end');g.battleAction('end');assert.equal(u.mobility,expected);}});
test('Water costs five points in reachability and the actual Move order',()=>{const {g,b,u}=arena();b.terrain[(u.r-1)*13+u.q]=4;u.mobility=4;assert(!reachable(b,u).some(p=>p.q===u.q&&p.r===u.r-1));u.mobility=5;const move=reachable(b,u).find(p=>p.q===u.q&&p.r===u.r-1);assert(move);g.battleAction('move',{unit:u.id,...move});assert.equal(u.mobility,0);assert.equal(terrainCost(4),5);});
test('Native training allowance has correct thresholds and retains banked mobility',()=>{assert.deepEqual([0,1,20,21,40,41,80,81,100].map(dailyMobility),[2,2,2,3,3,4,5,6,6]);});
test('Native fire is random below thirty percent, without mandatory hundred or morale damage',()=>{assert.equal(fireLoss(5000,0),0);assert.equal(fireLoss(5000,.5),750);assert.equal(fireLoss(5000,.999999),1499);assert.equal(fireLoss(99,0),99);const {g,b,u}=arena();b.fire[u.r*13+u.q]=3;b.side='defend';g.random=()=>.5;g.battleAction('end');assert.equal(u.soldiers,4250);assert.equal(u.morale,100);});
test('One saved speed controls scheduler and message durations, including legacy migration',()=>{for(const speed of [500,1000,2000,3000]){const s=createCampaign(scenarios[0],[]);s.speed=speed;s.settings.messageSpeed=1000;const v=validateSave(s,scenarios,terrains);assert.equal(v.speed,speed);assert.equal(messageDuration(v),speed);assert.equal(v.settings.messageSpeed,speed);}});
console.log(`${count} v25 regression groups passed.`);
