import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';
import {beginWarReport,extendWarReport,warReportText,acrossChinaChronology,provinceCurrentEvents,validateWarHistory} from '../mjs/event-chronicle.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrain=JSON.parse(fs.readFileSync('config/province-terrain.json'));
const fresh=()=>{const g=new Game(createCampaign(scenarios[0],[0]),{},terrain);g.s.monthlyReview=null;g.s.settings.battleView='all';return g;};
function battle(){const g=fresh();g.random=()=>0;g.invade({province:9,target:8,governor:33,officers:[0,34],food:20000});return g;}
function victory(){const g=battle(),b=g.s.battle;for(const id of g.province(8).neighbors){const p=g.province(id);if(p.owner===255){const source=g.province(9),officer=source.officers.find(id=>id!==33);if(officer!==undefined){source.officers=source.officers.filter(id=>id!==officer);p.officers.push(officer);p.owner=0;p.governor=officer;}}}b.outcome={winner:'attack',reason:'Palace occupied'};g.resolveBattle();return g;}
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS',name);};
test('A war has one dated summary even after hundreds of tactical messages',()=>{const g=battle(),row=g.s.warChronicle[0];for(let i=0;i<250;i++)g.record(`Day ${i%30+1}: Defending army’s orders.`,'war');assert.equal(g.s.log.length,160);assert.equal(acrossChinaChronology(g).filter(e=>e.text.includes('attacked')).length,1);assert(warReportText(g.s,row).includes('Jan 189 AD: Cao Cao #9 attacked Kong Rong #8. In progress.'));assert.equal(beginWarReport(g,g.s.battle),row);});
test('Extended January and won February retain distinct summaries for the same war',()=>{const g=battle(),b=g.s.battle;extendWarReport(g,b);g.s.month=2;beginWarReport(g,b);assert.equal(g.s.warChronicle.length,2);assert(warReportText(g.s,g.s.warChronicle[0]).endsWith('Extended to next month.'));b.outcome={winner:'attack',reason:'Palace occupied'};g.resolveBattle();assert.equal(g.s.warChronicle[0].status,'extended');assert.equal(g.s.warChronicle[1].status,'won');assert(acrossChinaChronology(g)[0].text.startsWith('Feb 189 AD:'));});
test('Refused recruitment remains pending; final dispositions update once and survive load',()=>{const g=victory(),row=g.s.warChronicle[0];assert(row.fates.length);g.acknowledgeTriumph();const c=g.s.captiveDecisions.find(c=>c.role!=='Ruler');assert(c);g.random=()=>.999;assert.equal(g.decideCaptive(c.officer,'recruit'),false);assert.equal(row.fates.find(f=>f.officer===c.officer).action,'pending');assert(!acrossChinaChronology(g).some(e=>/refused recruitment|Day \d/.test(e.text)));g.decideCaptive(c.officer,'free');assert.equal(row.fates.filter(f=>f.officer===c.officer).length,1);assert(warReportText(g.s,row).includes('set free — '+g.officer(c.officer).name));const restored=new Game(validateSave(g.s,scenarios,terrain),{},terrain);assert.deepEqual(restored.s.warChronicle,g.s.warChronicle);});
test('Recruit, behead and ruler release are distinct, including snapshots after succession',()=>{const g=victory();g.acknowledgeTriumph();const row=g.s.warChronicle[0],ruler=g.s.captiveDecisions.find(c=>c.role==='Ruler'),others=g.s.captiveDecisions.filter(c=>c.role!=='Ruler');assert(ruler&&others.length>=2);g.random=()=>0;g.decideCaptive(others[0].officer,'recruit');g.decideCaptive(others[1].officer,'behead');g.decideCaptive(ruler.officer,'free');const text=warReportText(g.s,row);assert(text.includes('opposing ruler was set free'));assert(text.includes('recruited — '+g.officer(others[0].officer).name));assert(text.includes('beheaded — '+g.officer(others[1].officer).name));const names=[row.attacker.name,row.defender.name];g.ruler(row.defender.id).name='Changed ruler';assert(names.every(name=>warReportText(g.s,row).includes(name)));validateSave(g.s,scenarios,terrain);});
test('A defeated invasion reports an unharmed returning ruler without pretending they were captured',()=>{const g=battle();g.s.battle.outcome={winner:'defend',reason:'Invaders withdrew'};g.resolveBattle();const text=warReportText(g.s,g.s.warChronicle[0]);assert(text.includes('Defeated. The attacking ruler returned unharmed.'));assert(text.includes('recruited — none'));});
test('Current province list has all 41 live provinces, local events only, and no battle/captive spam',()=>{const g=battle();g.record('Chen Deng moved to 8,5, spending 3 mobility.','war');g.record('Mi Zhu: set free.','prison',{battleOutcome:true,province:17});g.record(g.province(9).name+': cultivated land.');const list=provinceCurrentEvents(g);assert.equal(list.length,41);assert.equal(list[8].events.length,1);assert(list[8].events[0].text.includes('cultivated'));assert.equal(list[16].events.length,0);g.province(17).owner=0;assert.equal(provinceCurrentEvents(g)[16].province.owner,0);});
test('Legacy tactical logs are hidden, and old suspended battles migrate only known dates and provinces',()=>{const g=battle(),b=g.s.battle;b.suspended=true;g.suspendBattle();delete b.chronicleWar;delete g.s.warChronicle;delete g.s.warSerial;g.s.month=2;const restored=new Game(g.s,{},terrain);assert.equal(restored.s.warChronicle[0].month,1);assert.equal(restored.s.warChronicle[0].status,'extended');assert.equal(restored.s.warChronicle[0].source,9);g.record('Tao Qian refused recruitment. Decide whether to set them free or behead them.','prison');assert(!acrossChinaChronology(g).some(x=>x.text.includes('refused')));});
test('Malformed history, duplicate outcomes and forged captive links reject during save validation',()=>{const g=victory();for(const mutate of [s=>s.warChronicle[0].month=13,s=>s.warChronicle.push(structuredClone(s.warChronicle[0])),s=>s.warChronicle[0].fates.push(structuredClone(s.warChronicle[0].fates[0])),s=>s.captiveDecisions[0].warId=9999]){const s=structuredClone(g.s);mutate(s);assert.throws(()=>validateSave(s,scenarios,terrain),/chronicle/);}validateWarHistory(g.s);});
console.log(`${count} v27 event chronology regression groups passed.`);
