import {createHash} from 'node:crypto';const fsHash=text=>createHash('sha256').update(text).digest('hex');
import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';
import {NATIVE_POLICIES,NATIVE_GROUPS,nativePolicy,nativeGroupOrders,runNativePriority} from '../mjs/native-governance-priority.mjs';
import {ambushExchange,fleeChance,trainingGain,giveFoodGain} from '../mjs/native-combat.mjs';
import {ambushCells,spawnBattle,direction,retreatOptions,aiBattle,living} from '../mjs/battle.mjs';
import {captiveActions,takeCaptive} from '../mjs/campaign-decisions.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));
const fresh=(options={})=>{const g=new Game(createCampaign(scenarios[0],[0],3),{},structuredClone(terrains),options);g.s.monthlyReview=null;g.s.settings.battleView='all';return g;};
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS',name);};
const vectors=JSON.parse(fs.readFileSync('docs/native-battle-vectors-v33.json'));
test('812 controlled native vectors agree with ambush, flight, Train, Give and hex trigger geometry',()=>{
 for(const v of vectors.ambush){const rolls=[(v.random300+.1)/300,(v.random30+.1)/30];assert.deepEqual(ambushExchange(v.mover,v.ambusher,v.terrain,()=>rolls.shift(),v.factor),{loss:v.loss,weapons:v.weapons});}
 for(const v of vectors.flight){assert.equal(fleeChance({...v.unit,mobility:v.mobility},v.enemies,v.ruler,v.random10),v.chance);assert.equal(v.unit.hasHorse||v.roll100<v.chance,v.escaped);}
 for(const v of vectors.training)assert.equal(trainingGain({war:v.war},v.armies),v.gain);
 for(const v of vectors.give)assert.equal(giveFoodGain(v.population,v.governorCharm,v.officerCharm,v.food,v.difficulty),v.gain);
 for(const v of vectors.geometry)assert.deepEqual(ambushCells({q:v.fromCell[0],r:v.fromCell[1]},{q:v.toCell[0],r:v.toCell[1]}).map(p=>[p.q,p.r]),v.cells);
 assert.equal(Object.values(vectors).reduce((n,x)=>n+x.length,0),812);
});
test('Native local governance table selects ambition policy and rotates with original retry counts',()=>{
 assert.equal(nativePolicy(79,()=>{throw Error('Unneeded policy RNG');}),0);assert.equal(nativePolicy(80,()=>0),1);assert.equal(nativePolicy(100,()=>.999),2);
 assert.deepEqual(NATIVE_POLICIES[0],['domestic','personnel','domestic','military','movement']);
 assert.deepEqual(NATIVE_GROUPS.domestic,['relief','develop','flood','sellFood','buyHorses']);
 assert.deepEqual(nativeGroupOrders('military',3,()=>.75),['buyWeapons','trainArmy','hireArmy']);
 assert.deepEqual(nativeGroupOrders('personnel',3,()=>.5),['search','rewardWritings','reward','recruit']);
 const attempts=[];assert(runNativePriority(1,3,()=>0,x=>{attempts.push(x);return x==='trainArmy';}));assert.deepEqual(attempts,['relief','develop','flood','sellFood','trainArmy']);
});
test('Rulers have two captive options; execution announces an heir and 100 hostility toward the killer',()=>{
 const g=fresh(),r=g.ruler(0),old=r.leader;takeCaptive(g,old,12,8,0,'battle','Ruler');const c=g.s.captiveDecisions[0];assert(g.s.provinces.some(p=>p.owner===0));assert.deepEqual(captiveActions(g,c),['free','behead']);const before=JSON.stringify(g.s);assert.throws(()=>g.decideCaptive(old,'recruit'));assert.equal(JSON.stringify(g.s),before);g.decideCaptive(old,'behead');assert.notEqual(r.leader,old);assert.equal(r.relations[12],100);assert.equal(r.enemy,12);assert(g.s.log.some(e=>e.event?.art==='heir'));assert(g.s.successorDecisions.some(d=>d.owner===0));validateSave(g.s,scenarios,g.terrains);
});
function arena(options={}){const g=fresh(options);g.invade({province:9,target:8,officers:[0,34],governor:33,food:20000});while(g.s.battle.phase==='deployment')aiBattle(g,80);const b=g.s.battle,u=b.units.find(u=>u.id===0),v=b.units.find(u=>u.side==='defend'&&u.id!==b.leaders.defend);b.terrain=Array(156).fill(0);b.terrain[155]=6;g.terrains[7]=[...b.terrain];b.palace={q:12,r:11};for(const x of b.units)Object.assign(x,{q:x.id%12,r:10,placed:true,soldiers:5000,startSoldiers:5000,weapons:5000,int:80,war:80,training:20,mobility:20,ordered:false,orderDay:0,routed:false,captured:false,fled:false});Object.assign(u,{q:6,r:5});Object.assign(v,{q:6,r:7});b.terrain[7*13+6]=1;g.terrains[7]=[...b.terrain];b.selected=u.id;g.random=()=>.5;return {g,b,u,v};}
test('Moving beside a waiting forest defender automatically ambushes; INT 90 evades without consuming RNG',()=>{
 for(const intelligence of [89,90]){const {g,b,u,v}=arena();u.int=intelligence;v.ordered=true;v.mobility=0;const before=u.soldiers,mp=v.mobility;g.battleAction('move',{unit:u.id,q:6,r:6});assert.equal(u.soldiers<before,intelligence===89);assert(b.events.some(t=>t.includes('ambushed')));assert.equal(v.mobility,mp);assert(v.ordered);assert.equal(v.soldiers,5000);}
 let calls=0;const a={soldiers:1000,weapons:1000,war:80,int:90,training:50};assert.equal(ambushExchange(a,a,0,()=>{calls++;return .5;}).loss,0);assert.equal(calls,0);
});
test('Zero-men melee victims leave the field immediately and emit a capture status',()=>{const {g,b,u,v}=arena();Object.assign(v,direction(u.q,u.r,4),{soldiers:1,int:90});g.battleAction('charge',{unit:u.id,target:v.id});assert.equal(v.soldiers,0);assert(!living(b).some(x=>x.id===v.id));assert(v.captured);assert(b.messages.some(m=>m.text.includes('army depleted to 0; captured')));assert.deepEqual({q:u.q,r:u.r},{q:v.q,r:v.r});});
test('Adjacent friendly provinces are retreat destinations for either side; hostile provinces are excluded',()=>{const {g,b,u,v}=arena(),p=g.province(g.province(b.target).neighbors.find(id=>id!==b.source));p.owner=b.defender;for(const id of p.officers)g.officer(id).owner=b.defender;g.normalize();assert(g.province(8).neighbors.includes(p.id));assert(retreatOptions(g,v).some(q=>q.id===p.id));assert(!retreatOptions(g,u).some(q=>q.id===p.id));assert(!retreatOptions(g,v).some(q=>q.id===b.source));});
test('Flight restores training mobility, can fail even without contact, and horses guarantee success',()=>{for(const mounted of [false,true]){const {g,b}=arena(),u=b.units.find(x=>x.side==='attack'&&x.id!==b.leaders.attack);Object.assign(u,{war:0,training:0,mobility:0,soldiers:100});g.officer(u.id).hasHorse=mounted;g.random=()=>.99;g.battleAction('flee',{unit:u.id,province:b.source});assert.equal(u.fled,mounted);assert.equal(u.captured,!mounted);assert(b.messages.some(m=>m.text.includes(mounted?'fled successfully':'tried to flee — captured')));if(!mounted)assert.equal(u.mobility,2);}});
test('Watched results retain the field, pause AI and survive save/load until acknowledgement',()=>{const {g,b,u}=arena({reviewBattleResult:true});for(const x of b.units)g.officer(x.id).hasHorse=true;g.battleAction('flee',{unit:u.id,confirmArmy:true});assert.equal(g.s.battle,b);assert(b.awaitingResult);assert.equal(g.aiStep(),false);const h=new Game(validateSave(g.s,scenarios,g.terrains),{},g.terrains,{reviewBattleResult:true});assert(h.s.battle.awaitingResult);assert.equal(h.acknowledgeBattleResult(),true);assert.equal(h.s.battle,null);assert.equal(h.s.lastBattle.winner,'defend');assert.equal(h.acknowledgeBattleResult(),false);});
test('Unwatched and headless results settle immediately without introducing a result queue',()=>{const {g,b,u}=arena();for(const x of b.units)g.officer(x.id).hasHorse=true;g.battleAction('flee',{unit:u.id,confirmArmy:true});assert.equal(g.s.battle,null);const a=arena({reviewBattleResult:true});a.g.s.humanRulers=[];a.g.s.settings.battleView='personal';a.b.outcome={winner:'attack',reason:'Unwatched result'};a.g.finishBattle();assert.equal(a.g.s.battle,null);});
test('Train excludes full-training armies and includes zero-men officers in the resulting training update',()=>{const g=fresh(),p=g.province(9);for(const id of p.officers)Object.assign(g.officer(id),{soldiers:0,training:20,acted:false});const trainer=g.officer(p.officers[0]),trained=g.officer(p.officers[1]);trained.soldiers=10000;trained.training=100;const trainee=g.officer(p.officers[2]);trainee.soldiers=101;trainer.war=50;g.execute('trainArmy',{province:9,officer:trainer.id});assert.equal(trainer.training,100);assert.equal(trainee.training,100);assert.equal(trained.training,100);});
test('Give uses the local governor rather than a distant ruler for the loyalty gain',()=>{const g=fresh(),p=g.province(9),actor=g.officer(34);p.governor=33;g.officer(33).charm=20;g.officer(g.ruler().leader).charm=100;actor.charm=20;assert.equal(g.relief(p,actor,10000),giveFoodGain(p.population,20,20,10000,3));});
test('Battle HUD edits training and each army gold store within their native capacities',()=>{const {g,b,u}=arena();g.cheat('battle',u.id,{training:88,attackGold:12000,defendGold:22000});assert.equal(u.training,88);assert.deepEqual(b.gold,{attack:12000,defend:22000});assert.throws(()=>g.cheat('battle',u.id,{defendGold:30001}));});
test('Monthly advisor availability and order advice sources are unchanged except cache revision',()=>{const expected=JSON.parse(fs.readFileSync('docs/advice-preservation-v33.json'));for(const [file,hash]of Object.entries(expected)){const bytes=fs.readFileSync(file,'utf8').replace(/\?v=(33|34)/g,'?v=32');assert.equal(fs.readFileSync(file,'utf8').includes('?v=35'),false);assert.equal((awaitHash(bytes)),hash);}function awaitHash(bytes){return fsHash(bytes);}});
console.log(`${n} v33 native battle, governance and presentation checks passed.`);
