import fs from 'node:fs';import assert from 'node:assert/strict';
import {Game,createCampaign,validateSave} from '../mjs/strategy.mjs';
import {disaster} from '../mjs/monthly-events.mjs';
import {aiBattle,retreatOptions} from '../mjs/battle.mjs';
const scenarios=JSON.parse(fs.readFileSync('config/scenarios.json')),terrains=JSON.parse(fs.readFileSync('config/province-terrain.json'));
function battle(review=true){const g=new Game(createCampaign(scenarios[0],[0]),{},structuredClone(terrains),{reviewBattleResult:review});g.s.settings.battleView='all';g.invade({province:9,target:8,governor:33,officers:[0,34],food:20000});while(g.s.battle.phase==='deployment')aiBattle(g);const b=g.s.battle;b.outcome={winner:'defend',reason:'The palace was defended.'};return {g,b};}
let n=0;function test(name,f){f();n++;console.log('PASS',name);}
test('Defeated humans choose individually after result; cancellation/invalid destinations do not roll or mutate',()=>{const {g,b}=battle();g.finishBattle();assert(b.awaitingResult);assert.equal(g.acknowledgeBattleResult(),false);assert(b.resultReviewed);const first=g.defeatedWithdrawal()[0];assert(first);const before=JSON.stringify(g.s);assert.throws(()=>g.retreatDefeatedUnit(first.id,b.target));assert.equal(JSON.stringify(g.s),before);g.officer(first.id).hasHorse=true;g.retreatDefeatedUnit(first.id,b.source);assert(first.fled);assert(first.retreatProvince===b.source);assert(g.defeatedWithdrawal().length===1);validateSave(g.s,scenarios,g.terrains);const h=new Game(validateSave(g.s,scenarios,g.terrains),{},g.terrains,{reviewBattleResult:true});const next=h.defeatedWithdrawal()[0];h.officer(next.id).hasHorse=true;h.retreatDefeatedUnit(next.id,b.source);assert(!h.defeatedWithdrawal().length);assert(h.acknowledgeBattleResult());assert(h.province(b.source).officers.includes(first.id));assert(h.province(b.source).officers.includes(next.id));validateSave(h.s,scenarios,h.terrains);});
test('Compulsory field retreat can fail without adjacent enemies, using native flight rather than INT capture chance',()=>{const {g,b}=battle();g.s.humanRulers=[];for(const u of b.units.filter(u=>u.side==='attack'))Object.assign(u,{war:0,training:0,mobility:0,soldiers:100,int:100});g.random=()=>.99;g.finishBattle();assert(b.units.filter(u=>u.side==='attack').every(u=>u.captured&&!u.fled));assert(b.messages.some(x=>x.text.includes('tried to flee — captured')));assert(g.acknowledgeBattleResult());validateSave(g.s,scenarios,g.terrains);});
test('No exit causes capture without RNG, even for a mounted officer; friendly neighbours permit retreat',()=>{const {g,b}=battle();for(const id of g.province(b.target).neighbors){const p=g.province(id);p.owner=b.defender;for(const x of p.officers)g.officer(x).owner=b.defender;}g.normalize();for(const u of b.units.filter(u=>u.side==='attack'))g.officer(u.id).hasHorse=true;g.random=()=>{throw Error('No escape roll without destination');};g.finishBattle();assert(b.units.filter(u=>u.side==='attack').every(u=>u.captured));assert(b.messages.some(x=>x.text.includes('no adjacent')));});
test('Automatic field withdrawal prefers the original friendly province and does not reroll on repeated finish/save-load',()=>{const {g,b}=battle();g.s.humanRulers=[];for(const u of b.units.filter(u=>u.side==='attack'))g.officer(u.id).hasHorse=true;g.finishBattle();assert(b.units.filter(u=>u.side==='attack').every(u=>u.fled&&u.retreatProvince===b.source));const before=JSON.stringify(b);g.random=()=>{throw Error('Disposed troops must not roll again');};g.finishBattle();assert.equal(JSON.stringify(b),before);new Game(validateSave(g.s,scenarios,g.terrains),{},g.terrains,{reviewBattleResult:true});});
test('Governor rebellion cannot recycle the ruler ID of an active exile party',()=>{const {g}=battle(false);g.s.battle=null;const retired=g.ruler(12);for(const q of g.s.provinces.filter(p=>p.owner===retired.id)){q.owner=255;q.officers=[];q.governor=null;}for(let id=0;id<16;id++)if(!g.ruler(id))g.s.rulers.push({id,leader:1,name:'Retired',alliances:[]});g.s.roaming.push({owner:retired.id,province:9,officers:[retired.leader],gold:0,food:0});const leader=retired.leader,p=g.province(9);p.governor=33;disaster(g,p,'rebellion',{events:[],details:[]});assert.equal(g.ruler(retired.id).leader,leader);assert.notEqual(p.owner,retired.id);});
console.log(`${n} compulsory retreat checks passed.`);
