import {canAdvise,ADVICE_UNAVAILABLE} from './monthly-advice.mjs?v=34';
import {provinceLabel} from './province-choice.mjs?v=34';
export function adviceTopic(g,p,topic){
 const r=g.ruler(),advisor=r.advisor===null?null:g.officer(r.advisor);if(!advisor||!p.officers.includes(advisor.id))return 'Your advisor must be present in this province.';
 if(!canAdvise(g.s,r,advisor,topic))return `${advisor.name}: ${ADVICE_UNAVAILABLE}`;
 const key=`${g.s.year*12+g.s.month-1}:${p.id}:${topic}`;g.s.adviceReports=Object.fromEntries(Object.entries(g.s.adviceReports||{}).filter(([k])=>k.startsWith((g.s.year*12+g.s.month-1)+':')));if(g.s.adviceReports[key])return g.s.adviceReports[key];
 let text;if(topic==='war'){const men=p.officers.reduce((n,id)=>n+g.officer(id).soldiers,0),target=p.neighbors.map(id=>g.province(id)).filter(q=>![255,r.id].includes(q.owner)&&!r.alliances.includes(q.owner)).sort((a,b)=>a.officers.reduce((n,id)=>n+g.officer(id).soldiers,0)-b.officers.reduce((n,id)=>n+g.officer(id).soldiers,0))[0];text=target?`${provinceLabel(g,target)} has ${target.officers.reduce((n,id)=>n+g.officer(id).soldiers,0)} men; we have ${men}. ${p.food<men?'Improve our supplies first.':men>target.officers.reduce((n,id)=>n+g.officer(id).soldiers,0)*1.3?'We hold an advantage.':'Train and recruit before committing.'}`:'There is no hostile neighboring province.';}
 else if(topic==='officers'){const choices=p.officers.map(id=>g.officer(id)).filter(o=>o.id!==r.leader).sort((a,b)=>a.loyalty-b.loyalty),weak=choices[0];text=weak?`${weak.name} has loyalty ${weak.loyalty}. ${weak.loyalty<70?'Reward this general before sending them on important missions.':'Our officers are dependable.'}`:'No subordinate is serving here.';}
 else if(topic==='spy'){const targets=g.s.provinces.filter(q=>![255,r.id].includes(q.owner)).flatMap(q=>q.officers.map(id=>({p:q,o:g.officer(id)}))).filter(x=>x.o.id!==g.ruler(x.p.owner).leader).sort((a,b)=>a.o.loyalty-b.o.loyalty);text=targets.length?`${targets[0].o.name} in ${provinceLabel(g,targets[0].p)} has loyalty ${targets[0].o.loyalty}. ${targets[0].o.loyalty<60?'A recruitment or betrayal mission may succeed.':'Enemy loyalty is strong; use intelligence gathering first.'}`:'No rival subordinate is known.';}
 else if(topic==='visitors'){const v=g.s.visitors;text=`Hua Tuo: ${provinceLabel(g,g.province(v.huaTuo))}; Sima Hui: ${provinceLabel(g,g.province(v.scholar))}; Xu Shao: ${provinceLabel(g,g.province(v.critic))}.`;}
 else throw Error('Choose a council topic.');g.s.adviceReports[key]=`${advisor.name}: ${text}`;return g.s.adviceReports[key];
}
