import {cleanEventLanguage,withImpact} from './event-impact.mjs?v=31';
export function eventFor(game){const s=game.s;if(s.eventPreview)return {...s.eventPreview,preview:true};if(s.monthlyReview&&s.lastReport?.details?.[s.monthlyReview.index])return s.lastReport.details[s.monthlyReview.index];if(s.battle&&game.battleDetailed()){const b=s.battle;return {kind:'war',province:b.target,title:`${game.province(b.target).name} · ${b.phase==='deployment'?'Deployment':'Day '+b.day}`,text:b.events[0]||`${game.ruler(b.attacker).name} has invaded.`,officer:b.selected};}if(s.lastEvent)return s.lastEvent;const entry=s.log[0];return {kind:entry?.type==='war'?'war':'council',title:entry?'The chronicle':'The council awaits',text:entry?.text||'Select a province, then choose an order.',officer:game.province(s.selected).governor};}
export const eventCell=kind=>({diplomacy:0,prison:1,war:2,council:3,order:3,month:3,cheat:3})[kind]??3;
// Each requested event has a separate scene; ordinary council/diplomacy retain their original art.
export const EVENT_ART={clan:['clan',0],heir:['heir',0],locust:['disasters',0],uprising:['disasters',1],typhoon:['disasters',2],flood:['disasters',3],epidemic:['omens',0],meteor:['omens',1],war:['omens',2],occupation:['omens',3],tiger:['stories',0],death:['stories',1],chain:['stories',2],medical:['stories',3]};
export function eventFrame(event){if(event.kind==='history'||event.art==='history'){const year=event.historyYear??Number(event.title?.match(/\b(\d{3})\b/)?.[1]),cell=HISTORY_YEARS.indexOf(year);return {atlas:'history',cell:cell<0?15:cell};}const frame=EVENT_ART[event.art||event.kind];return frame?{atlas:frame[0],cell:frame[1]}:{atlas:'events',cell:eventCell(event.kind)};}

export const HISTORY_YEARS=[189,190,192,194,197,200,207,208,215,219,220,221,222,223,229];
export function presentEvent(game,event){const e={...event};if(e.kind==='history'){e.art='history';e.historyYear??=Number(e.title?.match(/\b(\d{3})\b/)?.[1])||game.s.log.find(x=>x.text===e.text&&x.type==='history')?.year||game.s.year;}if(Number.isInteger(e.province)&&game.s.provinces[e.province-1]){e.title=cleanEventLanguage(e.title);e.text=cleanEventLanguage(e.text);if(e.impact)e.text=withImpact(e.text,e.impact);}return e;}
