import {trainingGain} from './native-combat.mjs?v=34';
import {recruitmentProtection} from './campaign-fidelity.mjs?v=34';
import {canAdvise,ADVICE_UNAVAILABLE} from './monthly-advice.mjs?v=34';
import {provinceLabel} from './province-choice.mjs?v=34';
import {surrenderRealm,askJointConsent} from './campaign-completion.mjs?v=34';
import {clamp} from './engine.mjs?v=34';
import {disaster,monthNumber} from './monthly-events.mjs?v=34';
import {courtMarriage,checkRoyalProposal,acceptRoyalProposal} from './ruler-family.mjs?v=34';

export const NEW_ORDERS=new Set(['hireArmy','reassignArmy','trainArmy','rewardGold','rewardHorse','rewardWritings','dismiss','diplomaticMission','spyMission','delegateRealm','selfExile','healing','courtMarriage']);
export const readyOfficers=(g,p)=>p.officers.map(id=>g.officer(id)).filter(o=>!o.acted&&!o.sick&&!o.injured);
export const rulerPresent=(g,p)=>p.officers.includes(g.ruler().leader);
export function hireCapacity(g,p){const people=Math.floor(p.population/100),men=Math.floor(p.officers.reduce((n,id)=>n+g.officer(id).soldiers,0)/100),space=Math.ceil(p.officers.reduce((n,id)=>n+10000-g.officer(id).soldiers,0)/100);return Math.max(0,Math.floor(Math.min(people-500,(people-men)/2,p.food/100,p.gold/10,space)));}
const active=(g,id)=>g.s.rulers.find(r=>r.id===Number(id)&&g.s.provinces.some(p=>p.owner===r.id));
const strength=(g,id)=>g.s.provinces.filter(p=>p.owner===id).reduce((n,p)=>n+p.officers.reduce((s,i)=>s+g.officer(i).soldiers,0),0);
const advisorInt=(g,r)=>r.advisor===null?g.officer(r.leader).int:g.officer(r.advisor).int;
function relation(a,b,value){const delta=value-(a.relations[b.id]??50);a.relations[b.id]=clamp(value);b.relations[a.id]=clamp((b.relations[a.id]??50)+delta);}
function ally(a,b){if(!a.alliances.includes(b.id))a.alliances.push(b.id);if(!b.alliances.includes(a.id))b.alliances.push(a.id);}
function sever(g,a,b){a.alliances=a.alliances.filter(id=>id!==b.id);b.alliances=b.alliances.filter(id=>id!==a.id);g.s.jointPlans=(g.s.jointPlans||[]).filter(p=>!([p.ruler,p.ally].includes(a.id)&&[p.ruler,p.ally].includes(b.id)));}
function homeOnly(g,p){if(!rulerPresent(g,p))throw Error('Issue this order where your ruler is staying.');}
function detach(g,id){for(const p of g.s.provinces)for(const key of ['officers','unclaimed','hidden'])p[key]=p[key].filter(i=>i!==id);for(const r of g.s.rulers)if(r.advisor===id)r.advisor=null;}

export function updateVisitors(g){const key=monthNumber(g.s);if(g.s.visitors?.month===key)return g.s.visitors;if(g.s.visitors){const v=g.s.visitors;for(const k of ['huaTuo','scholar','critic']){const options=[v[k],...g.province(v[k]).neighbors];v[k]=options[g.int(0,options.length-1)];}v.month=key;return v;}const ids=g.s.provinces.map(p=>p.id),choose=()=>ids.splice(g.int(0,ids.length-1),1)[0];return g.s.visitors={month:key,huaTuo:choose(),scholar:choose(),critic:choose()};}
export function provinceAdvice(g,p){
 const r=g.ruler(),advisor=r.advisor===null?null:g.officer(r.advisor);if(!advisor||!p.officers.includes(advisor.id))return 'Your advisor must be in this province to give advice.';
 if(!canAdvise(g.s,r,advisor,'general'))return `${advisor.name}: ${ADVICE_UNAVAILABLE}`;
 const month=monthNumber(g.s),key=`${month}:${p.id}`;g.s.adviceReports=Object.fromEntries(Object.entries(g.s.adviceReports||{}).filter(([key])=>key.startsWith(month+':')));if(g.s.adviceReports[key])return g.s.adviceReports[key];
 const accurate=true,men=p.officers.reduce((n,id)=>n+g.officer(id).soldiers,0),enemy=p.neighbors.map(id=>g.province(id)).filter(q=>q.owner!==255&&q.owner!==p.owner&&!r.alliances.includes(q.owner)).sort((a,b)=>a.officers.reduce((n,id)=>n+g.officer(id).soldiers,0)-b.officers.reduce((n,id)=>n+g.officer(id).soldiers,0))[0];
 const available=p.unclaimed.map(id=>g.officer(id)).sort((a,b)=>b.int+b.war+b.charm-a.int-a.war-a.charm)[0];
 let text=!accurate?'I see no immediate opportunity. Strengthen your forces and be cautious.':p.food<men/2?`Our ${men.toLocaleString()} soldiers have only ${p.food.toLocaleString()} food. Buy or send food before going to war.`:available?`${available.name} is available here. Their abilities are INT ${available.int}, WAR ${available.war}, CHA ${available.charm}; consider recruiting them.`:enemy&&enemy.officers.reduce((n,id)=>n+g.officer(id).soldiers,0)<men/3?`${provinceLabel(g,enemy)} has fewer than one third of our soldiers. It is a promising target, provided we take enough food.`:p.loyalty<70?`Popular loyalty is ${p.loyalty}. Give food to the people before imposing another tax.`:p.flood<60?`Flood protection is ${p.flood}. Build dikes to reduce summer losses.`:p.land<80?`Land development is ${p.land}. Cultivation will improve the harvest.`:'Our province is stable. Keep supplies ready and examine neighbouring governors for weaknesses.';
 g.s.adviceReports[key]=`${advisor.name}: ${text}`;return g.s.adviceReports[key];
}
export function provinceRumours(g,p){const v=updateVisitors(g),visitor=v.scholar===p.id?'Sima Hui':v.critic===p.id?'Xu Shao':null;if(!visitor)return 'Neither Sima Hui nor Xu Shao is visiting this province this month.';const candidates=g.s.provinces.flatMap(q=>[...q.hidden,...q.unclaimed].map(id=>({p:q,o:g.officer(id)}))).filter(({o})=>!o.pendingArrival&&!o.dead&&o.name!=='Unnamed').sort((a,b)=>visitor==='Sima Hui'?b.o.int-a.o.int:b.o.war+b.o.charm-a.o.war-a.o.charm);const x=candidates[0];return x?`${visitor}: I have heard of ${x.o.name} in ${provinceLabel(g,x.p)}. ${x.p.hidden.includes(x.o.id)?'Search there for this talent.':'They are available for recruitment.'}`:`${visitor}: I have no news of unclaimed talent today.`;}
export function missionChance(g,p,envoy,target,mode){const me=g.ruler(),hostility=me.relations[target.id]??50;return clamp(mode==='threat'?20+(strength(g,me.id)/Math.max(1,strength(g,target.id))-1)*25+envoy.charm/4:mode==='joint'?45+envoy.charm/3+me.trust/5-hostility/3:mode==='marriage'?25+(envoy.charm+g.officer(me.leader).charm)/4+me.trust/5-hostility/2:25+envoy.charm/2+me.trust/4-hostility/2,5,95);}
export function spyChance(g,envoy,target,mode,second=null,other=null){const me=g.ruler();if(mode==='infiltrate')return 100;if(mode==='rival'){if(!second||!other)return null;return clamp((me.trust+envoy.int+second.int)/3+advisorInt(g,me)/3-(advisorInt(g,target)+advisorInt(g,other))/4,5,95);}const province=g.s.provinces.find(q=>q.officers.includes(target.id));if(!province)return null;const enemy=g.ruler(province.owner);if(['wolf','betrayal'].includes(mode)&&recruitmentProtection(g.s,target,province.owner,me.id))return 0;return clamp((mode==='forged'?envoy.int:envoy.charm)/2+me.trust/4+advisorInt(g,me)/4-target.loyalty/2-(mode==='wolf'?(target.virtue??50)/4:(enemy.trust+target.int)/8),5,95);}

function applyOrder(g,type,args){
 const p=g.owned(args.province),me=g.ruler();let text='';
 if(type==='courtMarriage'){homeOnly(g,p);text=courtMarriage(g,p);}
 else if(['hireArmy','reassignArmy'].includes(type)){
  const officer=g.ready(p,args.officer),hundreds=type==='hireArmy'?g.amount(args.hundreds,hireCapacity(g,p)):0,hired=hundreds*100,total=p.officers.reduce((n,id)=>n+g.officer(id).soldiers,0)+hired,alloc=args.allocations;
  if(!alloc||typeof alloc!=='object'||Array.isArray(alloc)||Object.keys(alloc).length!==p.officers.length||Object.keys(alloc).some(id=>!p.officers.includes(Number(id))))throw Error('Assign men only to the generals serving in this province.');
  const assigned=p.officers.reduce((n,id)=>n+g.amount(alloc[id],10000,0),0),remaining=total-assigned;if(remaining<0)throw Error('The assignments exceed the available men.');if(remaining&&args.disband!==true)throw Error(`Confirm disbanding the ${remaining} remaining men before quitting.`);if(p.population-hired+remaining>3000000)throw Error('The province cannot receive that many disbanded men.');
  const average=total?Math.floor(p.officers.reduce((n,id)=>n+g.officer(id).soldiers*g.officer(id).training,0)/total):0;
  p.gold-=hundreds*10;p.food-=hired;p.population=p.population-hired+remaining;
  for(const id of p.officers){const o=g.officer(id),next=Number(alloc[id]);if(type==='hireArmy'&&next>o.soldiers)o.training=average;o.soldiers=next;}officer.acted=true;text=`${officer.name} ${hired?'hired '+hired.toLocaleString()+' men and ':''}reassigned the army.${remaining?' '+remaining.toLocaleString()+' remaining men were disbanded.':''}`;
 }else if(type==='trainArmy'){
  const officer=g.ready(p,args.officer),men=p.officers.reduce((n,id)=>n+g.officer(id).soldiers,0);if(!men)throw Error('This province has no soldiers to train.');if(p.officers.every(id=>g.officer(id).training===100))throw Error('The army is already fully trained.');const gain=trainingGain(officer,p.officers.map(id=>g.officer(id)));for(const id of p.officers){const o=g.officer(id);o.training=clamp(o.training+gain);}officer.acted=true;text=`${officer.name} trained every army in ${p.name}; training increased by up to ${gain}.`;
 }else if(['rewardGold','rewardHorse','rewardWritings'].includes(type)){
  g.ready(p,p.governor);const target=g.officer(args.officer);if(!p.officers.includes(target.id)||target.id===me.leader)throw Error('Choose a subordinate serving in this province.');const amount=type==='rewardGold'?g.amount(args.amount,Math.min(100,p.gold)):100;
  if(type==='rewardHorse'&&p.horses<1)throw Error('No horse is available.');
  if(type==='rewardWritings'){const advisor=me.advisor===null?null:g.officer(me.advisor);if(!advisor||!p.officers.includes(advisor.id)||target.int+1>=advisor.int)throw Error('An advisor here must have at least two more intelligence points than the recipient.');target.int++;if(!g.s.books.includes(target.id))g.s.books.push(target.id);text=`${target.name} received writings and gained one intelligence point.`;}
  else{if(target.loyalty===100)throw Error('This general is already fully loyal.');const before=target.loyalty;target.loyalty=clamp(before+Math.floor(g.officer(p.governor).charm*(type==='rewardHorse'?100:amount)/400)+g.int(0,1));if(type==='rewardHorse'){p.horses--;}text=`${target.name} received ${type==='rewardHorse'?'a horse':amount+' gold'}. Loyalty ${before} → ${target.loyalty}.`;}
  if(type==='rewardGold')p.gold-=amount;g.officer(p.governor).acted=true;
 }else if(type==='dismiss'){
  homeOnly(g,p);const officer=g.officer(args.officer);if(!p.officers.includes(officer.id)||officer.id===me.leader||p.officers.length<2)throw Error('Dismiss a subordinate and leave an officer to govern.');p.officers=p.officers.filter(id=>id!==officer.id);const destination=g.province(p.neighbors[g.int(0,p.neighbors.length-1)]);destination.hidden.push(officer.id);p.population=Math.min(3000000,p.population+officer.soldiers);officer.soldiers=0;officer.weapons=0;officer.owner=255;officer.acted=true;if(me.advisor===officer.id)me.advisor=null;text=`${officer.name} was dismissed and is now a free general.`;
 }else if(type==='healing'){
  if(updateVisitors(g).huaTuo!==p.id)throw Error('Hua Tuo is not visiting this province this month.');const patients=p.officers.map(id=>g.officer(id)).filter(o=>o.sick||o.injured);if(!patients.length)throw Error('No general here needs healing.');for(const o of patients){o.sick=false;o.injured=false;o.illMonths=0;}text=`Hua Tuo healed ${patients.map(o=>o.name).join(', ')}.`;
 }else if(type==='delegateRealm'){
  homeOnly(g,p);const ruler=g.ready(p,me.leader),target=g.owned(args.target);if(target.officers.includes(me.leader))throw Error('Your ruler’s province remains under direct rule.');if(!['self','direct'].includes(args.mode))throw Error('Choose Self rule or Direct rule.');target.delegate=args.mode==='self'?'domestic':'manual';ruler.acted=true;text=`${target.name} is now under ${args.mode==='self'?'self rule':'direct rule'}.`;
 }else if(type==='selfExile'){
  homeOnly(g,p);const ruler=g.ready(p,me.leader);if(args.confirm!==true)throw Error('Confirm that your ruler will go into exile.');if(typeof args.takeAll!=='boolean')throw Error('Choose whether to take all generals.');
  const partyIds=args.takeAll?[...p.officers]:[ruler.id],gold=p.gold,food=p.food;p.gold=0;p.food=0;
  for(const q of g.s.provinces.filter(q=>q.owner===me.id)){
   for(const id of q.officers){const o=g.officer(id);o.owner=255;o.acted=true;if(!partyIds.includes(id)){q.population=Math.min(3000000,q.population+o.soldiers);o.soldiers=0;o.weapons=0;q.unclaimed.push(id);}}
   q.officers=[];q.owner=255;q.governor=null;q.delegate='manual';
  }
  g.s.roaming??=[];g.s.roaming.push({owner:me.id,province:p.id,officers:partyIds,gold,food});
  me.exiled=true;me.home=p.id;if(!partyIds.includes(me.advisor))me.advisor=null;
  for(const r of g.s.rulers)r.alliances=r.alliances.filter(id=>id!==me.id);me.alliances=[];
  g.s.jointPlans=(g.s.jointPlans||[]).filter(x=>x.ruler!==me.id&&x.ally!==me.id);
  text=`${me.name} went into exile with ${partyIds.length} generals, ${gold} gold and ${food.toLocaleString()} food. Move, View, Settle and Rest remain available.`;
 }else if(type==='diplomaticMission'){
  const mode=args.mode,target=active(g,args.target);if(!target||target.id===me.id)throw Error('Choose another active ruler.');if(mode==='threat'&&(g.s.wars||[]).some(b=>[b.attacker,b.defender].includes(target.id)))throw Error('Resolve this ruler’s ongoing wars before demanding submission.');if(!['alliance','joint','marriage','gift','cancel','threat'].includes(mode))throw Error('Choose a diplomatic mission.');
  if(mode==='cancel'){homeOnly(g,p);if(!me.alliances.includes(target.id))throw Error('Choose a ruler already allied with you.');g.ready(p,p.governor).acted=true;sever(g,me,target);relation(me,target,(me.relations[target.id]??50)+20);text=`The alliance with ${target.name} was cancelled.`;}
  else{
   const envoy=g.ready(p,args.officer);if(['alliance','joint','marriage','threat'].includes(mode))homeOnly(g,p);if(mode==='alliance'&&me.alliances.includes(target.id))throw Error('This ruler is already an ally.');
   let enemy=null,amount=0;if(mode==='joint'){if(!me.alliances.includes(target.id))throw Error('A joint invasion requires an ally.');enemy=g.province(args.enemy);if(enemy.owner===255||[me.id,target.id].includes(enemy.owner)||me.alliances.includes(enemy.owner)||target.alliances.includes(enemy.owner)||!enemy.neighbors.some(id=>g.province(id).owner===me.id)||!enemy.neighbors.some(id=>g.province(id).owner===target.id))throw Error('Choose an enemy province bordering both allied realms.');}
   if(mode==='marriage'){if(g.s.familyMode==='expanded')checkRoyalProposal(g,me,target,args.child);else{if(me.hasDaughter===false)throw Error('You have no daughters.');if(me.daughterGivenTo!==undefined)throw Error('Each ruler can offer one daughter in marriage.');}}if(mode==='gift')amount=g.amount(args.amount,p.gold,100);
   const success=typeof g.missionAnswer==='boolean'?g.missionAnswer:g.random()*100<missionChance(g,p,envoy,target,mode);envoy.acted=true;
   if(mode==='gift'&&success){p.gold-=amount;const capital=g.province(target.home);capital.gold=Math.min(30000,capital.gold+amount);relation(me,target,(me.relations[target.id]??50)-Math.floor(Math.sqrt(amount)*envoy.charm/30));text=`${envoy.name} delivered ${amount} gold to ${target.name}; mutual hostility is ${me.relations[target.id]}.`;}
   else if(!success){relation(me,target,(me.relations[target.id]??50)+(mode==='threat'?20:5));text=`${target.name} refused ${envoy.name}’s ${mode==='joint'?'joint invasion proposal':mode==='marriage'?'marriage proposal':mode==='threat'?'demand to surrender':mode==='gift'?'gift':'alliance proposal'}.`;}
   else if(mode==='alliance'){ally(me,target);pruneJointPlans(g);relation(me,target,Math.min(30,me.relations[target.id]??50));text=`${target.name} accepted an alliance with ${me.name}.`;}
   else if(mode==='joint'&&g.isHuman(target.id)){text=askJointConsent(g,me,target,enemy);}
   else if(mode==='joint'){g.s.jointPlans??=[];g.s.jointPlans=g.s.jointPlans.filter(x=>x.ruler!==me.id||x.enemy!==enemy.id);g.s.jointPlans.push({ruler:me.id,ally:target.id,enemy:enemy.id,expires:monthNumber(g.s)+1});text=`${target.name} agreed to support an invasion of ${enemy.name}. The agreement lasts one month.`;}
   else if(mode==='marriage'){if(g.s.familyMode==='expanded')text=acceptRoyalProposal(g,me,target,args.child)+' Mutual hostility fell.';else{me.daughterGivenTo=target.id;target.daughtersReceived??=[];target.daughtersReceived.push(me.id);text=`${target.name} accepted your daughter’s marriage proposal; mutual hostility fell.`;}relation(me,target,(me.relations[target.id]??50)-30);}
   else{text=surrenderRealm(g,target,envoy);}
  }
 }else if(type==='spyMission'){
  homeOnly(g,p);const mode=args.mode,envoy=g.ready(p,args.officer);if(!['infiltrate','rival','wolf','betrayal','forged'].includes(mode))throw Error('Choose a spy mission.');
  if(mode==='infiltrate'){const target=g.province(args.target);if(target.owner===255||target.owner===me.id||envoy.id===me.leader||envoy.loyalty!==100||p.officers.length<2)throw Error('Infiltration requires a fully loyal subordinate and an enemy province; leave a governor behind.');detach(g,envoy.id);target.unclaimed.push(envoy.id);envoy.owner=255;envoy.spyFor=me.id;envoy.acted=true;text=`${envoy.name} infiltrated ${target.name} as a free general. If recruited, they can undermine the enemy and return to your side in battle.`;}
  else if(mode==='rival'){
   const a=active(g,args.target),b=active(g,args.other),second=g.ready(p,args.second);if(!a||!b||a.id===b.id||[a.id,b.id].includes(me.id)||envoy.id===second.id)throw Error('Choose two rival rulers and two different ready messengers.');const chance=spyChance(g,envoy,a,mode,second,b),success=g.random()*100<chance;envoy.acted=true;second.acted=true;if(success){relation(a,b,(a.relations[b.id]??50)+20);text=`The rival tigers plot succeeded. ${a.name} and ${b.name} have mutual hostility ${a.relations[b.id]}.`;}else{relation(me,a,(me.relations[a.id]??50)+10);relation(me,b,(me.relations[b.id]??50)+10);text='The rival tigers plot was exposed; both rulers became more hostile to you.';}
  }else{
   const target=g.officer(args.target);if((g.s.wars||[]).some(b=>b.units.some(u=>u.id===target.id)))throw Error('This general is committed to an ongoing battle.');const province=g.s.provinces.find(q=>q.officers.includes(target.id));if(!province||province.owner===me.id||province.owner===255||target.id===g.ruler(province.owner).leader)throw Error('Choose a rival’s subordinate general.');const enemy=g.ruler(province.owner);if(mode==='wolf'&&province.governor!==target.id)throw Error('Tiger and wolf targets a rival governor.');if(mode==='wolf'&&g.s.rulers.length===16&&g.s.rulers.every(r=>g.s.provinces.some(q=>q.owner===r.id)))throw Error('No ruler slot is available for a new rebellion.');
   const chance=spyChance(g,envoy,target,mode),success=g.random()*100<chance;envoy.acted=true;
   if(!success)text=`${envoy.name}’s ${mode==='wolf'?'tiger and wolf':mode==='forged'?'forged letter':'betrayal'} mission failed.`;
   else if(mode==='wolf'){if((g.s.wars||[]).some(b=>[b.source,b.target,...b.units.map(u=>u.origin)].includes(province.id)))throw Error('This province has generals committed to an ongoing battle.');target.loyalty=clamp(target.loyalty-20);const report={events:[],details:[]};disaster(g,province,'rebellion',report);text=report.events.join(' ');}
   else{target.loyalty=clamp(target.loyalty-20);if(mode==='betrayal'){target.betrayalFor=me.id;target.betrayalUntil=monthNumber(g.s)+3;text=`${target.name} agreed to betray their ruler during an invasion by your army. The pact lasts three months.`;}else text=`The forged letter lowered ${target.name}’s loyalty to ${target.loyalty}.`;}
  }
 }
 g.normalize();return g.record(`${p.name}: ${text}`,type==='diplomaticMission'?'diplomacy':'order');
}
export function executeProvinceOrder(g,type,args){const before=JSON.parse(JSON.stringify(g.s));try{return applyOrder(g,type,args);}catch(e){g.s=before;throw e;}}
export function validateProvinceOrders(s){
 const owners=new Set(s.rulers.map(r=>r.id));s.jointPlans??=[];if(!Array.isArray(s.jointPlans)||s.jointPlans.length>41||s.jointPlans.some(x=>!owners.has(x.ruler)||!owners.has(x.ally)||x.ruler===x.ally||!s.provinces[x.enemy-1]||!Number.isInteger(x.expires)))throw Error('Invalid joint invasion agreement.');
 for(const x of s.jointPlans)if(x.officers&&(!Array.isArray(x.officers)||!x.officers.length||x.officers.length>5||new Set(x.officers).size!==x.officers.length||x.officers.some(id=>!s.officers[id])||!s.provinces[x.supplyProvince-1]||!Number.isInteger(x.food)||x.food<0||x.food>3000000||!Number.isInteger(x.gold)||x.gold<0||x.gold>30000))throw Error('Invalid pledged allied army.');
 if(s.visitors&&(!Number.isInteger(s.visitors.month)||['huaTuo','scholar','critic'].some(k=>!s.provinces[s.visitors[k]-1])))throw Error('Invalid travelling visitor state.');
 for(const o of s.officers){if(o.serviceSince!==undefined&&(!Number.isInteger(o.serviceSince)||o.serviceSince<1||o.serviceSince>s.year))throw Error('Invalid service record.');for(const k of ['spyFor','betrayalFor'])if(o[k]!==undefined&&!owners.has(o[k]))throw Error('Invalid covert allegiance.');if(o.betrayalUntil!==undefined&&!Number.isInteger(o.betrayalUntil))throw Error('Invalid betrayal duration.');if(o.hasHorse!==undefined&&typeof o.hasHorse!=='boolean')throw Error('Invalid horse reward.');}
 for(const r of s.rulers)if(r.marriedTo!==undefined&&(!owners.has(r.marriedTo)||r.marriedTo===r.id||s.rulers.find(x=>x.id===r.marriedTo).marriedTo!==r.id))throw Error('Invalid marriage agreement.');
 for(const r of s.rulers){if(r.marriedTo!==undefined&&r.daughterGivenTo===undefined){r.daughterGivenTo=r.marriedTo;const other=s.rulers.find(x=>x.id===r.marriedTo);other.daughtersReceived??=[];if(!other.daughtersReceived.includes(r.id))other.daughtersReceived.push(r.id);}}
 for(const r of s.rulers){r.hasDaughter??=true;if(typeof r.hasDaughter!=='boolean')throw Error('Invalid daughter availability.');if(r.daughterGivenTo!==undefined&&(!owners.has(r.daughterGivenTo)||r.daughterGivenTo===r.id||!s.rulers.find(x=>x.id===r.daughterGivenTo).daughtersReceived?.includes(r.id)))throw Error('Invalid daughter marriage.');if(r.daughtersReceived!==undefined&&(!Array.isArray(r.daughtersReceived)||new Set(r.daughtersReceived).size!==r.daughtersReceived.length||r.daughtersReceived.some(id=>s.rulers.find(x=>x.id===id)?.daughterGivenTo!==r.id)))throw Error('Invalid received marriages.');}
 if(s.campaignEnded!==undefined&&typeof s.campaignEnded!=='boolean')throw Error('Invalid exile state.');if(s.adviceReports&&(!Object.values(s.adviceReports).every(v=>typeof v==='string'&&v.length<3000)||Object.keys(s.adviceReports).length>205))throw Error('Invalid advisor reports.');
}

function pruneJointPlans(g){const month=monthNumber(g.s);g.s.jointPlans=(g.s.jointPlans||[]).filter(x=>{const a=active(g,x.ruler),b=active(g,x.ally),enemy=g.province(x.enemy);return x.expires>=month&&a&&b&&a.alliances.includes(b.id)&&![255,a.id,b.id].includes(enemy.owner)&&!a.alliances.includes(enemy.owner)&&!b.alliances.includes(enemy.owner);});}
export function covertUpkeep(g){pruneJointPlans(g);const month=monthNumber(g.s);for(const o of g.s.officers){if(o.betrayalUntil<month){delete o.betrayalFor;delete o.betrayalUntil;}}for(const p of g.s.provinces.filter(q=>q.owner!==255)){for(const id of p.officers){const spy=g.officer(id);if(spy.spyFor!==undefined&&spy.spyFor!==p.owner&&active(g,spy.spyFor)){if(g.random()*100>100-Math.max(0,(100-spy.loyalty)/10)){g.record(`${spy.name} abandoned their covert allegiance and now serves ${g.ruler(p.owner).name}.`,'month');delete spy.spyFor;continue;}for(const other of p.officers){const o=g.officer(other);if(o.id!==g.ruler(p.owner).leader&&o.id!==spy.id)o.loyalty=clamp(o.loyalty-g.int(1,3));}}}}updateVisitors(g);}
