import {hexPoint,reachable,at,TERRAIN,living} from './battle.mjs?v=34';
export function createProvinceWorld(T,canvas,labels,game,terrains,onHex){
 const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;const scene=new T.Scene();scene.background=new T.Color('#91a69e');scene.fog=new T.Fog('#91a69e',35,80);const camera=new T.PerspectiveCamera(42,1,.1,120),target=new T.Vector3(0,0,0);let dist=34,desired=34,running=true,last=0,frames=0,group=new T.Group();scene.add(group);
 scene.add(new T.HemisphereLight('#c9e4ed','#4d553b',2));const sun=new T.DirectionalLight('#ffe3b7',3);sun.position.set(-15,30,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20});scene.add(sun);
 const colors=['#7f8d5c','#466b49','#849068','#8a8779','#487d88','#a6a18a','#aea285'],materials=colors.map(color=>new T.MeshStandardMaterial({color,roughness:color===colors[4]?.35:.95,metalness:color===colors[4]?.2:0})),highlight=new T.MeshBasicMaterial({color:'#e9cb83',transparent:true,opacity:.4});const hex=new T.CylinderGeometry(.98,.98,.45,6);hex.rotateY(Math.PI/6);const rings=new T.RingGeometry(.78,.9,6);rings.rotateX(-Math.PI/2);rings.rotateY(Math.PI/6);const timber=new T.MeshStandardMaterial({color:'#654d38'}),leaf=new T.MeshStandardMaterial({color:'#31513d'}),roof=new T.MeshStandardMaterial({color:'#3c5053'}),rock=new T.MeshStandardMaterial({color:'#7c7d70',roughness:1});
 const textNodes=[];let current=[],meshes=[];const staticMaterials=new Set([...materials,highlight,timber,leaf,roof,rock]);
 const add=(geo,mat,x,y,z,sx=1,sy=1,sz=1)=>{const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;};
 function disposeGroup(){scene.remove(group);group.traverse(o=>{if(o.geometry&&!['tile','ring'].includes(o.userData.shared))o.geometry.dispose();if(o.material&&!staticMaterials.has(o.material))o.material.dispose();});group=new T.Group();scene.add(group);labels.replaceChildren();textNodes.length=0;meshes=[];}
 function compact(){const bins=new Map();for(const m of [...group.children]){if(!m.isMesh)continue;m.updateMatrix();m.updateMatrixWorld(true);const mat=m.material,key=[mat.type,mat.color.getHexString(),mat.roughness,mat.metalness,mat.opacity,mat.side].join(':');let bin=bins.get(key);if(!bin){bin={mat,vertices:[],normals:[],indices:[],offset:0};bins.set(key,bin);}const g=m.geometry.clone().applyMatrix4(m.matrix);bin.vertices.push(...g.attributes.position.array);bin.normals.push(...g.attributes.normal.array);if(g.index)for(const i of g.index.array)bin.indices.push(i+bin.offset);else for(let i=0;i<g.attributes.position.count;i++)bin.indices.push(i+bin.offset);bin.offset+=g.attributes.position.count;g.dispose();group.remove(m);if(!m.userData.shared)m.geometry.dispose();if(mat!==bin.mat&&!staticMaterials.has(mat))mat.dispose();}
 for(const b of bins.values()){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(b.vertices,3));g.setAttribute('normal',new T.Float32BufferAttribute(b.normals,3));g.setIndex(b.indices);const m=new T.Mesh(g,b.mat);m.castShadow=true;m.receiveShadow=true;group.add(m);}}
 function update(){disposeGroup();const b=game.s.battle,p=game.province(b?b.target:game.s.selected),tiles=b?.terrain||terrains[p.id-1],selected=b?.units.find(u=>u.id===b.selected),reach=b&&selected&&selected.side===b.side&&selected.ap?reachable(b,selected):[];current=tiles;
 for(let r=0;r<12;r++)for(let q=0;q<13;q++){const type=tiles[r*13+q];if(!materials[type])continue;const {x,z}=hexPoint(q,r),h=type===4?-.12:type===2?.3:type===3?.5:0;const tile=add(hex,materials[type],x,h-.22,z);tile.userData={q,r,shared:'tile'};meshes.push(tile);
 if(type===1)for(let i=0;i<3;i++){const dx=Math.sin(q*7+r*3+i)*.42,dz=Math.cos(q*3+r*8+i)*.42;add(new T.CylinderGeometry(.05,.08,.7,5),timber,x+dx,h+.3,z+dz);add(new T.ConeGeometry(.3,.85,7),leaf,x+dx,h+.8,z+dz);}
 if(type===2||type===3){add(new T.IcosahedronGeometry(.62,1),rock,x,h+.2,z,1,type===3?1.6:1,.9);}
 if(type===5||type===6){for(const [dx,dz,sx,sz]of [[0,-.62,1.4,.15],[0,.62,1.4,.15],[-.62,0,.15,1.4],[.62,0,.15,1.4]])add(new T.BoxGeometry(1,1,1),materials[type],x+dx,.28,z+dz,sx,.6,sz);add(new T.BoxGeometry(.6,.55,.5),materials[6],x,.3,z);add(new T.ConeGeometry(.52,.3,4),roof,x,.7,z,1,1,1);}
 if(reach.some(v=>v.q===q&&v.r===r)){const ring=add(rings,highlight,x,h+.04,z);ring.userData.shared='ring';}
 if(b?.fire[r*13+q]){const flame=add(new T.ConeGeometry(.45,1.8,7),new T.MeshBasicMaterial({color:'#e98738',transparent:true,opacity:.8}),x,.9,z);flame.userData.flame=true;}
 }
 const units=b?living(b):p.officers.filter(id=>game.officer(id).soldiers>0).slice(0,10).map((id,i)=>({id,side:'defend',soldiers:game.officer(id).soldiers,q:Math.min(12,4+i%5),r:Math.min(11,4+Math.floor(i/5)),ap:0}));
 for(const u of units){const {x,z}=hexPoint(u.q,u.r),mat=new T.MeshStandardMaterial({color:u.side==='attack'?'#b75243':'#476e92'});for(let i=0;i<4;i++){const dx=(i%2-.5)*.35,dz=(Math.floor(i/2)-.5)*.35;add(new T.CylinderGeometry(.07,.11,.3,6),mat,x+dx,.4,z+dz);add(new T.SphereGeometry(.08,6,4),materials[6],x+dx,.63,z+dz);}add(new T.CylinderGeometry(.025,.025,1.4,5),timber,x+.3,.7,z);add(new T.PlaneGeometry(.6,.35),new T.MeshStandardMaterial({color:u.id===b?.selected?'#f1d295':u.side==='attack'?'#a53e32':'#375979',side:T.DoubleSide}),x+.55,1.25,z);
 const node=document.createElement('button');node.className='unit-label'+(u.id===b?.selected?' selected':'');node.textContent=`${game.officer(u.id).name} · ${u.soldiers.toLocaleString()}`;node.setAttribute('aria-label',`Unit ${game.officer(u.id).name}, ${u.soldiers} soldiers, hex ${u.q+1}, ${u.r+1}`);node.onclick=()=>onHex(u.q,u.r);labels.append(node);textNodes.push({node,x,z,y:1.7});}
 compact();
 }
 const ray=new T.Raycaster(),mouse=new T.Vector2();let pointer=null,drag=false,pointers=new Map(),pinch=0;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointer={x:e.clientX,y:e.clientY};drag=false;pointers.set(e.pointerId,pointer);});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){drag=true;const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch)desired=T.MathUtils.clamp(desired*pinch/d,16,52);pinch=d;}else if(pointer&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>6){drag=true;target.x-= (e.clientX-old.x)*dist/canvas.clientHeight*.55;target.z-=(e.clientY-old.y)*dist/canvas.clientHeight*.8;}});canvas.addEventListener('pointerup',e=>{if(!drag){const rect=canvas.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes)[0];if(hit)onHex(hit.object.userData.q,hit.object.userData.r);}pointers.delete(e.pointerId);pointer=null;pinch=0;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);pointer=null;pinch=0;});canvas.addEventListener('wheel',e=>{e.preventDefault();desired=T.MathUtils.clamp(desired*(e.deltaY>0?1.1:.9),16,52);},{passive:false});
 const resize=()=>{const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix();},observer=new ResizeObserver(resize);observer.observe(canvas.parentElement);function frame(time){if(!running)return;requestAnimationFrame(frame);if(document.hidden||time-last<32)return;last=time;dist=T.MathUtils.lerp(dist,desired,.15);camera.position.set(target.x,target.y+dist*.8,target.z+dist*.65);camera.lookAt(target);renderer.render(scene,camera);frames++;for(const t of textNodes){const v=new T.Vector3(t.x,t.y,t.z).project(camera);t.node.style.left=(v.x*.5+.5)*canvas.clientWidth+'px';t.node.style.top=(-v.y*.5+.5)*canvas.clientHeight+'px';t.node.style.display=v.z<1?'block':'none';}}
 const setQuality=v=>{renderer.setPixelRatio(Math.min(devicePixelRatio,v==='high'?2:v==='low'?1:1.5));renderer.shadowMap.enabled=v!=='low';resize();};update();setQuality(game.s.settings.quality);requestAnimationFrame(frame);
 return {update,focus(){update();},overview(){target.set(0,0,0);desired=34;},zoom(n){desired=T.MathUtils.clamp(desired*n,16,52);},setQuality,get stats(){return {drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,frames,threeRevision:T.REVISION};},destroy(){running=false;observer.disconnect();scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});renderer.dispose();labels.replaceChildren();}};
}
