import {moveForecast,moveTeamInsight} from './move-forecast.mjs?v=29';
import {provinceChoice,provinceLabel} from './province-choice.mjs?v=29';
import {orderUnavailable} from './order-availability.mjs?v=29';
import {adviceTopic} from './advice-topics.mjs?v=29';
import {orderInsight,generalStats} from './game-ui.mjs?v=29';
import {readyOfficers,rulerPresent,hireCapacity,provinceAdvice,provinceRumours,updateVisitors} from './province-rules.mjs?v=29';
import {eligibleRoyalChildren,childAge} from './ruler-family.mjs?v=29';
export function createProvinceCommands(c){
 const $=id=>document.getElementById(id),g=()=>c.getGame(),p=()=>c.getSelected(),me=()=>g().ruler(),e=c.esc,n=c.num;
 let allocation=null;
 const officers=(ids)=>ids.map(id=>[id,c.name(g().officer(id)),{officer:id}]);
 const ready=()=>officers(readyOfficers(g(),p()).map(o=>o.id));
 const active=()=>g().s.rulers.filter(r=>r.id!==me().id&&g().s.provinces.some(q=>q.owner===r.id));
 const rulers=(list=active())=>list.map(r=>[r.id,c.name(r)]);
 const enemyOfficers=governors=>g().s.provinces.filter(q=>![255,me().id].includes(q.owner)).flatMap(q=>(governors?[q.governor]:q.officers).filter(id=>id!==g().ruler(q.owner).leader).map(id=>[id,`${c.name(g().officer(id))} · ${provinceLabel(g(),q)}`,{officer:id}]));
 const select=(key,label,choices)=>({key,label,choices});
 const amount=(key,label,min,max,value)=>({key,label,min,max,value});
 const yes=(label)=>select('confirm',label,[[1,'Yes'],[0,'No']]);
 function info(title,text){c.dialog(title,`<p class="dialog-intro">${e(text)}</p>`,`<button id="adviceClose">Close</button>`,'PROVINCE ORDERS');$('adviceClose').onclick=c.close;c.refresh();}
 function menu(title,items,intro=''){
  const scope=({Milit:'military',Person:'personnel',Diplom:'diplomacy',Spy:'spy',Advice:'advice',Reward:'reward',Merch:'trade'})[title];
  const reason=id=>scope?orderUnavailable(g(),p(),scope+':'+id):null;
  c.dialog(title,`${intro?`<p class="dialog-intro">${e(intro)}</p>`:''}<div class="suborder-grid">${items.map(([id,label,fn,invalid])=>`<button data-suborder="${id}" class="${invalid||reason(id)?'order-unavailable':''}">${e(label)}</button>`).join('')}</div>`,`<button id="cancelOrder">Close</button>`,'PROVINCE ORDERS');
  $('cancelOrder').onclick=c.close;items.forEach(([id,label,fn])=>{$('dialogBody').querySelector(`[data-suborder="${id}"]`).onclick=()=>{const why=reason(id);if(why){info(label,why);return;}fn();};});
 }
 function perform(type,args){const message=g().execute(type,{province:p().id,...args});allocation=null;c.close();c.refresh();c.toast(message);if(g().s.campaignEnded)info('The ruler has gone into exile','Your realm has dissolved. Return to launch from Menu to begin or load another campaign.');}
 function flow(title,steps,action,seed={}){
  let index=0,data={...seed};
  function draw(){const s=steps[index],choices=typeof s.choices==='function'?s.choices(data):s.choices,min=typeof s.min==='function'?s.min(data):s.min,max=typeof s.max==='function'?s.max(data):s.max,empty=choices?choices.length===0:max<min;
   const value=data[s.key]??s.value??(choices?.[0]?.[0]??min);
   const forecast=title==='Move'&&data.officers?moveForecast(g(),p(),g().province(data.target),data.officers):null;
   c.dialog(title,`<p class="step-caption">${index+1} / ${steps.length}</p><div class="field" data-step="${s.key}"><label for="orderValue">${e(typeof s.label==='function'?s.label(data):s.label)}</label>${choices?`<select id="orderValue" data-purpose="${e(title)}">${choices.map(([id,label,meta])=>`<option ${meta?.officer!==undefined?`data-officer="${meta.officer}"`:""} ${meta?.province!==undefined?`data-province="${meta.province}"`:""} value="${e(id)}" ${String(value)===String(id)?'selected':''}>${e(label)}</option>`).join('')}</select>`:`<input id="orderValue" type="range" min="${min}" max="${max}" step="1" value="${Math.min(max,Math.max(min,Number(value)))}"><small>Range: ${n(min)} – ${n(Math.max(min,max))}</small>`}</div>${empty?'<p class="form-error">No eligible choice is available for this order.</p>':''}${forecast?`<aside class="advisor-insight" id="moveForecast"><strong>Supply estimate · #${data.target}</strong><span>Next payroll: ${n(forecast.payroll)} gold; ${n(forecast.goldNeeded)} additional gold needed after existing stores.</span><span>To next July harvest: ${forecast.months} monthly payments × ${n(forecast.monthlyFood)} food = ${n(forecast.food)}; ${n(forecast.foodNeeded)} additional food needed. Events, casualties and later orders can change these estimates.</span></aside>`:''}<div id="selectionAdvice"></div><p id="orderError" class="form-error" role="alert"></p>`,`<button id="cancelOrder">Cancel</button>${index?'<button id="orderBack">Back</button>':''}<button id="confirmOrder" class="gold-button" ${empty?'disabled':''}>${index===steps.length-1?'Confirm order':'Next'}</button>`,'PROVINCE ORDERS');
   const advice=()=>{const id=['officer','governor'].includes(s.key)?Number($('orderValue').value):data.officer??(/Tax|Deleg/i.test(title)?p().governor:undefined);$('selectionAdvice').innerHTML=id===undefined?'':orderInsight(g(),s.key==='governor'?'Appoint governor':title,id,{...data,[s.key]:$('orderValue').value});};$('orderValue').onchange=advice;$('orderValue').oninput=advice;advice();$('cancelOrder').onclick=c.close;if(index)$('orderBack').onclick=()=>{data[s.key]=$('orderValue').value;index--;draw();};
   $('confirmOrder').onclick=()=>{try{const v=$('orderValue').value;if(choices){if(!choices.some(([id])=>String(id)===v))throw Error('Choose an available option.');data[s.key]=v;}else{const vNum=Number(v);if(!Number.isSafeInteger(vNum)||vNum<min||vNum>max)throw Error(`Choose a whole number from ${min} to ${max}.`);data[s.key]=vNum;}if(index<steps.length-1){index++;draw();}else action(data);}catch(error){$('orderError').textContent=error.message;}};
  }draw();
 }
 function actorFlow(title,type,steps=[],seed={}){flow(title,[select('officer','Who will carry out this order?',ready),...steps],d=>perform(type,d),seed);}
 function beginAllocation(type,data){const q=p();allocation={type,province:q.id,officer:Number(data.officer),hundreds:Number(data.hundreds||0),allocations:Object.fromEntries(q.officers.map(id=>[id,g().officer(id).soldiers])),remaining:Number(data.hundreds||0)*100};drawAllocation();}
 function drawAllocation(){const a=allocation,q=g().province(a.province);c.dialog('Reassign men',`<p class="dialog-intro">Reduce an assignment to return men to the pool, then assign them to another general. Each army holds at most 10,000 men.</p><p class="allocation-total">Remaining men: <strong id="remainingMen">${n(a.remaining)}</strong></p><div class="field"><label for="allocationOfficer">Change whom?</label><select id="allocationOfficer">${q.officers.map(id=>`<option value="${id}">${e(c.name(g().officer(id)))} · ${n(a.allocations[id])} men</option>`).join('')}</select></div><div class="field"><label for="allocationMen">Assign how many men?</label><input id="allocationMen" type="range" min="0" step="1"><small id="allocationMax"></small></div><button id="applyAllocation">Assign men</button><p id="orderError" class="form-error" role="alert"></p>`,`<button id="finishAllocation" class="gold-button">Finish reassignment</button>`,'MILIT · REASSIGN');
  const update=()=>{const id=Number($('allocationOfficer').value),max=Math.min(10000,a.remaining+a.allocations[id]);$('allocationMen').max=max;$('allocationMen').value=a.allocations[id];$('allocationMax').textContent=`Range: 0 – ${n(max)}`;};$('allocationOfficer').onchange=update;update();
  $('applyAllocation').onclick=()=>{try{const id=Number($('allocationOfficer').value),men=g().amount($('allocationMen').value,Math.min(10000,a.remaining+a.allocations[id]),0);a.remaining+=a.allocations[id]-men;a.allocations[id]=men;drawAllocation();$('allocationOfficer').value=id;update();}catch(error){$('orderError').textContent=error.message;}};$('finishAllocation').onclick=finishAllocation;
 }
 function commitAllocation(disband){try{const a=allocation,old=p().id;if(old!==a.province)throw Error('Return to the original province before finishing reassignment.');perform(a.type,{...a,disband});}catch(error){if($('orderError'))$('orderError').textContent=error.message;else c.toast(error.message);}}
 function finishAllocation(){if(!allocation)return false;if(!allocation.remaining){commitAllocation(false);return true;}c.dialog('Disband remaining soldiers?',`<p class="dialog-intro">${n(allocation.remaining)} men remain unassigned. Quitting will disband them and return them to the province population.</p><p id="orderError" class="form-error" role="alert"></p>`,`<button id="returnAllocation">Keep reassigning</button><button id="confirmDisband" class="gold-button">Confirm disbanding</button>`,'MILIT · CONFIRM');$('returnAllocation').onclick=drawAllocation;$('confirmDisband').onclick=()=>commitAllocation(true);return true;}
 function military(){menu('Milit',[['hire','Hire',()=>flow('Hire men',[select('officer','Who will hire men?',ready),amount('hundreds','Hire how many hundreds of men?',1,()=>hireCapacity(g(),p())),yes(d=>`Confirm ${g().officer(d.officer).name} hiring ${n(Number(d.hundreds)*100)} men for ${n(Number(d.hundreds)*10)} gold and ${n(Number(d.hundreds)*100)} food, then assign them?`)],d=>{if(Number(d.confirm))beginAllocation('hireArmy',d);else c.close();})],['reassign','Reassign',()=>flow('Reassign',[select('officer','Who will reassign the men?',ready)],d=>beginAllocation('reassignArmy',d))],['train','Train',()=>actorFlow('Train all armies','trainArmy')],['fort','Build fort',()=>c.buildFort()]]);}
 function recruit(){const targets=()=>g().s.provinces.flatMap(q=>[...q.unclaimed,...(q.owner!==255&&q.owner!==me().id?q.officers.filter(id=>id!==g().ruler(q.owner).leader):[])].map(id=>[id,c.name(g().officer(id))+' · '+provinceLabel(g(),q),{officer:id}])).filter(([id])=>!g().officer(id).dead&&g().officer(id).prisonerOf===undefined);flow('Recruit',[select('target','Recruit whom?',targets),select('method','Offer which invitation?',[['attention','Special attention'],['horse','Horse'],['gold','Gold'],['letter','Letter']]),select('officer','Send whom?',ready)],d=>{if(d.method==='gold')flow('Recruit · Gold',[amount('amount','Offer how much gold?',100,()=>p().gold)],x=>perform('recruitMethod',{...d,...x}),d);else perform('recruitMethod',d);});}
 function appointment(role){if(!rulerPresent(g(),p())){info('Appoint','Only the ruler may appoint officers.');return;}flow('Appoint '+role,[select('target','Appoint in which province?',()=>g().s.provinces.filter(q=>q.owner===me().id).map(q=>provinceChoice(g(),q))),select('officer','Appoint whom?',d=>officers(g().province(d.target).officers.filter(id=>role==='governor'?(!g().province(d.target).officers.includes(me().leader)||id===me().leader):id!==me().leader&&g().officer(id).int>=80))),yes(d=>`Confirm ${g().officer(d.officer).name} as ${role} of #${d.target} · ${g().province(d.target).name}?`)],d=>{if(!Number(d.confirm)){c.close();return;}perform('appointRealm',{...d,role});if(role==='governor')c.showProvince(Number(d.target));});}
 function dismiss(){if(!rulerPresent(g(),p())){info('Dismiss','Only the ruler may dismiss or demote officers.');return;}menu('Dismiss',[['officer','Dismiss general',()=>flow('Dismiss general',[select('officer','Dismiss whom?',()=>officers(p().officers.filter(id=>id!==me().leader))),yes('Dismiss this general and disband their soldiers?')],d=>{if(Number(d.confirm))perform('dismiss',d);else c.close();})],['advisor','Demote advisor',()=>flow('Demote advisor',[yes('Demote the advisor and retain them as a general?')],d=>{if(Number(d.confirm))perform('demoteAdvisor',{});else c.close();}),me().advisor===null]]);}
 function person(){menu('Person',[['recruit','Recruit',recruit],['search','Search',()=>actorFlow('Search for talent','search')],['appoint','Appoint',()=>menu('Appoint',[['governor','Governor',()=>appointment('governor')],['advisor','Advisor',()=>appointment('advisor')]])],['dismiss','Dismiss',dismiss]]);}
 function moving(seed={}){flow('Move',[select('target','Move where?',()=>p().neighbors.map(i=>g().province(i)).filter(q=>[255,me().id].includes(q.owner)&&!g().s.wars.some(b=>b.target===q.id)).map(q=>provinceChoice(g(),q)))],d=>{
  const choices=readyOfficers(g(),p()),ids=new Set(seed.officer===undefined?[]:[seed.officer]);
  c.dialog('Move whom?',`<p class="dialog-intro">Select one or more generals. Leaving nobody behind abandons this province.</p><div class="suborder-grid">${choices.map(o=>`<button data-moving="${o.id}" aria-pressed="${ids.has(o.id)}">${c.portraitMarkup(o,'portrait-mini')}<strong>${e(c.name(o))}</strong><span class="general-stats">${generalStats(o,'move')}</span></button>`).join('')}</div><div id="moveTeamAdvice"></div><p id="orderError" class="form-error"></p>`,'<button id="cancelOrder">Cancel</button><button id="moveSelected" class="gold-button">Next</button>','MOVE');$('cancelOrder').onclick=c.close;
  const adviseTeam=()=>{$('moveTeamAdvice').innerHTML=moveTeamInsight(g(),p(),g().province(d.target),[...ids]);};adviseTeam();
  $('dialogBody').querySelectorAll('[data-moving]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.moving);if(ids.has(id))ids.delete(id);else ids.add(id);b.setAttribute('aria-pressed',String(ids.has(id)));adviseTeam();});
  $('moveSelected').onclick=()=>{if(!ids.size){$('orderError').textContent='Choose at least one general.';return;}const remaining=p().officers.filter(id=>!ids.has(id)),steps=[amount('gold','Take how much gold?',0,()=>p().gold,0),amount('food','Take how much food?',0,()=>p().food,0)];if(!remaining.length)steps.push(yes('Abandon this province?'));else if(ids.has(p().governor))steps.push(select('governor','Who will remain as governor?',()=>officers(remaining)));if(remaining.length)steps.push(yes(x=>`Move ${[...ids].map(id=>g().officer(id).name).join(', ')} to #${d.target} · ${g().province(d.target).name} with ${n(x.gold)} gold and ${n(x.food)} food?`));flow('Move',steps,x=>{if(!Number(x.confirm)){c.close();return;}perform('moveParty',{...d,...x,officers:[...ids],abandon:!remaining.length});},{...d,officers:[...ids]});};
 });}
 function diplomatic(mode){const titles={alliance:'Ally with whom?',joint:'Plan a joint invasion with whom?',marriage:'Offer your daughter to whom?',gift:'Offer gold to whom?',cancel:'Cancel alliance with which ruler?',threat:'Threaten whom?'};
  const expanded=g().s.familyMode==='expanded';
  if(mode==='marriage'&&!expanded&&(me().hasDaughter===false||me().daughterGivenTo!==undefined)){info('Marriage',me().hasDaughter===false?'You have no daughters.':'Your daughter is already married to '+g().ruler(me().daughterGivenTo).name+'.');return;}
  if(mode==='marriage'&&expanded&&!eligibleRoyalChildren(g().s,me()).length){info('Royal marriage','No unmarried child is 16 yet. View Royal Family for ages. Your ruler can marry a court consort independently.');return;}
  const steps=[select('target',mode==='marriage'&&expanded?'Offer a royal child to which unmarried ruler?':titles[mode],()=>rulers(active().filter(r=>['joint','cancel'].includes(mode)?me().alliances.includes(r.id):mode==='alliance'?!me().alliances.includes(r.id):mode==='marriage'?expanded?!r.family?.spouse&&g().s.year-g().officer(r.leader).birth+1>=16&&eligibleRoyalChildren(g().s,me(),r).length:me().hasDaughter!==false&&me().daughterGivenTo===undefined:true)))];
  if(mode==='marriage'&&expanded)steps.push(select('child','Offer which child?',d=>eligibleRoyalChildren(g().s,me(),g().ruler(Number(d.target))).map(child=>[child.id,`${child.name} · Age ${childAge(g().s,child)}`])));
  if(mode==='joint')steps.push(select('enemy','Invade which province?',d=>g().s.provinces.filter(q=>![255,me().id,Number(d.target)].includes(q.owner)&&!me().alliances.includes(q.owner)&&!g().ruler(Number(d.target)).alliances.includes(q.owner)&&q.neighbors.some(id=>g().province(id).owner===me().id)&&q.neighbors.some(id=>g().province(id).owner===Number(d.target))).map(q=>provinceChoice(g(),q))));
  if(mode!=='cancel')steps.push(select('officer','Send whom as messenger?',ready));
  if(mode==='gift')steps.push(amount('amount','Offer how much gold?',100,()=>p().gold));
  if(mode==='cancel')steps.push(yes('Cancel this alliance and its joint invasion plans?'));
  flow('Diplom · '+({alliance:'Alliance',joint:'Joint invasion',marriage:'Marriage',gift:'Gift',cancel:'Cancel alliance',threat:'Threaten'})[mode],steps,d=>{if(mode==='cancel'&&!Number(d.confirm)){c.close();return;}perform('diplomaticMission',{...d,mode});});
 }
 function diplomacy(){const items=['alliance','joint','marriage','gift','cancel','threat'].map((id,i)=>[id,['Alliance','Joint invasion',g().s.familyMode==='expanded'?'Royal marriage':'Marriage','Gift','Cancel alliance','Threaten'][i],()=>diplomatic(id),['alliance','joint','marriage','cancel','threat'].includes(id)&&!rulerPresent(g(),p())]);if(g().s.familyMode==='expanded')items.push(['court','Court marriage',()=>{try{g().ready(p(),me().leader);if(me().family?.spouse)throw Error('Your ruler is already married.');flow('Court marriage',[yes('Marry a court consort? Costs 100 gold and the ruler’s monthly action.')],d=>{if(Number(d.confirm))perform('courtMarriage',{});else c.close();});}catch(error){info('Court marriage',error.message);}},!rulerPresent(g(),p())]);items.push(['family','Royal Family',()=>c.showFamily(me().id)]);menu('Diplom',items);}
 function spy(mode){const steps=[];
  if(mode==='infiltrate'){steps.push(select('target','Infiltrate which province?',()=>g().s.provinces.filter(q=>![255,me().id].includes(q.owner)).map(q=>provinceChoice(g(),q))),select('officer','Send whom? (Loyalty 100)',()=>officers(readyOfficers(g(),p()).filter(o=>o.id!==me().leader&&o.loyalty===100).map(o=>o.id))));}
  else if(mode==='rival')steps.push(select('target','First rival ruler',()=>rulers()),select('other','Second rival ruler',d=>rulers(active().filter(r=>r.id!==Number(d.target)))),select('officer','Messenger to the first ruler',ready),select('second','Different messenger to the second ruler',d=>ready().filter(([id])=>id!==Number(d.officer))));
  else steps.push(select('target',mode==='wolf'?'Incite which governor?':'Target which general?',()=>enemyOfficers(mode==='wolf')),select('officer','Send whom as messenger?',ready));
  flow('Spy · '+({infiltrate:'Infiltrate',rival:'Rival tigers',wolf:'Tiger and wolf',betrayal:'Betrayal',forged:'Forged letter'})[mode],steps,d=>perform('spyMission',{...d,mode}));
 }
 function spyStatus(mode){flow('Spy · '+mode,[select('officer','Which deployed spy?',()=>officers(g().s.officers.filter(o=>o.spyFor===me().id&&!o.dead&&o.prisonerOf===undefined).map(o=>o.id)))],d=>perform('spyControl',{...d,mode}));}
 function spies(){if(!rulerPresent(g(),p())){info('Spy','Issue spy orders in the province where your ruler is staying.');return;}menu('Spy',['infiltrate','rival','wolf','betrayal','forged','verify','withdraw'].map((id,i)=>[id,['Hide / Infiltrate','Rival tigers','Tiger and wolf','Betrayal','Forged letter','Verify','Withdraw'][i],()=>['verify','withdraw'].includes(id)?spyStatus(id):spy(id)]));}
 function advice(){const v=updateVisitors(g());menu('Advice',[['advice','Advice',()=>menu('Advice topics',[['general','General',()=>info('Advice',provinceAdvice(g(),p()))],...['war','officers','spy','visitors'].map(topic=>[topic,topic[0].toUpperCase()+topic.slice(1),()=>info('Advice',adviceTopic(g(),p(),topic))])])],['rumours','Rumours',()=>info('Rumours',provinceRumours(g(),p()))],['healing','Healing',()=>flow('Healing',[yes('Ask Hua Tuo to heal all sick and injured generals here?')],d=>{if(Number(d.confirm))perform('healing',{});else c.close();}),v.huaTuo!==p().id||!p().officers.some(id=>g().officer(id).sick||g().officer(id).injured)]],`Visiting this month: ${[v.huaTuo===p().id?'Hua Tuo':null,v.scholar===p().id?'Sima Hui':null,v.critic===p().id?'Xu Shao':null].filter(Boolean).join(', ')||'no special visitors'}. Advice requires your advisor here; rumours need Sima Hui or Xu Shao; healing needs Hua Tuo and a sick or injured general.`);c.refresh();}
 function reward(kind){const steps=[];if(kind==='Gold')steps.push(amount('amount','Allocate how much gold?',1,()=>Math.min(100,p().gold)));steps.push(select('officer','Reward whom?',()=>officers(p().officers.filter(id=>id!==me().leader&&(kind==='Writings'?g().officer(id).int+1<(me().advisor===null?0:g().officer(me().advisor).int):g().officer(id).loyalty<100)))),yes(d=>kind==='Writings'?`Confirm adviser-led study for ${g().officer(d.officer).name}? No gold or inventory book is required.`:kind==='Horse'?`Confirm giving one horse to ${g().officer(d.officer).name}? No gold is required.`:`Confirm ${d.amount} gold for ${g().officer(d.officer).name}?`));flow('Reward · '+kind,steps,d=>{if(Number(d.confirm))perform({Gold:'rewardGold',Horse:'rewardHorse',Writings:'rewardWritings'}[kind],d);else c.close();});}
 function trade(mode){const steps=[select('officer',mode==='arms'?'Who will buy weapons?':'Who will trade?',ready)];if(mode==='arms')steps.push(select('recipient','Equip which general?',()=>officers(p().officers)));
 const max=d=>mode==='sell'?Math.min(p().food,(30000-p().gold)*p().ricePrice):mode==='buy'?Math.min(p().gold*p().ricePrice-1,3000000-p().food):mode==='horse'?Math.min(Math.floor(p().gold/100),100-p().horses):Math.min(p().gold,Math.floor((10000-g().officer(d.recipient??d.officer).weapons)/100));
 steps.push(amount('amount',mode==='arms'?'Buy how many hundreds of weapons?':mode==='horse'?'Buy how many horses?':mode==='buy'?'Buy how much food?':'Sell how much food?',mode==='sell'?()=>p().ricePrice:1,max));flow('Merch',steps,d=>perform('trade',{...d,mode}),{mode});}
 const role=(o,q)=>o.id===g().ruler(q.owner)?.leader?'Ruler':o.id===q.governor?'Governor':o.id===g().ruler(q.owner)?.advisor?'Advisor':q.unclaimed.includes(o.id)?'Free':'General';
 function table(title,headers,rows){c.dialog(title,`<div class="table-scroll"><table class="province-table"><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${e(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`,`<button id="viewBack">View menu</button><button id="cancelOrder">Close</button>`,'VIEW');$('viewBack').onclick=views;$('cancelOrder').onclick=c.close;}
 function generals(){const q=p(),ids=[...q.officers,...q.unclaimed];c.dialog('Generals',ids.map(id=>{const o=g().officer(id);return `<button class="officer-card list-row" data-view-officer="${id}">${c.portraitMarkup(o,'portrait-mini')}<span><strong>${e(c.name(o))}</strong><small>${role(o,q)} · INT ${o.int} · WAR ${o.war} · CHA ${o.charm}</small></span></button>`;}).join(''),`<button id="viewBack">View menu</button>`,'VIEW');$('viewBack').onclick=views;$('dialogBody').querySelectorAll('[data-view-officer]').forEach(b=>b.onclick=()=>c.showOfficer(Number(b.dataset.viewOfficer)));}
 function summary(which){const q=p(),list=[...q.officers,...q.unclaimed].map(id=>g().officer(id));table('Summary '+which,which===1?['General','Rank','Loy','INT','WAR','CHA']:['General','Rank','Service years','Train','Arms %','Weapons','Men'],list.map(o=>which===1?[c.name(o),role(o,q),o.owner===255?'—':o.loyalty,o.int,o.war,o.charm]:[c.name(o),role(o,q),o.owner===255?'—':Math.max(1,g().s.year-(o.serviceSince??g().s.year)+1),o.training,Math.min(100,Math.floor(o.weapons/Math.max(1,o.soldiers)*100)),n(o.weapons),n(o.soldiers)]));}
 function territory(){table('Territory',['Province','Ruler','Governor','Gold','Food','Pop','Loy','Generals','Rule'],g().s.provinces.filter(q=>q.owner===me().id).map(q=>['#'+q.id+' · '+q.name,c.name(me()),q.governor===null?'—':c.name(g().officer(q.governor)),n(q.gold),n(q.food),n(q.population),q.loyalty,q.officers.length,q.delegate==='manual'?'Direct':'Self *']));}
 function views(){menu('View',[['other','Other provinces',()=>flow('Other provinces',[select('target','View which province?',()=>g().s.provinces.filter(q=>q.id!==p().id).map(q=>provinceChoice(g(),q)))],d=>{if(g().province(d.target).owner===me().id){c.close();c.showProvince(Number(d.target));}else flow('View · Scout',[select('officer','Who will scout?',ready)],x=>{g().record(`${g().officer(x.officer).name} surveyed Province ${d.target}.`);c.close();c.showProvince(Number(d.target));});})],['generals','Generals',generals],['summary1','Summary 1',()=>summary(1)],['summary2','Summary 2',()=>summary(2)],['territory','Territory',territory],['data','Data order',()=>flow('Data order',[select('sort','Order generals by which attribute?',[['int','INT'],['war','WAR'],['charm','CHA'],['loyalty','Loy'],['training','Train'],['soldiers','Men']])],d=>{const q=p(),priority=id=>id===g().ruler(q.owner)?.leader?2:id===q.governor?1:0;q.officers.sort((a,b)=>priority(b)-priority(a)||g().officer(b)[d.sort]-g().officer(a)[d.sort]);c.refresh();generals();})]]);}
 function open(id,forcedOfficer){if(allocation){c.toast('Finish troop reassignment before opening another order.');return true;}const known=['military','personnel','diplomacy','spy','view','advice','move','develop','flood','relief','reward','trade','tax','map','delegate','exile','enlist','train','book','search','recruit','governor','advisor'];if(!known.includes(id))return false;
  const readOnly=['view','map'].includes(id);if(!readOnly&&(!g().isHuman()||g().s.battle||g().s.monthlyReview||p().owner!==me().id||g().s.campaignEnded)){c.toast('Select your province during your faction’s orders turn.');return true;}
  const seed=forcedOfficer===undefined?{}:{officer:forcedOfficer};
  if(id==='military')military();else if(id==='personnel')person();else if(id==='diplomacy')diplomacy();else if(id==='spy')spies();else if(id==='advice')advice();else if(id==='view')views();else if(id==='map'){c.close();c.onMap();}
  else if(id==='move')moving(seed);
  else if(['develop','flood'].includes(id))actorFlow(id==='develop'?'Cultivate':'Flood control',id,[amount('amount','Use how much gold?',1,()=>Math.min(100,p().gold))],seed);
  else if(id==='relief')actorFlow('Give food to the people','relief',[amount('amount','Give how much food?',1,()=>Math.min(10000,p().food))],seed);
  else if(['reward','book'].includes(id)){try{g().ready(p(),p().governor);if(id==='book')reward('Writings');else menu('Reward',['Gold','Horse','Writings'].map(kind=>[kind.toLowerCase(),kind,()=>reward(kind)]));}catch(error){info('Reward',error.message);}}
  else if(id==='trade'){if(!p().merchant)info('Merch','No merchant is visiting this province this month.');else menu('Merch',['sell','buy','horse','arms'].map((mode,i)=>[mode,['Sell food','Buy food','Buy horses','Buy weapons'][i],()=>trade(mode)]));}
  else if(id==='tax'){try{g().ready(p(),p().governor);flow('Tax',[yes('Impose special tax? Loyalty falls by 10 and ruler trust by 5.')],d=>{if(Number(d.confirm))perform('tax',{});else c.close();});}catch(error){info('Tax',error.message);}}
  else if(id==='delegate'){try{if(!rulerPresent(g(),p()))throw Error('Only the ruler may delegate from their own province.');g().ready(p(),me().leader);flow('Deleg',[select('target','Send orders where?',()=>g().s.provinces.filter(q=>q.owner===me().id&&!q.officers.includes(me().leader)).map(q=>[q.id,`${provinceLabel(g(),q)} · ${q.delegate==='manual'?'Direct rule':'Self rule'}`,{province:q.id}])),select('mode','Set provincial rule',[['self','1. Self rule'],['direct','2. Direct rule']])],d=>{if(d.mode==='direct'){perform('delegateRealm',d);return;}flow('Deleg · Self rule',[select('policy','Delegate which authority?',[['full','Full'],['internal','Internal'],['military','Military'],['personnel','Personnel']]),select('supply','Send supplies where?',()=>[[0,'Do not send'],...g().s.provinces.filter(q=>q.owner===me().id&&q.id!==Number(d.target)&&g().route(Number(d.target),q.id)).map(q=>provinceChoice(g(),q))]),select('attack','Attack which province?',()=>[[0,'Do not attack'],...g().province(d.target).neighbors.map(id=>g().province(id)).filter(q=>![255,me().id].includes(q.owner)&&!me().alliances.includes(q.owner)).map(q=>provinceChoice(g(),q))])],x=>perform('delegateRealm',{...d,...x}));});}catch(error){info('Deleg',error.message);}}
  else if(id==='exile'){try{if(!rulerPresent(g(),p()))throw Error('Only the ruler may choose self-exile from their own province.');g().ready(p(),me().leader);flow('Exile',[yes('Go into exile? Your provinces will become independent.')],d=>{if(!Number(d.confirm)){c.close();return;}flow('Exile',[select('takeAll','Take all generals in this province?',[[1,'Yes'],[0,'No']])],x=>perform('selfExile',{confirm:true,takeAll:Boolean(Number(x.takeAll))}));});}catch(error){info('Exile',error.message);}}
  else if(id==='enlist')flow('Hire men',[select('officer','Who will hire men?',ready),amount('hundreds','Hire how many hundreds of men?',1,()=>hireCapacity(g(),p())),yes(d=>`Confirm ${g().officer(d.officer).name} hiring ${n(Number(d.hundreds)*100)} men for ${n(Number(d.hundreds)*10)} gold and ${n(Number(d.hundreds)*100)} food, then assign them?`)],d=>{if(Number(d.confirm))beginAllocation('hireArmy',d);else c.close();},seed);
  else if(id==='train')actorFlow('Train all armies','trainArmy',[],seed);
  else if(['governor','advisor'].includes(id))appointment(id);
  else if(id==='search')actorFlow('Search','search',[],seed);
  else if(id==='recruit')recruit();
  else if(['governor','advisor'].includes(id))appointment(id);
  return true;
 }
 return {open,guardClose:finishAllocation,isAllocating:()=>allocation!==null,reset(){allocation=null;}};
}
