import {provinceCurrentEvents} from './event-chronicle.mjs?v=34';
import {activeBattleUnit} from './battle-presentation.mjs?v=34';
import {battlefieldKey,battlefieldFile,paintBattlefield} from './battlefield-art.mjs?v=34';
import {provinceTerrain} from './campaign-fidelity.mjs?v=34';
import {ownershipCells,layoutCityBadges} from './terrain-mask.mjs?v=34';
import {pointFor,project,provinceDirection} from './geography.mjs?v=34';
import {tilePoint,reachable,living,visibleUnit,TERRAIN,placementCells} from './battle.mjs?v=34';
const palette=['#e0b65e','#88b19c','#8faecc','#d98f79','#c0a377','#b78251','#d0be83','#81989e','#c687a4','#a995c5','#83a664','#9aafc1','#a0be7c','#d8a18a','#75b0ac','#cfb24b'];
export async function loadRasterAssets(){const assets={};await Promise.all(['clan','heir','history','courier','portraits','events','army','launch','relief','capitals','weather','disasters','omens','stories','officersHistoric','triumph',...Array.from({length:22},(_,i)=>'officers'+i),...Array.from({length:41},(_,i)=>battlefieldKey(i+1))].map(key=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{assets[key]=im;resolve();};im.onerror=()=>reject(Error('Artwork could not load: '+key));const file=key.startsWith('battlefield')?battlefieldFile(Number(key.slice(11))).replace(/\.webp$/,''):{clan:'clan-destroyed-v31',heir:'heir-vows-vengeance-v31',triumph:'triumph-v17',officersHistoric:'officers-historic-v30',history:'history-v30',disasters:'disasters-v30',omens:'omens-v30',stories:'stories-v30',terrain:'terrain-v15',army:'army-v23',launch:'launch-v9',relief:'china-relief-v9',capitals:'capitals-v9'}[key]||key;im.src='./assets/'+file+'.webp';})));return assets;}
const tileCell=t=>({0:0,1:1,2:2,3:3,4:4,5:5,6:6})[t]??0;
export function createRasterWorld(canvas,labels,game,map,terrains,assets,mode,onSelect,onHex){
 const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw Error('Canvas 2D is unavailable.');let width=1,height=1,dpr=1,running=true,frames=0,dirty=true,scale=1,center={x:0,z:7},lastFrame=0,actionTime=0,lastAction='',lastAmbush='',ambushTime=0,positionCache=new Map(),moves=new Map(),buttons=new Map();const army=assets.army,cells=ownershipCells(game.s.provinces.map(p=>({...pointFor(p),id:p.id})));let badgeLayout=null,eventLog,eventReport,eventMonth,eventIds=new Set();const currentEvents=()=>{const month=game.s.year*12+game.s.month;if(eventLog!==game.s.log||eventReport!==game.s.lastReport||eventMonth!==month){eventLog=game.s.log;eventReport=game.s.lastReport;eventMonth=month;eventIds=new Set(provinceCurrentEvents(game).filter(x=>x.events.length).map(x=>x.province.id));}return eventIds;};const reducedMotion=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true;
 const base=document.createElement('canvas');base.width=base.height=1400;const bc=base.getContext('2d'),bs=1400/144;bc.fillStyle='#315660';bc.fillRect(0,0,1400,1400);
 bc.save();bc.beginPath();for(const poly of map.land){poly.forEach((coord,i)=>{const p=project(...coord),x=(p.x+72)*bs,y=(p.z+64)*bs;i?bc.lineTo(x,y):bc.moveTo(x,y);});bc.closePath();}bc.clip();const relief=assets.relief,f=Math.max(1400/relief.width,1400/relief.height);bc.drawImage(relief,(1400-relief.width*f)/2,(1400-relief.height*f)/2,relief.width*f,relief.height*f);bc.fillStyle='#27392318';bc.fillRect(0,0,1400,1400);bc.restore();bc.strokeStyle='#bed1b35c';bc.lineWidth=2;for(const poly of map.land){bc.beginPath();poly.forEach((coord,i)=>{const p=project(...coord),x=(p.x+72)*bs,y=(p.z+64)*bs;i?bc.lineTo(x,y):bc.moveTo(x,y);});bc.closePath();bc.stroke();}
 for(const river of map.rivers){bc.beginPath();river.points.forEach((coord,i)=>{const p=project(...coord),x=(p.x+72)*bs,y=(p.z+64)*bs;i?bc.lineTo(x,y):bc.moveTo(x,y);});bc.strokeStyle='#658d9a';bc.lineWidth=4;bc.lineJoin='round';bc.stroke();}
 const screen=p=>({x:width/2+(p.x-center.x)*scale,y:height/2+(p.z-center.z)*scale}),coord=(x,y)=>({x:center.x+(x-width/2)/scale,z:center.z+(y-height/2)/scale});
 function overview(){center={x:0,z:mode==='china'?7:0};scale=mode==='china'?Math.min(width/144,(height-24)/130)*.92:Math.min((width-32)/20,(height-62)/22);dirty=true;}
 function resize(){const r=canvas.parentElement.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);dpr=Math.min(globalThis.devicePixelRatio||1,game.s.settings.quality==='high'?2:game.s.settings.quality==='low'?1:1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);overview();dirty=true;}
 function label(id,text,kind,click){let b=buttons.get(id);if(!b){b=document.createElement('button');b.className=kind;b.onclick=click;labels.append(b);buttons.set(id,b);}b.textContent=text;return b;}
 function update(){dirty=true;const b=game.s.battle;if(mode==='province'&&b){const stamp=JSON.stringify(b.lastAction);if(stamp!==lastAction){lastAction=stamp;actionTime=performance.now();}const ambush=JSON.stringify(b.lastAmbush);if(ambush!==lastAmbush){lastAmbush=ambush;ambushTime=performance.now();}for(const u of living(b).filter(u=>u.placed)){const p=tilePoint(u.q,u.r),old=positionCache.get(u.id);if(old&&(old.x!==p.x||old.z!==p.z))moves.set(u.id,{from:old,to:p,start:performance.now()});positionCache.set(u.id,p);}}}
 function china(time){
 ctx.fillStyle='#315660';ctx.fillRect(0,0,width,height);const a=screen({x:-72,z:-64});ctx.drawImage(base,a.x,a.y,144*scale,144*scale);
 if(game.s.settings.ownership!==false){ctx.save();ctx.beginPath();for(const poly of map.land){poly.forEach((coord,i)=>{const a=screen(project(...coord));i?ctx.lineTo(a.x,a.y):ctx.moveTo(a.x,a.y);});ctx.closePath();}ctx.clip();game.s.provinces.forEach((p,i)=>{const anchor=pointFor(p),poly=cells[i].map(v=>({x:anchor.x+(v.x-anchor.x)*.78,z:anchor.z+(v.z-anchor.z)*.78}));ctx.beginPath();poly.forEach((v,k)=>{const a=screen(v);k?ctx.lineTo(a.x,a.y):ctx.moveTo(a.x,a.y);});ctx.closePath();ctx.fillStyle=p.owner===255?'#ced0a010':palette[p.owner%16]+'65';ctx.fill();});ctx.restore();}
 const selectedProvince=game.province(game.s.selected),connected=new Set(selectedProvince.neighbors);
 if(game.s.settings.showNumbers!==false){const from=screen(pointFor(selectedProvince));for(const id of connected){const to=screen(pointFor(game.province(id)));ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.strokeStyle='#07120ed9';ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle='#eace89c9';ctx.lineWidth=1.5;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([]);}}
 const capital=game.ruler().home;if(dirty||!badgeLayout){const size=Math.max(9,Math.min(24,scale*3.2)),cs=size*1.65;badgeLayout=layoutCityBadges(game.s.provinces.map(p=>{const a=screen(pointFor(p));return {id:p.id,x:a.x,y:a.y-cs*.55,priority:p.id===game.s.selected?2:p.id===capital?1:0};}).filter(a=>a.x>0&&a.x<width&&a.y>8&&a.y<height-8),width,height,height<=500?22:24);}
 for(const p of game.s.provinces){const a=screen(pointFor(p)),selected=p.id===game.s.selected,current=p.id===capital,controlled=p.owner===game.s.player,size=Math.max(9,Math.min(24,scale*3.2)),color=p.owner===255?'#a0aaa4':palette[p.owner%16];
  const cell=[1,1,1,2,2,0,0,5,2,2,3,4,7,6][p.region]??2,im=assets.capitals,cw=im.width/4,ch=im.height/2,cs=size*1.65;
  // City art and number share one projected anchor; no detached name badges.
  ctx.drawImage(im,cell%4*cw,Math.floor(cell/4)*ch,cw,ch,a.x-cs*(cw/ch)/2,a.y-cs*.48,cs*(cw/ch),cs);
  const badge=badgeLayout.get(p.id)||{x:a.x,y:a.y-cs*.55};if(game.s.settings.showNumbers!==false&&Math.hypot(badge.x-a.x,badge.y-(a.y-cs*.55))>3){ctx.beginPath();ctx.moveTo(a.x,a.y-cs*.1);ctx.lineTo(badge.x,badge.y);ctx.strokeStyle=color+'bb';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(a.x,a.y-cs*.1,1.5,0,Math.PI*2);ctx.fill();}
  const node=label('p'+p.id,String(p.id),'province-label',()=>onSelect(p.id));node.setAttribute('aria-label',`Select ${p.name}${current?', ruler’s headquarters':controlled?', controlled province':''}`);node.classList.toggle('selected',selected);node.classList.toggle('controlled',controlled);node.classList.toggle('connected',connected.has(p.id));node.dataset.connections=p.neighbors.join(',');node.classList.toggle('current-capital',current);node.classList.toggle('has-event',currentEvents().has(p.id));node.dataset.eventCount=currentEvents().has(p.id)?'1':'0';node.style.display=game.s.settings.showNumbers!==false&&a.x>0&&a.x<width&&a.y>8&&a.y<height-8?'block':'none';node.style.left=badge.x+'px';node.style.top=badge.y+'px';node.style.borderColor=color;node.style.setProperty('--owner-color',color);
 }
 const j=game.s.journey;if(j){const leg=j.legs[j.leg],route=leg.route.map(id=>screen(pointFor(game.province(id))));ctx.beginPath();route.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.strokeStyle='#f7d98b';ctx.lineWidth=2;ctx.setLineDash([4,5]);ctx.stroke();ctx.setLineDash([]);let at=route[leg.index];const motion=game.journeyMotion;if(motion){const t=Math.min(1,(time-motion.start)/650),from=screen(pointFor(game.province(motion.from))),to=screen(pointFor(game.province(motion.to)));at={x:from.x+(to.x-from.x)*t,y:from.y+(to.y-from.y)*t};}
  const im=assets.courier,sw=im.width/4,sh=im.height,frame=Math.floor(time/130)%4,h=80,w=h*sw/sh;ctx.save();ctx.translate(at.x,at.y);if(leg.index&&route[leg.index].x<route[leg.index-1].x)ctx.scale(-1,1);ctx.drawImage(im,frame*sw,0,sw,sh,-w/2,-h*.7,w,h);ctx.restore();
 }
 }

 function hex(c,q,r){const p=screen(tilePoint(q,r));c.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3,x=p.x+Math.cos(a)*scale,y=p.y+Math.sin(a)*scale;i?c.lineTo(x,y):c.moveTo(x,y);}c.closePath();return p;}
 function province(time){const b=game.s.battle,p=game.province(b?.target||game.s.selected),tiles=b?.terrain||provinceTerrain(p,terrains[p.id-1]),selected=b?.units.find(u=>u.id===b.selected),preview=!b&&game.mapApproachProvince&&p.neighbors.includes(game.mapApproachProvince)?{target:p.id,terrain:tiles,units:[],fire:{},entryDirection:provinceDirection(p,game.province(game.mapApproachProvince))}:null,reach=b?(b.phase==='deployment'?placementCells(b,b.side,selected):game.battlePlacementSide?placementCells(b,game.battlePlacementSide,null,game.battlePlacementDirection):selected&&selected.side===b.side?reachable(b,selected):[]):preview?placementCells(preview,'attack'):[];ctx.fillStyle='#283b2e';ctx.fillRect(0,0,width,height);
 // A single province painting replaces the former terrain atlas and blending code.
 paintBattlefield(ctx,assets[battlefieldKey(p.id)],scale,screen);
 for(let index=0;index<tiles.length;index++){const kind=tiles[index];if(kind!==5&&kind!==6)continue;const pos=screen(tilePoint(index%13,Math.floor(index/13))),im=assets.capitals,sw=im.width/4,sh=im.height/2,cell=kind===6?0:1,h=scale*(kind===6?1.9:1.5);ctx.drawImage(im,cell%4*sw,Math.floor(cell/4)*sh,sw,sh,pos.x-h*(sw/sh)/2,pos.y-h*.6,h*(sw/sh),h);}
 for(let r=0;r<12;r++)for(let q=0;q<13;q++){
  const type=tiles[r*13+q];if(type===9||type===99)continue;
  const pos=hex(ctx,q,r);
  if(reach.some(v=>v.q===q&&v.r===r)){ctx.fillStyle='#efcc663c';ctx.fill();ctx.strokeStyle='#f3d175';ctx.lineWidth=1.3;ctx.stroke();}
  if(b?.fire[r*13+q]){const grd=ctx.createRadialGradient(pos.x,pos.y,1,pos.x,pos.y,scale);grd.addColorStop(0,'#ffe276d9');grd.addColorStop(.4,'#ed722aba');grd.addColorStop(1,'#ed452800');ctx.fillStyle=grd;ctx.globalAlpha=.7+.2*Math.sin(time*.01+q+r);ctx.fill();ctx.globalAlpha=1;}
 }

 const units=b?living(b).filter(u=>u.placed):[],activeIds=new Set();for(const u of units){if(b&&!visibleUnit(b,u)){const hidden=buttons.get('u'+u.id);if(hidden)hidden.style.display='none';continue;}activeIds.add('u'+u.id);let loc=tilePoint(u.q,u.r),moving=moves.get(u.id),walk=false;if(moving){const t=Math.min(1,(time-moving.start)/650);if(t<1){loc={x:moving.from.x+(moving.to.x-moving.from.x)*t,z:moving.from.z+(moving.to.z-moving.from.z)*t};walk=true;}else moves.delete(u.id);}const active=activeBattleUnit(b,u),pulse=active&&!reducedMotion?.46+.54*(.5+.5*Math.cos(time*2*Math.PI/1200)):1;ctx.globalAlpha=pulse;const a=screen(loc),attack=b?.lastAction?.unit===u.id&&['attack','charge','simultaneous','challenge','fireball'].includes(b?.lastAction?.type)&&time-actionTime<700||b?.lastAmbush?.unit===u.id&&time-ambushTime<700,frame=walk||attack?Math.floor(time/135)%2:0,row=(u.side==='defend'?2:0)+(attack?1:0),sw=army.width/4,sh=army.height/4,sz=Math.max(32,scale*1.8);ctx.fillStyle=u.allyOwner!==undefined&&!u.betrayed?'#e1bd42ec':u.side==='attack'?'#b6443bec':'#437aabec';ctx.beginPath();ctx.ellipse(a.x,a.y+scale*.25,scale*.72,scale*.24,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(a.x,a.y);if(u.side==='defend')ctx.scale(-1,1);const bounce=walk?Math.sin(time/85)*Math.min(1.8,scale*.05):0;ctx.drawImage(army,frame*sw,row*sh,sw,sh,-sz*(sw/sh)/2,-sz*.73+bounce,sz*(sw/sh),sz);ctx.restore();ctx.globalAlpha=1;const commander=b.leaders[u.side]===u.id,node=label('u'+u.id,u.soldiers.toLocaleString(),'unit-label',()=>onHex(u.q,u.r));node.onclick=()=>onHex(u.q,u.r);node.style.maxWidth=Math.max(44,scale*1.6)+'px';node.style.fontSize='';node.classList.toggle('active-turn',active);node.style.opacity=String(pulse);node.style.left=a.x+'px';node.style.top=(a.y+scale*.48)+'px';node.style.display=a.x>0&&a.x<width&&a.y>0&&a.y<height-40?'block':'none';node.classList.toggle('selected',b?.selected===u.id);node.classList.toggle('commander',commander);node.dataset.side=u.side;node.dataset.soldiers=String(u.soldiers);node.setAttribute('aria-label',`${commander?'Commander, ':''}${game.officer(u.id).name}, ${u.soldiers} soldiers, hex ${u.q+1}, ${u.r+1}`);activeIds.add('flag'+u.id);const flag=label('flag'+u.id,(commander?'★ ':'')+(game.s.settings.names==='chinese'?(game.officer(u.id).zh||game.officer(u.id).name):game.officer(u.id).name),'army-flag',()=>onHex(u.q,u.r));flag.dataset.side=u.side;flag.classList.toggle('commander',commander);flag.style.left=(a.x+(u.side==='defend'?-1:1)*sz*.22)+'px';flag.style.top=(a.y-sz*.53)+'px';flag.style.maxWidth=Math.max(40,sz*.52)+'px';flag.style.opacity=String(pulse);flag.style.display=node.style.display;flag.setAttribute('aria-label',`${game.officer(u.id).name} army flag`);}
 if(b&&b.weather!=='sunny'){ctx.fillStyle=b.weather==='rain'?'#263c5b18':b.weather==='cloudy'?'#15233820':'#5a667210';ctx.fillRect(0,0,width,height);if(b.weather==='rain'){ctx.strokeStyle='#c8d9e84a';ctx.lineWidth=1;for(let i=0;i<60;i++){const x=(i*71+time*.08)%width,y=(i*97+time*.28)%height;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+12);ctx.stroke();}}}
 for(const [id,node]of buttons)if((id.startsWith('u')||id.startsWith('flag'))&&!activeIds.has(id)){node.remove();buttons.delete(id);}ctx.fillStyle='#e9d9ad';ctx.font='600 14px Georgia, serif';ctx.textAlign='center';for(let q=0;q<13;q++){const a=screen(tilePoint(q,0));ctx.fillText(q+1,a.x,a.y-scale*1.12);}for(let r=0;r<12;r++){const a=screen(tilePoint(0,r));ctx.fillText(r+1,a.x-scale*1.4,a.y+4);}
 }
 function frame(time){if(!running)return;requestAnimationFrame(frame);if(document.hidden||time-lastFrame<33)return;lastFrame=time;if(mode==='china'&&!dirty&&!game.s.journey)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);mode==='china'?china(time):province(time);dirty=false;frames++;}
 const pointers=new Map();let drag=false,start=null,pinch=0;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});start={x:e.clientX,y:e.clientY};drag=false;});canvas.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch&&d)zoom(pinch/d);pinch=d;drag=true;}else if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>6){drag=true;center.x-=(e.clientX-old.x)/scale;center.z-=(e.clientY-old.y)/scale;dirty=true;}});canvas.addEventListener('pointerup',e=>{if(!drag&&pointers.size===1){const r=canvas.getBoundingClientRect(),p=coord(e.clientX-r.left,e.clientY-r.top);if(mode==='province'){let best=null,min=1.05;for(let q=0;q<13;q++)for(let row=0;row<12;row++){const c=tilePoint(q,row),d=Math.hypot(c.x-p.x,c.z-p.z);if(d<min){min=d;best={q,r:row};}}if(best)onHex(best.q,best.r);}else{const nearest=game.s.provinces.map(v=>({id:v.id,d:Math.hypot(pointFor(v).x-p.x,pointFor(v).z-p.z)})).sort((a,b)=>a.d-b.d)[0];if(nearest.d*scale<35)onSelect(nearest.id);}}pointers.delete(e.pointerId);pinch=0;start=null;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);start=null;pinch=0;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.12:.88);},{passive:false});canvas.addEventListener('dblclick',()=>zoom(.6));
 function zoom(n){scale=Math.max(mode==='china'?.7:5,Math.min(mode==='china'?25:55,scale/n));dirty=true;}
 const observer=new ResizeObserver(resize);observer.observe(canvas.parentElement);resize();update();requestAnimationFrame(frame);
 return {focus(id){if(mode==='china')center=pointFor(game.province(id));else update();dirty=true;},overview,zoom,update,setQuality(){resize();},get stats(){return {renderer:'Canvas 2D raster',frames,webgl:false,battlefieldPaintings:41};},destroy(){running=false;observer.disconnect();labels.replaceChildren();}};
}
