import {pointFor,project,insideLand} from './geography.mjs?v=20';
export async function loadThree(){
 const paths=['../../lib/three.module.js','https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js','./three.module.js'];let error;
 for(const path of paths){try{const T=await import(path);if(!T.WebGLRenderer||!T.PerspectiveCamera)throw Error('Invalid THREE module');return {T,source:path};}catch(e){error=e;}}
 throw Error('THREE.js could not load. Check the local library files or your internet connection. '+error.message);
}
const palette=['#cbaa66','#64a791','#7e9fc7','#b66963','#b9a46b','#b38958','#c5b589','#7f969e','#925b61','#9d81a8','#809c73','#7c98b8','#98b897','#c3957b','#8baba3','#c5ad72'];
export function createWorld(T,canvas,labels,game,onSelect,map){
 const renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const scene=new T.Scene();scene.background=new T.Color('#849c94');scene.fog=new T.FogExp2('#97aca1',.0045);const camera=new T.PerspectiveCamera(42,1,.3,450);
 scene.add(new T.HemisphereLight('#d3e6ec','#4d5940',2.0));const sun=new T.DirectionalLight('#ffe0ac',3.1);sun.position.set(-45,80,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-75,right:75,top:75,bottom:-75,near:1,far:220});sun.shadow.bias=-.0002;sun.shadow.normalBias=.2;scene.add(sun);const fill=new T.DirectionalLight('#b2d2e0',.6);fill.position.set(40,20,-40);scene.add(fill);
 const points=new Map();for(const p of game.s.provinces)points.set(p.id,pointFor(p));
 function hash(x,z){return (Math.sin(x*127.1+z*311.7)*43758.5453)%1;}
 function noise(x,z){const i=Math.floor(x),j=Math.floor(z),u=x-i,v=z-j;const a=u*u*(3-2*u),b=v*v*(3-2*v);const h=(a,b)=>Math.abs(hash(a,b));return T.MathUtils.lerp(T.MathUtils.lerp(h(i,j),h(i+1,j),a),T.MathUtils.lerp(h(i,j+1),h(i+1,j+1),a),b);}
 const rivers=map.rivers.map(r=>r.points.map(p=>project(...p)));
 function baseHeight(x,z){if(!insideLand(x,z,map))return -1.3;const f=noise(x*.042,z*.042)*.6+noise(x*.08,z*.08)*.28+noise(x*.2,z*.2)*.12,west=T.MathUtils.smoothstep(-x,-3,48);let h=.5+Math.pow(f,2.4)*(2+west*16);for(const river of rivers){if(river.some(p=>Math.hypot(x-p.x,z-p.z)<1.8))h=Math.min(h,.65);}return h;}
 const cityHeights=new Map();for(const [id,p]of points)cityHeights.set(id,Math.max(.65,baseHeight(p.x,p.z)));
 function height(x,z){let h=baseHeight(x,z);for(const [id,p]of points){const d=Math.hypot(p.x-x,p.z-z);if(d<4.5)h=T.MathUtils.lerp(cityHeights.get(id),h,T.MathUtils.smoothstep(d,2.7,4.5));}return h;}
 const terrainGeometry=new T.PlaneGeometry(144,144,160,160);terrainGeometry.rotateX(-Math.PI/2);const pos=terrainGeometry.attributes.position;const colors=[];const c=new T.Color();for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),h=height(x,z);pos.setY(i,h);const slope=baseHeight(x,z);const n=noise(x*.3,z*.3);c.set(slope<0?'#346c76':slope>8?'#747464':slope>4?'#5f714b':n>.55?'#6c8051':'#657b4c');c.multiplyScalar(.8+n*.3);colors.push(c.r,c.g,c.b);}terrainGeometry.setAttribute('color',new T.Float32BufferAttribute(colors,3));terrainGeometry.computeVertexNormals();
 const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=256;const tc=textureCanvas.getContext('2d'),data=tc.createImageData(256,256);for(let i=0;i<data.data.length;i+=4){const n=130+Math.floor(Math.abs(hash(i,2))*90);data.data[i]=data.data[i+1]=data.data[i+2]=n;data.data[i+3]=255;}tc.putImageData(data,0,0);const tex=new T.CanvasTexture(textureCanvas);tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(24,24);const terrain=new T.Mesh(terrainGeometry,new T.MeshStandardMaterial({vertexColors:true,map:tex,bumpMap:tex,bumpScale:.13,roughness:1}));terrain.receiveShadow=true;scene.add(terrain);
 const ocean=new T.Mesh(new T.PlaneGeometry(300,300),new T.MeshStandardMaterial({color:'#3c777b',roughness:.36,metalness:.38}));ocean.rotation.x=-Math.PI/2;ocean.position.y=-.65;scene.add(ocean);
 function ribbon(path,width,material,yOffset=.1){const verts=[],indices=[];for(let i=0;i<path.length;i++){const p=path[i],next=path[Math.min(path.length-1,i+1)],prev=path[Math.max(0,i-1)];const dx=next.x-prev.x,dz=next.z-prev.z,dist=Math.hypot(dx,dz)||1;const nx=-dz/dist*width/2,nz=dx/dist*width/2;for(const side of [-1,1]){const x=p.x+nx*side,z=p.z+nz*side;verts.push(x,height(x,z)+yOffset,z);}if(i<path.length-1){const q=i*2;indices.push(q,q+1,q+2,q+1,q+3,q+2);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setIndex(indices);g.computeVertexNormals();const mesh=new T.Mesh(g,material);mesh.receiveShadow=true;return mesh;}
 const waterMaterial=new T.MeshStandardMaterial({color:'#477e80',roughness:.25,metalness:.42,transparent:true,opacity:.92});for(const river of rivers)scene.add(ribbon(river,1.25,waterMaterial,.14));
 const roadMaterial=new T.MeshStandardMaterial({color:'#bdac81',roughness:1});const roadGeometries=[];for(const p of game.s.provinces)for(const id of p.neighbors){if(p.id>=id)continue;const a=points.get(p.id),b=points.get(id);const path=Array.from({length:18},(_,i)=>{const t=i/17;return {x:T.MathUtils.lerp(a.x,b.x,t),z:T.MathUtils.lerp(a.z,b.z,t)+Math.sin(t*Math.PI)*.7};});roadGeometries.push(ribbon(path,.14,roadMaterial,.07).geometry);}function mergeGeometries(gs){const vertices=[],normals=[],idx=[];let offset=0;for(const g of gs){vertices.push(...g.attributes.position.array);normals.push(...g.attributes.normal.array);if(g.index)for(const v of g.index.array)idx.push(v+offset);else for(let i=0;i<g.attributes.position.count;i++)idx.push(i+offset);offset+=g.attributes.position.count;}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('normal',new T.Float32BufferAttribute(normals,3));g.setIndex(idx);return g;}scene.add(new T.Mesh(mergeGeometries(roadGeometries),roadMaterial));
 const dummy=new T.Object3D();function instances(geo,mat,count){const m=new T.InstancedMesh(geo,mat,count);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}function set(m,i,x,y,z,sx,sy,sz,rotation=0){dummy.position.set(x,y,z);dummy.scale.set(sx,sy,sz);dummy.rotation.set(0,rotation,0);dummy.updateMatrix();m.setMatrixAt(i,dummy.matrix);}
 const stone=new T.MeshStandardMaterial({color:'#b1b09d',roughness:.96,bumpMap:tex,bumpScale:.04});const plaster=new T.MeshStandardMaterial({color:'#cbbfa2',roughness:.9});const roof=new T.MeshStandardMaterial({color:'#475459',roughness:.8});const darkRoof=new T.MeshStandardMaterial({color:'#314349',roughness:.76});const timber=new T.MeshStandardMaterial({color:'#674e38',roughness:.96});
 const walls=instances(new T.BoxGeometry(1,1,1),stone,41*14),houses=instances(new T.BoxGeometry(1,1,1),plaster,41*16),roofs=instances(new T.CylinderGeometry(.3,1,1,4,1),roof,41*16),towerRoofs=instances(new T.CylinderGeometry(.25,1,1,4,1),darkRoof,41*7),posts=instances(new T.CylinderGeometry(.07,.08,1,6),timber,41*2),banners=instances(new T.PlaneGeometry(1,1,4,2),new T.MeshStandardMaterial({color:'#fff',side:T.DoubleSide,roughness:.8}),41);
 const fields=instances(new T.PlaneGeometry(1,1),new T.MeshStandardMaterial({color:'#8e984b',roughness:1,side:T.DoubleSide,map:tex}),41*6);let w=0,b=0,r=0,roofI=0,postI=0,fieldI=0;
 for(const p of game.s.provinces){const a=points.get(p.id),h=cityHeights.get(p.id);
  for(const [dx,dz,sx,sz]of [[0,-1.8,3.8,.18],[0,1.8,3.8,.18],[-1.8,0,.18,3.8],[1.8,0,.18,3.8]])set(walls,w++,a.x+dx,h+.33,a.z+dz,sx,.66,sz);
  for(const dx of [-1.8,1.8])for(const dz of [-1.8,1.8]){set(walls,w++,a.x+dx,h+.5,a.z+dz,.5,1,.5);set(towerRoofs,roofI++,a.x+dx,h+1.05,a.z+dz,.6,.3,.6,Math.PI/4);}
  for(const dz of [-1.8,1.8]){set(walls,w++,a.x,h+.55,a.z+dz,.75,.2,.4);set(towerRoofs,roofI++,a.x,h+.79,a.z+dz,.7,.3,.48,Math.PI/4);}
  for(let j=0;j<15;j++){const dx=((j%4)-1.5)*.65,dz=(Math.floor(j/4)-1.5)*.65;set(houses,b++,a.x+dx,h+.19,a.z+dz,.46,.38,.4);set(roofs,r++,a.x+dx,h+.49,a.z+dz,.43,.26,.4,Math.PI/4);}
  set(houses,b++,a.x,h+.52,a.z,1.1,1.04,.75);set(towerRoofs,roofI++,a.x,h+1.18,a.z,1.08,.5,.75,Math.PI/4);
  set(posts,postI++,a.x+.5,h+1.4,a.z+.35,1,2.8,1);set(posts,postI++,a.x-.5,h+1.4,a.z+.35,1,2.8,1);set(banners,p.id-1,a.x+.91,h+2.4,a.z+.35,.8,.55,1);banners.setColorAt(p.id-1,new T.Color(p.owner===game.s.player?'#d7b57b':p.owner===255?'#8e9c8e':palette[p.owner%16]));
  for(let j=0;j<6;j++){const x=a.x+(j%3-1)*.8,z=a.z+3.05+Math.floor(j/3)*.45;dummy.position.set(x,height(x,z)+.04,z);dummy.scale.set(.7,.35,1);dummy.rotation.set(-Math.PI/2,0,0);dummy.updateMatrix();fields.setMatrixAt(fieldI++,dummy.matrix);}
 }
 walls.count=w;roofs.count=r;towerRoofs.count=roofI;posts.count=postI;fields.count=fieldI;
 const trunks=instances(new T.CylinderGeometry(.05,.07,1,5),new T.MeshStandardMaterial({color:'#544e36',roughness:1}),2000),trees=instances(new T.ConeGeometry(.48,1.65,7),new T.MeshStandardMaterial({color:'#315844',roughness:1}),2000);let ti=0;for(let i=0;i<5500&&ti<2000;i++){const x=(Math.abs(hash(i,12))-.5)*119,z=(Math.abs(hash(i,30))-.5)*120,h=height(x,z);if(!insideLand(x,z,map)||h<.45||h>12||[...points.values()].some(p=>Math.hypot(p.x-x,p.z-z)<4.4))continue;const scale=.55+Math.abs(hash(i,2))*.9;set(trunks,ti,x,h+.3*scale,z,scale,.6*scale,scale);set(trees,ti,x,h+1.1*scale,z,scale,scale,scale);trees.setColorAt(ti,new T.Color().setHSL(.28+Math.abs(hash(i,4))*.07,.26,.2+Math.abs(hash(i,6))*.07));ti++;}trees.count=trunks.count=ti;
 const borderMaterial=new T.LineBasicMaterial({color:'#d9bd81',transparent:true,opacity:.3});let borders;
 const ring=new T.Mesh(new T.RingGeometry(2.9,3.04,80),new T.MeshBasicMaterial({color:'#ffe2a2',side:T.DoubleSide,transparent:true,opacity:.8}));ring.rotation.x=-Math.PI/2;scene.add(ring);
 const target=new T.Vector3(),desired=new T.Vector3();let distance=55,desiredDistance=55,azimuth=.04,running=true,lastFrame=0,frames=0,quality='balanced',selected=-1;
 const buttons=new Map();for(const p of game.s.provinces){const button=document.createElement('button');button.className='province-label';button.setAttribute('aria-label',`Select ${p.name}`);button.addEventListener('click',()=>onSelect(p.id));labels.append(button);buttons.set(p.id,button);}
 function update(){for(const p of game.s.provinces)banners.setColorAt(p.id-1,new T.Color(p.owner===game.s.player?'#d7b57b':p.owner===255?'#8e9c8e':palette[p.owner%16]));banners.instanceColor.needsUpdate=true;if(borders){scene.remove(borders);borders.geometry.dispose();}const vertices=[];for(const p of game.s.provinces.filter(p=>p.owner===game.s.player)){const a=points.get(p.id);for(let j=0;j<24;j++){const angle=j*Math.PI/12,next=(j+1)*Math.PI/12;for(const ang of [angle,next]){const x=a.x+Math.cos(ang)*2.7,z=a.z+Math.sin(ang)*2.7;vertices.push(x,height(x,z)+.14,z);}}}const bg=new T.BufferGeometry();bg.setAttribute('position',new T.Float32BufferAttribute(vertices,3));borders=new T.LineSegments(bg,borderMaterial);scene.add(borders);}
 function focus(id,close=false){const p=points.get(id);selected=id;desired.set(p.x,cityHeights.get(id),p.z);if(close)desiredDistance=23;const a=points.get(id);ring.position.set(a.x,cityHeights.get(id)+.09,a.z);}
 function overview(){desired.set(0,2,7);desiredDistance=175;}
 function zoom(n){desiredDistance=T.MathUtils.clamp(desiredDistance*n,15,190);}
 function setQuality(value){quality=value;renderer.setPixelRatio(Math.min(devicePixelRatio,value==='high'?2:value==='low'?1:1.5));renderer.shadowMap.enabled=value!=='low';resize();}
 function resize(){const rect=canvas.parentElement.getBoundingClientRect();renderer.setSize(Math.max(1,rect.width),Math.max(1,rect.height),false);camera.aspect=rect.width/Math.max(1,rect.height);camera.updateProjectionMatrix();}
 const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(canvas.parentElement);
 const pointers=new Map();let start=null,pinch=0,dragged=false;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});start={x:e.clientX,y:e.clientY};dragged=false;if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);}});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const prev=pointers.get(e.pointerId),dx=e.clientX-prev.x,dy=e.clientY-prev.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>5)dragged=true;if(pointers.size===2){const [a,b]=[...pointers.values()];const d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch&&d)zoom(pinch/d);pinch=d;dragged=true;}else{const scale=distance/Math.max(200,canvas.clientHeight)*.65;desired.x-=dx*scale;desired.z-=dy*scale*1.3;desired.x=T.MathUtils.clamp(desired.x,-55,55);desired.z=T.MathUtils.clamp(desired.z,-58,58);}});
 const release=e=>{if(!dragged&&pointers.size===1){const rect=canvas.getBoundingClientRect();let best=null,dist=26;for(const [id,point]of points){const v=new T.Vector3(point.x,cityHeights.get(id)+1.8,point.z).project(camera);const d=Math.hypot((v.x*.5+.5)*rect.width-(e.clientX-rect.left),(-v.y*.5+.5)*rect.height-(e.clientY-rect.top));if(v.z<1&&d<dist){dist=d;best=id;}}if(best)onSelect(best);}pointers.delete(e.pointerId);pinch=0;start=null;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);start=null;pinch=0;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.1:.9);},{passive:false});canvas.addEventListener('dblclick',()=>focus(selected,true));
 const projected=new T.Vector3();let lastLabelFrame=0;function frame(time){if(!running)return;requestAnimationFrame(frame);if(document.hidden)return;const fps=quality==='high'?60:30;if(time-lastFrame<1000/fps-1)return;lastFrame=time;target.lerp(desired,.12);distance=T.MathUtils.lerp(distance,desiredDistance,.12);camera.position.set(target.x+Math.sin(azimuth)*distance*.45,target.y+distance*.7,target.z+Math.cos(azimuth)*distance*.72);camera.lookAt(target);ring.material.opacity=.65+Math.sin(time*.002)*.15;waterMaterial.roughness=.28+Math.sin(time*.001)*.03;renderer.render(scene,camera);frames++;
  if(time-lastLabelFrame>65){lastLabelFrame=time;const placed=[];const provinces=[...game.s.provinces].sort((a,b)=>(b.id===selected)-(a.id===selected));for(const p of provinces){const point=points.get(p.id),button=buttons.get(p.id);projected.set(point.x,cityHeights.get(p.id)+2.3,point.z).project(camera);const x=(projected.x*.5+.5)*canvas.clientWidth,y=(-projected.y*.5+.5)*canvas.clientHeight;let visible=projected.z<1&&x>12&&x<canvas.clientWidth-12&&y>18&&y<canvas.clientHeight-38;const named=p.id===selected||distance<60||p.governor===game.ruler(p.owner)?.leader;const width=named?75:28;if(p.id!==selected&&placed.some(v=>Math.abs(v.x-x)<(v.w+width)/2&&Math.abs(v.y-y)<27))visible=false;button.style.display=visible?'block':'none';if(visible){placed.push({x,y,w:width});button.style.left=x+'px';button.style.top=y+'px';button.textContent=named?p.name:String(p.id);button.className='province-label'+(p.id===selected?' selected':named?'':' dot');button.style.borderBottomColor=p.owner===255?'#8e9c8e':palette[p.owner%16];}}}
 }
 focus(game.s.selected);overview();target.copy(desired);update();resize();requestAnimationFrame(frame);
 const onVisibility=()=>{lastFrame=0;};document.addEventListener('visibilitychange',onVisibility);
 return {focus,overview,zoom,update,setQuality,color:id=>id===game.s.player?'#d7b57b':palette[id%16],get stats(){return {drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,frames,threeRevision:T.REVISION};},destroy(){running=false;resizeObserver.disconnect();document.removeEventListener('visibilitychange',onVisibility);renderer.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});tex.dispose();labels.replaceChildren();}};
}
