// ===== SHORT SELLER REPORT SYSTEM (EMPIRICALLY-BASED) =====
// Based on academic research: Ljungqvist & Qin (2021), Wong & Zhao (2017), Putniņš (2024)
//
// EMPIRICAL FOUNDATIONS:
// - Activist short sellers are "informed" traders, not manipulators (2-5% manipulation rate)
// - Average -20% over 4 years for targeted companies (Ljungqvist & Qin)
// - Fraud allegations: ~10% reversal probability
// - Valuation-only reports: ~40% reversal probability
// - 13.6% average drop in first 3 days for severe misconduct allegations
// - Companies with Big 4 auditors have higher survival rates
//
// SIGNAL INTEGRATION:
// - Insider buying signals from InsiderTrading module (Lakonishok & Lee 2001)
// - Cluster buying (3+ insiders) has 2x power (Hjort & Bapkas 2024)
// - Insider SELLING is NOISE - not used as signal
//
// KEY DETECTABLE SIGNALS (for educational gameplay):
// 1. Report Type: Fraud vs Valuation (binary, massive impact on outcome)
// 2. Insider Buying: Detected via InsiderTrading module (strong reversal signal)
// 3. Cluster Buying: 3+ insiders = strongest signal
// 4. Rebuttal Quality: Detailed vs Generic denial
// 5. Auditor Quality: Big 4 vs Boutique
// 6. Two-Week Base: 10-14 day consolidation pattern
//
// EDUCATIONAL PURPOSE:
// Teaches players fundamental analysis skills:
// - Distinguishing fraud from overvaluation
// - Reading insider behavior signals
// - Understanding auditor credibility
// - Patience (waiting for base formation)
// - Risk assessment (different from technical DCB analysis)
//
// ARCHITECTURE:
// This module uses dependency injection for testability.

const SSR = (function() {
  'use strict';

  // ========== EMPIRICALLY-BASED CONSTANTS ==========
  const CONSTANTS = {
    // ========== GOLD STANDARD 85% SETUP ==========
    // The highest probability SSR reversal requires ONE of these criteria
    GOLD_STANDARD: {
      description: 'Point-by-point DATA rebuttal OR Big 4 Auditor reaffirms books',
      requirements: {
        dataRebuttal: true,          // Company must provide DATA, not generic denial
        pointByPoint: true,          // Must address EACH allegation specifically
        big4Auditor: ['Deloitte', 'PwC', 'EY', 'KPMG'], // Big 4 firms only
        auditorAction: 'reaffirm',   // Auditor must REAFFIRM the books
        successRate: 0.85            // 85% success when criteria met
      },
      educationalNote: 'Generic denials are RED FLAGS. Only data-driven rebuttals or Big 4 auditor support matter.'
    },
    
    // Report type determines outcome probability
    REPORT_TYPES: {
      fraud: {
        probability: 0.40,           // 40% of reports allege fraud
        reversalChance: 0.10,        // Only 10% reverse (very dangerous)
        initialDrop: { min: 0.20, max: 0.35 },  // 20-35% initial drop
        longTermDecline: { min: 0.50, max: 0.80 },  // 50-80% permanent loss if true
        description: 'alleges accounting fraud or fake revenue'
      },
      valuation: {
        probability: 0.60,           // 60% are valuation-based
        reversalChance: 0.40,        // 40% reverse at fair value
        initialDrop: { min: 0.15, max: 0.25 },  // 15-25% initial drop
        fairValueDiscount: { min: 0.20, max: 0.35 },  // Settles at 20-35% below peak
        description: 'claims stock is overvalued'
      }
    },

    // Insider buying signals (from InsiderTrading module - Lakonishok & Lee 2001)
    // NOTE: Actual insider events generated by InsiderTrading module
    // These constants define how SSR responds to those signals
    INSIDER_BUYING: {
      reversalBoost: 0.30,           // +30% to reversal probability for insider buy
      clusterBoost: 0.15,            // +15% additional for cluster buying (3+ insiders)
      // Legacy fields for backward compatibility (events now from InsiderTrading module)
      probability: 0.25,             // Probability InsiderTrading generates buy during SSR
      amounts: ['$500K', '$1M', '$2M', '$5M'],
      titles: ['CEO', 'CFO', 'Chairman', 'Director']
    },

    // Auditor quality (Big 4 vs boutique)
    AUDITOR: {
      big4: {
        probability: 0.45,           // 45% have Big 4 auditors
        reversalBoost: 0.15,         // +15% to reversal probability
        names: ['PwC', 'Deloitte', 'EY', 'KPMG']
      },
      boutique: {
        probability: 0.55,           // 55% have smaller auditors
        reversalPenalty: 0.10,       // -10% from reversal probability
        names: ['Local CPA', 'Regional Firm', 'Offshore Auditor']
      }
    },

    // Company rebuttal quality
    // Brendel & Ryans (2021): "Responding to Activist Short Sellers"
    // - Only 31% of firms respond at all
    // - Public denial: -14% 3-day return
    // - Internal investigation: -24% 3-day return (SELL SIGNAL)
    // - No response: 0% return, fewer SEC actions ("stay silent" paradox)
    REBUTTAL: {
      detailed: {
        probability: 0.15,           // 15% provide data-driven rebuttals (rare)
        reversalBoost: 0.15,         // +15% to reversal probability
        description: 'point-by-point rebuttal citing specific documents (10-K page refs, GPS logs)',
        timing: { min: 3, max: 5 }   // Gold Standard: 3-5 trading days
      },
      generic: {
        probability: 0.16,           // 16% give generic denials (28% of 31% who respond * ~60%)
        reversalPenalty: 0.05,       // -5% from reversal probability
        description: 'uses opinion words: "unfounded," "baseless," "categorically denies"',
        timing: { min: 0, max: 2 }   // Immediate: 0-48 hours
      },
      investigation: {
        probability: 0.08,           // 8% launch internal investigation
        reversalPenalty: 0.25,       // -25% MAJOR penalty (confirms something to find)
        description: 'launches internal investigation or hires special committee',
        timing: { min: 7, max: 14 }  // Takes 2-4 weeks = SELL SIGNAL
      },
      none: {
        probability: 0.61,           // 69% don't respond (Brendel & Ryans: silence often optimal)
        reversalPenalty: 0.00,       // NO penalty if Big 4 auditor ("noise not worth acknowledging")
        reversalPenaltyNoBig4: 0.15, // -15% penalty if no Big 4 backing
        description: 'no public response from company'
      }
    },

    // Two-week base pattern (technical confirmation)
    BASE_PATTERN: {
      minDays: 10,                   // Minimum 10 days
      maxDays: 14,                   // Maximum 14 days
      breakoutProbability: 0.60,     // 60% breakout if base forms properly
      volumeContraction: 0.4         // Volume drops to 40% of crash volume
    },

    // Duration for various phases (in days)
    // Brendel & Ryans (2021): >7 days without response = market assumes merit
    DURATION: {
      initialCrash: { min: 2, max: 4 },      // 2-4 days of selling (13.6% avg drop)
      rebuttalWindow: { min: 5, max: 7 },    // 5-7 days - if no detailed rebuttal by day 7, bearish
      baseBuilding: { min: 10, max: 14 },    // 10-14 day consolidation ("two-week base")
      resolution: { min: 5, max: 10 }        // 5-10 days for breakout/breakdown
    },

    // Volume patterns
    VOLUME: {
      reportDay: 5.0,                // 500% volume on report day
      panic: 3.0,                    // 300% during panic selling
      baseBuilding: 0.4,             // 40% during consolidation
      breakout: 2.0,                 // 200% on breakout
      breakdown: 2.5                 // 250% on breakdown
    },

    // Short seller firms (for news generation)
    SHORT_SELLERS: [
      { name: 'Hindenburg Research', reputation: 'high', specialty: 'fraud' },
      { name: 'Muddy Waters', reputation: 'high', specialty: 'fraud' },
      { name: 'Citron Research', reputation: 'medium', specialty: 'valuation' },
      { name: 'Wolfpack Research', reputation: 'medium', specialty: 'fraud' },
      { name: 'Spruce Point', reputation: 'medium', specialty: 'valuation' },
      { name: 'Grizzly Research', reputation: 'low', specialty: 'valuation' }
    ]
  };

  // ========== DEPENDENCIES (INJECTED) ==========
  let deps = {
    stocks: null,
    todayNews: null,
    getMemeMultiplier: null,
    randomChoice: null,
    isEventTypeEnabled: null,
    random: Math.random
  };

  // ========== INITIALIZATION ==========
  function init(dependencies) {
    if (dependencies.stocks !== undefined) deps.stocks = dependencies.stocks;
    if (dependencies.todayNews !== undefined) deps.todayNews = dependencies.todayNews;
    if (dependencies.getMemeMultiplier !== undefined) deps.getMemeMultiplier = dependencies.getMemeMultiplier;
    if (dependencies.randomChoice !== undefined) deps.randomChoice = dependencies.randomChoice;
    if (dependencies.isEventTypeEnabled !== undefined) deps.isEventTypeEnabled = dependencies.isEventTypeEnabled;
    if (dependencies.random !== undefined) deps.random = dependencies.random;

    return SSR;
  }

  // ========== HELPER FUNCTIONS ==========
  function getStocks() {
    return deps.stocks || (typeof stocks !== 'undefined' ? stocks : []);
  }

  function getNews() {
    return deps.todayNews || (typeof todayNews !== 'undefined' ? todayNews : []);
  }

  function getMemeMultiplier(stock) {
    if (deps.getMemeMultiplier) return deps.getMemeMultiplier(stock);
    if (typeof window !== 'undefined' && typeof window.getMemeMultiplier === 'function') {
      return window.getMemeMultiplier(stock);
    }
    return (stock.isMeme || stock.volatility > 0.05) ? 1.5 : 1.0;
  }

  function randomChoice(arr) {
    if (deps.randomChoice) return deps.randomChoice(arr);
    if (typeof window !== 'undefined' && typeof window.randomChoice === 'function') {
      return window.randomChoice(arr);
    }
    return arr[Math.floor(deps.random() * arr.length)];
  }

  function isEventTypeEnabled(eventType) {
    if (deps.isEventTypeEnabled) return deps.isEventTypeEnabled(eventType);
    if (typeof window !== 'undefined' && typeof window.isEventTypeEnabled === 'function') {
      return window.isEventTypeEnabled(eventType);
    }
    return true;
  }

  function getDate() {
    let gs = (typeof gameState !== 'undefined') ? gameState : (typeof window !== 'undefined' && window.gameState) ? window.gameState : null;
    if (gs && gs.year && gs.month && gs.day) return `Y${gs.year}/M${gs.month}/D${gs.day}`;
    return '?';
  }

  function getPriceInfo(stock) {
    const price = stock.price ? `$${stock.price.toFixed(2)}` : '$?';
    const delta = stock.preReportPrice 
      ? `${((stock.price - stock.preReportPrice) / stock.preReportPrice * 100).toFixed(1)}%`
      : '?';
    return `[${price} Δ${delta.startsWith('-') ? '' : '+'}${delta}]`;
  }

  function random() {
    return deps.random();
  }

  // ========== CALCULATE REVERSAL PROBABILITY ==========
  // Combines all signals into a final reversal probability
  function calculateReversalProbability(stock, verbose = true) {
    const baseReversalChance = stock.reportType === 'fraud' 
      ? CONSTANTS.REPORT_TYPES.fraud.reversalChance 
      : CONSTANTS.REPORT_TYPES.valuation.reversalChance;
    
    let runningProb = baseReversalChance;
    
    // Build calculation breakdown for logging
    const breakdown = [];
    breakdown.push(`  Base (${stock.reportType}): ${(baseReversalChance * 100).toFixed(0)}%`);
    
    // Insider buying - now checked via InsiderBuying module (separate from InsiderSelling)
    // Uses module if available, falls back to stock.insiderBuying flag
    const insiderBoost = (typeof InsiderBuying !== 'undefined' && InsiderBuying.getInsiderBoost)
      ? InsiderBuying.getInsiderBoost(stock)
      : { hasBuySignal: stock.insiderBuying || false, isClusterBuy: false, buyCount: 0 };
    
    if (insiderBoost.isClusterBuy) {
      // Cluster buying = strongest signal (Hjort & Bapkas 2024)
      const boost = CONSTANTS.INSIDER_BUYING.reversalBoost + CONSTANTS.INSIDER_BUYING.clusterBoost;
      runningProb += boost;
      breakdown.push(`  + CLUSTER Insider Buying (${insiderBoost.buyCount} insiders): +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else if (insiderBoost.hasBuySignal || stock.insiderBuying) {
      const boost = CONSTANTS.INSIDER_BUYING.reversalBoost;
      runningProb += boost;
      const details = stock.insiderBuyingTitle && stock.insiderBuyingAmount 
        ? `(${stock.insiderBuyingTitle} ${stock.insiderBuyingAmount})` 
        : `(${insiderBoost.buyCount || 1} insider${insiderBoost.buyCount > 1 ? 's' : ''})`;
      breakdown.push(`  + Insider Buying ${details}: +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else {
      breakdown.push(`  + Insider Buying: NONE (+0%)`);
    }
    
    // Auditor quality
    if (stock.auditorQuality === 'big4') {
      const boost = CONSTANTS.AUDITOR.big4.reversalBoost;
      runningProb += boost;
      breakdown.push(`  + Auditor (${stock.auditorName} - Big 4): +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else {
      const penalty = CONSTANTS.AUDITOR.boutique.reversalPenalty;
      runningProb -= penalty;
      breakdown.push(`  + Auditor (${stock.auditorName} - Boutique): -${(penalty * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    }
    
    // Rebuttal quality - Brendel & Ryans (2021) findings
    if (stock.rebuttalQuality === 'detailed') {
      const boost = CONSTANTS.REBUTTAL.detailed.reversalBoost;
      runningProb += boost;
      breakdown.push(`  + Rebuttal (DETAILED DATA): +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else if (stock.rebuttalQuality === 'generic') {
      const penalty = CONSTANTS.REBUTTAL.generic.reversalPenalty;
      runningProb -= penalty;
      breakdown.push(`  + Rebuttal (GENERIC denial): -${(penalty * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else if (stock.rebuttalQuality === 'investigation') {
      // Investigation = MAJOR SELL SIGNAL (Brendel & Ryans: -24% vs -14%)
      const penalty = CONSTANTS.REBUTTAL.investigation.reversalPenalty;
      runningProb -= penalty;
      breakdown.push(`  + Rebuttal (INVESTIGATION): -${(penalty * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}% ⚠️ SELL SIGNAL`);
    } else if (stock.rebuttalQuality === 'none') {
      // Silence - penalty depends on auditor (Big 4 can stay silent credibly)
      const penalty = stock.auditorQuality === 'big4' 
        ? CONSTANTS.REBUTTAL.none.reversalPenalty 
        : CONSTANTS.REBUTTAL.none.reversalPenaltyNoBig4;
      runningProb -= penalty;
      const note = stock.auditorQuality === 'big4' ? '(Big 4 "stay silent" paradox)' : '(no Big 4 backing)';
      breakdown.push(`  + Rebuttal (SILENT ${note}): -${(penalty * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    }
    
    // Clamp between 0.05 and 0.75
    const finalProb = Math.max(0.05, Math.min(0.75, runningProb));
    
    if (runningProb !== finalProb) {
      breakdown.push(`  CLAMPED: ${(runningProb * 100).toFixed(0)}% → ${(finalProb * 100).toFixed(0)}% (range: 5%-75%)`);
    }
    
    breakdown.push(`  ═══════════════════════════`);
    breakdown.push(`  FINAL REVERSAL PROBABILITY: ${(finalProb * 100).toFixed(0)}%`);
    
    // Log the breakdown
    if (verbose) {
      console.log(`[SSR] ${getDate()}: ${stock.symbol} Reversal Probability ${getPriceInfo(stock)}:`);
      breakdown.forEach(line => console.log(line));
    }
    
    return finalProb;
  }

  // ========== TRIGGER SHORT REPORT ==========
  function triggerShortReport(stock, shortSeller = null) {
    if (stock.shortReportPhase || stock.crashPhase) return false;

    const memeMultiplier = getMemeMultiplier(stock);

    // Select short seller
    const seller = shortSeller || randomChoice(CONSTANTS.SHORT_SELLERS);
    stock.shortSeller = seller;

    // Determine report type (fraud vs valuation)
    const isFraud = random() < CONSTANTS.REPORT_TYPES.fraud.probability;
    stock.reportType = isFraud ? 'fraud' : 'valuation';
    const reportConfig = CONSTANTS.REPORT_TYPES[stock.reportType];

    // Determine auditor quality
    stock.auditorQuality = random() < CONSTANTS.AUDITOR.big4.probability ? 'big4' : 'boutique';
    stock.auditorName = stock.auditorQuality === 'big4' 
      ? randomChoice(CONSTANTS.AUDITOR.big4.names)
      : randomChoice(CONSTANTS.AUDITOR.boutique.names);

    // Calculate initial crash magnitude
    const crashMagnitude = reportConfig.initialDrop.min + 
      random() * (reportConfig.initialDrop.max - reportConfig.initialDrop.min);

    // Store pre-crash state
    stock.preReportPrice = stock.price;
    stock.reportCrashMagnitude = crashMagnitude;
    stock.shortReportPhase = 'initial_crash';
    // +1 because processShortReport decrements BEFORE checking phase transition
    stock.shortReportDaysLeft = CONSTANTS.DURATION.initialCrash.min + 
      Math.floor(random() * (CONSTANTS.DURATION.initialCrash.max - CONSTANTS.DURATION.initialCrash.min + 1)) + 1;

    // These will be determined later
    stock.insiderBuying = false;
    stock.insiderBuyingAmount = null;
    stock.insiderBuyingTitle = null;
    stock.rebuttalQuality = null;
    stock.baseDays = 0;
    stock.baseHighPrice = 0;
    stock.baseLowPrice = Infinity;

    // Volume spike on report
    stock.volumeMultiplier = CONSTANTS.VOLUME.reportDay;
    stock.volumeTrend = 'spike';

    // Apply immediate crash impact
    stock.sentimentOffset = -(crashMagnitude * 0.7) * memeMultiplier;
    stock.volatilityBoost = (stock.volatilityBoost || 0) + 0.6 * memeMultiplier;
    stock.shortReportTransitionEffect = -(crashMagnitude * 0.5 + random() * crashMagnitude * 0.2);

    console.log(`[SSR] ${getDate()}: ${stock.symbol} SHORT REPORT by ${seller.name}: ${stock.reportType.toUpperCase()} ${getPriceInfo(stock)} [daysLeft=${stock.shortReportDaysLeft}]`);

    return true;
  }

  // ========== CHECK FOR NEW SHORT REPORTS ==========
  function checkShortReportEvents() {
    const stockList = getStocks();
    const news = getNews();

    // Very rare event: 0.5% per stock per day
    stockList.forEach(stock => {
      if (!stock.shortReportPhase && !stock.crashPhase && random() < 0.005) {
        const seller = randomChoice(CONSTANTS.SHORT_SELLERS);

        triggerShortReport(stock, seller);

        // Generate initial report news
        const reportTypeDesc = CONSTANTS.REPORT_TYPES[stock.reportType].description;
        
        // Empirical NLP: "Hard Information" with specific accounting terms (Loughran & McDonald 2011)
        // Keywords: "Exposed," "Phantom," "Fabricated," "Investigation," "Whistleblower," "Audit"
        const fraudHeadlines = [
          `🔴 ${seller.name}: "${stock.symbol} Fabricated 40% of Reported Revenue"`,
          `🔴 ${seller.name} EXPOSES ${stock.symbol}: "Phantom Inventory, Fake Invoices"`,
          `🔴 WHISTLEBLOWER: ${seller.name} Report on ${stock.symbol} Cites Internal Documents`
        ];
        const valuationHeadlines = [
          `🔴 ${seller.name}: "${stock.symbol} Worth 70% Less" - Detailed Analysis`,
          `🔴 ${seller.name} TARGETS ${stock.symbol}: "Massively Overvalued" - Price Target $0`
        ];
        const headline = stock.reportType === 'fraud'
          ? fraudHeadlines[Math.floor(Math.random() * fraudHeadlines.length)]
          : valuationHeadlines[Math.floor(Math.random() * valuationHeadlines.length)];
        
        news.push({
          headline: headline,
          description: `Activist short seller ${seller.name} releases damaging report that ${reportTypeDesc}. ` +
            `Stock halted briefly as trading volume explodes.`,
          sentiment: 'very_negative',
          relatedStock: stock.symbol,
          newsType: 'short_report',
          isShortReport: true,
          // Educational data
          reportType: stock.reportType,
          volumeIndicator: 'EXTREME (5x normal)',
          auditorInfo: `Auditor: ${stock.auditorName}`,
          educationalNote: stock.reportType === 'fraud' 
            ? '🎯 ACTION: DO NOT BUY YET. Fraud = only 10% reverse. Wait for data rebuttal + insider buying!'
            : '🎯 ACTION: WAIT AND WATCH. Valuation = 40% reversal rate. Look for insider buying signal.'
        });
      }
    });
  }

  // ========== MAIN PROCESSING FUNCTION ==========
  function processShortReport() {
    const stockList = getStocks();

    stockList.forEach(stock => {
      if (!stock.shortReportPhase) return;

      if (!isEventTypeEnabled('short_report')) {
        clearShortReportState(stock);
        return;
      }

      const memeMultiplier = getMemeMultiplier(stock);

      // Apply pending transition effects
      if (stock.pendingTransitionEffect) {
        stock.shortReportTransitionEffect = stock.pendingTransitionEffect;
        stock.pendingTransitionEffect = 0;
      }

      stock.shortReportDaysLeft--;

      // Route to appropriate phase handler
      switch (stock.shortReportPhase) {
        case 'initial_crash':
          processInitialCrashPhase(stock, memeMultiplier);
          break;
        case 'rebuttal_window':
          processRebuttalPhase(stock, memeMultiplier);
          break;
        case 'base_building':
          processBaseBuildingPhase(stock, memeMultiplier);
          break;
        case 'resolution':
          processResolutionPhase(stock, memeMultiplier);
          break;
      }
    });
  }

  // ===== INITIAL CRASH PHASE PROCESSING =====
  function processInitialCrashPhase(stock, memeMultiplier) {
    const news = getNews();

    if (stock.shortReportDaysLeft <= 0) {
      // Record the initial crash low
      stock.shortReportLow = stock.price;

      // Transition to rebuttal window
      stock.shortReportPhase = 'rebuttal_window';
      // +1 because processShortReport decrements BEFORE checking phase transition
      stock.shortReportDaysLeft = CONSTANTS.DURATION.rebuttalWindow.min + 
        Math.floor(random() * (CONSTANTS.DURATION.rebuttalWindow.max - CONSTANTS.DURATION.rebuttalWindow.min + 1)) + 1;

      // Decrease volume but stay elevated
      stock.volumeMultiplier = CONSTANTS.VOLUME.panic;
      stock.volumeTrend = 'elevated';

      // Determine if insiders will buy (KEY SIGNAL)
      if (random() < CONSTANTS.INSIDER_BUYING.probability) {
        stock.insiderBuying = true;
        stock.insiderBuyingAmount = randomChoice(CONSTANTS.INSIDER_BUYING.amounts);
        stock.insiderBuyingTitle = randomChoice(CONSTANTS.INSIDER_BUYING.titles);
        stock.insiderBuyingDay = 1 + Math.floor(random() * stock.shortReportDaysLeft);
      }

      console.log(`[SSR] ${getDate()}: ${stock.symbol} → REBUTTAL WINDOW ${getPriceInfo(stock)} (insider buying: ${stock.insiderBuying}) [daysLeft=${stock.shortReportDaysLeft}]`);
      
      // Generate news
      news.push({
        headline: `${stock.symbol} shares stabilize after ${(stock.reportCrashMagnitude * 100).toFixed(0)}% plunge`,
        description: `Trading remains volatile as investors await company response to ${stock.shortSeller.name}'s allegations.`,
        sentiment: 'negative',
        relatedStock: stock.symbol,
        newsType: 'short_report_update',
        volumeIndicator: 'HIGH (3x normal)',
        educationalNote: '🎯 ACTION: WAIT. Do NOT buy yet. Watch for: 1) Data rebuttal, 2) Insider buying, 3) Base formation.'
      });
    } else {
      // Continue crash
      stock.sentimentOffset = -(0.08 + random() * 0.06) * memeMultiplier;
    }
  }

  // ===== REBUTTAL PHASE PROCESSING =====
  // Brendel & Ryans (2021): Timing windows for company response
  // - Day 1-2: Generic denial expected (28% of cases)
  // - Day 3-5: Gold Standard for detailed rebuttal
  // - Day 7+: No response = market assumes allegations have merit
  function processRebuttalPhase(stock, memeMultiplier) {
    const news = getNews();
    const totalDays = CONSTANTS.DURATION.rebuttalWindow.max;
    const daysInPhase = (totalDays - stock.shortReportDaysLeft);

    // Day 1-2: Check for immediate generic denial (0-48 hours)
    if (daysInPhase === 1 && !stock.initialDenial) {
      // 28% of responding firms issue immediate denial
      if (random() < 0.28) {
        stock.initialDenial = true;
        news.push({
          headline: `${stock.symbol} "categorically denies" ${stock.shortSeller.name}'s allegations`,
          description: `Company issues immediate press release calling the report "baseless" and ` +
            `"filled with inaccuracies." No specific data provided to counter claims.`,
          sentiment: 'neutral',
          relatedStock: stock.symbol,
          newsType: 'short_report_update',
          volumeIndicator: 'HIGH',
          educationalNote: '🎯 ACTION: WAIT. Generic denial is NOT enough. Watch for DATA rebuttal with documents in 3-5 days.'
        });
      }
    }

    // Day 3-5: Detailed rebuttal window (Gold Standard timing)
    if (daysInPhase >= 3 && daysInPhase <= 5 && !stock.rebuttalQuality) {
      // Determine rebuttal quality based on empirical probabilities
      const rebuttalRoll = random();
      let cumProb = 0;
      
      cumProb += CONSTANTS.REBUTTAL.detailed.probability;
      if (rebuttalRoll < cumProb) {
        stock.rebuttalQuality = 'detailed';
        stock.rebuttalDay = daysInPhase;
      } else {
        cumProb += CONSTANTS.REBUTTAL.investigation.probability;
        if (rebuttalRoll < cumProb) {
          stock.rebuttalQuality = 'investigation';
          stock.rebuttalDay = daysInPhase + 5; // Investigation announced later
        } else {
          cumProb += CONSTANTS.REBUTTAL.generic.probability;
          if (rebuttalRoll < cumProb && !stock.initialDenial) {
            stock.rebuttalQuality = 'generic';
            stock.rebuttalDay = daysInPhase;
          } else {
            stock.rebuttalQuality = 'none';
          }
        }
      }

      // Generate rebuttal news if determined
      if (stock.rebuttalQuality && stock.rebuttalQuality !== 'none') {
        generateRebuttalNews(stock);
      }
      
      // Effect based on rebuttal quality
      if (stock.rebuttalQuality === 'detailed') {
        stock.pendingTransitionEffect = 0.03 + random() * 0.02;
        stock.sentimentOffset = 0.03 * memeMultiplier;
      } else if (stock.rebuttalQuality === 'investigation') {
        // Investigation = SELL SIGNAL (Brendel & Ryans: -24% vs -14%)
        stock.pendingTransitionEffect = -(0.05 + random() * 0.03);
        stock.sentimentOffset = -0.05 * memeMultiplier;
      }
    }

    // Day 7: No detailed response = bearish signal
    if (daysInPhase === 7 && stock.rebuttalQuality === 'none') {
      generateRebuttalNews(stock); // Generate "no response" news
      // Penalty depends on auditor quality (Big 4 can stay silent credibly)
      if (stock.auditorQuality !== 'big4') {
        stock.sentimentOffset = -0.03 * memeMultiplier;
      }
    }

    // Check for insider buying event (strongest reversal signal)
    if (stock.insiderBuying && daysInPhase === stock.insiderBuyingDay) {
      console.log(`[SSR] ${getDate()}: ${stock.symbol} INSIDER BUY ${getPriceInfo(stock)} ${stock.insiderBuyingTitle} buys ${stock.insiderBuyingAmount}`);
      
      news.push({
        headline: `💰 ${stock.symbol} ${stock.insiderBuyingTitle} BUYS ${stock.insiderBuyingAmount} in shares`,
        description: `Company insider makes significant open-market purchase following short attack. ` +
          `Brendel & Ryans (2021): Insider buying after fast denial = highest reversal probability.`,
        sentiment: 'positive',
        relatedStock: stock.symbol,
        newsType: 'insider_buying',
        isInsiderBuying: true,
        volumeIndicator: 'MODERATE',
        educationalNote: '🎯 ACTION: BUY NOW or PREPARE TO BUY. Insider buying = STRONGEST signal. Wait for base breakout for confirmation.'
      });

      // Strong positive effect
      stock.pendingTransitionEffect = 0.04 + random() * 0.02;
      stock.sentimentOffset = 0.04 * memeMultiplier;
    }

    // On last day of rebuttal window, transition to base building
    if (stock.shortReportDaysLeft <= 0) {
      // If rebuttal wasn't determined yet (edge case), determine now
      if (!stock.rebuttalQuality) {
        const rebuttalRoll = random();
        if (rebuttalRoll < CONSTANTS.REBUTTAL.detailed.probability) {
          stock.rebuttalQuality = 'detailed';
        } else if (rebuttalRoll < CONSTANTS.REBUTTAL.detailed.probability + CONSTANTS.REBUTTAL.generic.probability) {
          stock.rebuttalQuality = 'generic';
        } else {
          stock.rebuttalQuality = 'none';
        }
        generateRebuttalNews(stock);
      }

      // Calculate final reversal probability
      stock.reversalProbability = calculateReversalProbability(stock);

      // Determine actual outcome based on probability
      stock.willReverse = random() < stock.reversalProbability;

      // Transition to base building phase
      stock.shortReportPhase = 'base_building';
      // +1 because processShortReport decrements BEFORE checking phase transition
      stock.shortReportDaysLeft = CONSTANTS.DURATION.baseBuilding.min + 
        Math.floor(random() * (CONSTANTS.DURATION.baseBuilding.max - CONSTANTS.DURATION.baseBuilding.min + 1)) + 1;
      stock.baseDays = 0;
      stock.baseHighPrice = stock.price;
      stock.baseLowPrice = stock.price;
      stock.baseAnchorPrice = stock.price; // Anchor for mean reversion during base

      // Volume contracts during base building - KEY for tight range
      stock.volumeMultiplier = CONSTANTS.VOLUME.baseBuilding;
      stock.volumeTrend = 'contracting';
      
      // CRITICAL: Reduce volatility significantly during base building
      // This is what creates the "tight range" consolidation pattern
      stock.volatilityBoost = Math.max(0, (stock.volatilityBoost || 0) * 0.3);

      console.log(`[SSR] ${getDate()}: ${stock.symbol} → BASE BUILDING ${getPriceInfo(stock)} (reversal prob: ${(stock.reversalProbability * 100).toFixed(0)}%, will reverse: ${stock.willReverse}) [daysLeft=${stock.shortReportDaysLeft}]`);
    } else {
      // Volatile trading during rebuttal phase
      stock.sentimentOffset = (random() - 0.55) * 0.04 * memeMultiplier;
    }
  }

  // ===== BASE BUILDING PHASE PROCESSING =====
  function processBaseBuildingPhase(stock, memeMultiplier) {
    const news = getNews();
    
    // Track the base range
    stock.baseDays++;
    stock.baseHighPrice = Math.max(stock.baseHighPrice, stock.price);
    stock.baseLowPrice = Math.min(stock.baseLowPrice, stock.price);

    // Calculate range tightness (volatility contraction)
    const rangePercent = stock.baseHighPrice > 0 
      ? (stock.baseHighPrice - stock.baseLowPrice) / stock.baseHighPrice 
      : 0;
    stock.baseRangePercent = rangePercent;

    // Is the base forming properly? (range < 15% and enough days)
    // Loosened from 10% to 15% to account for normal volatility
    const isValidBase = rangePercent < 0.15 && stock.baseDays >= CONSTANTS.BASE_PATTERN.minDays;

    if (stock.shortReportDaysLeft <= 0) {
      // Time to resolve - breakout or breakdown
      stock.shortReportPhase = 'resolution';
      // +1 because processShortReport decrements BEFORE checking phase transition
      stock.shortReportDaysLeft = CONSTANTS.DURATION.resolution.min + 
        Math.floor(random() * (CONSTANTS.DURATION.resolution.max - CONSTANTS.DURATION.resolution.min + 1)) + 1;

      // Log base validation for debugging
      console.log(`[SSR] ${getDate()}: ${stock.symbol} BASE ANALYSIS ${getPriceInfo(stock)}`);
      console.log(`  Days: ${stock.baseDays}/${CONSTANTS.BASE_PATTERN.minDays}, Range: $${stock.baseLowPrice.toFixed(2)}-$${stock.baseHighPrice.toFixed(2)} (${(rangePercent * 100).toFixed(1)}%)`);
      console.log(`  Valid: ${isValidBase}, Will Reverse: ${stock.willReverse}`);

      // Determine direction: 
      // - If willReverse is true AND base is valid = high confidence breakout
      // - If willReverse is true BUT base invalid = still breakout but weaker (empirical prob won)
      // - If willReverse is false = breakdown regardless of base quality
      if (stock.willReverse) {
        stock.resolutionDirection = 'breakout';
        stock.volumeMultiplier = CONSTANTS.VOLUME.breakout;
        stock.volumeTrend = 'increasing';
        
        // Set immediate price impact for breakout day
        const breakoutStrength = 0.04 + random() * 0.03; // +4% to +7% on breakout day
        stock.sentimentOffset = breakoutStrength * memeMultiplier;
        stock.shortReportTransitionEffect = breakoutStrength;
        
        const confidence = isValidBase ? 'HIGH-PROBABILITY' : 'MODERATE';
        news.push({
          headline: `📈 ${stock.symbol} BREAKS OUT above resistance on high volume`,
          description: `After ${stock.baseDays} days of consolidation, shares surge above the base high of $${stock.baseHighPrice.toFixed(2)}. ` +
            `Volume confirms institutional buying.${isValidBase ? '' : ' Base was volatile but buying pressure won out.'}`,
          sentiment: 'positive',
          relatedStock: stock.symbol,
          newsType: 'breakout',
          volumeIndicator: 'HIGH (2x normal)',
          educationalNote: `🎯 ACTION: BUY NOW if not already in. HOLD if long. Breakout confirmed - ride the trend!`
        });
      } else {
        stock.resolutionDirection = 'breakdown';
        stock.volumeMultiplier = CONSTANTS.VOLUME.breakdown;
        stock.volumeTrend = 'increasing';
        
        // Set immediate price impact for breakdown day
        const breakdownStrength = -(0.05 + random() * 0.04); // -5% to -9% on breakdown day
        stock.sentimentOffset = breakdownStrength * memeMultiplier;
        stock.shortReportTransitionEffect = breakdownStrength;
        
        news.push({
          headline: `📉 ${stock.symbol} BREAKS DOWN below support, new lows likely`,
          description: `Base pattern fails as shares crash through $${stock.baseLowPrice.toFixed(2)} support. ` +
            `Short seller's thesis appears validated.`,
          sentiment: 'very_negative',
          relatedStock: stock.symbol,
          newsType: 'breakdown',
          volumeIndicator: 'HIGH (2.5x normal)',
          educationalNote: '🎯 ACTION: SELL if holding. DO NOT BUY. Short seller was right - more downside ahead.'
        });
      }

      console.log(`[SSR] ${getDate()}: ${stock.symbol} → RESOLUTION (${stock.resolutionDirection}) ${getPriceInfo(stock)} [daysLeft=${stock.shortReportDaysLeft}]`);
    } else {
      // During base building - tight range, low volume
      // TIGHT RANGE consolidation - mean reversion to anchor price
      // This creates the "two-week base" pattern empirically observed
      const anchorPrice = stock.baseAnchorPrice || stock.price;
      const priceDeviation = (stock.price - anchorPrice) / anchorPrice;
      
      // Mean reversion: pull price back toward anchor if it drifts too far
      // This simulates the "absorption of selling pressure" mentioned in research
      let meanReversionForce = 0;
      if (Math.abs(priceDeviation) > 0.03) { // If price drifted more than 3%
        meanReversionForce = -priceDeviation * 0.3; // Pull back 30% of the way
      }
      
      // Small random noise (±1%) plus mean reversion
      const randomNoise = (random() - 0.5) * 0.02;
      stock.sentimentOffset = (randomNoise + meanReversionForce) * memeMultiplier;
      
      // Also dampen the transition effect during base building
      stock.shortReportTransitionEffect = (stock.shortReportTransitionEffect || 0) * 0.5;

      // Generate mid-base news occasionally
      if (stock.baseDays === 7) {
        news.push({
          headline: `${stock.symbol} trading in tight range as dust settles`,
          description: `Volume has contracted significantly. Analysts watching for breakout or breakdown.`,
          sentiment: 'neutral',
          relatedStock: stock.symbol,
          newsType: 'base_update',
          volumeIndicator: 'LOW (40% of normal)',
          baseRange: `$${stock.baseLowPrice.toFixed(2)} - $${stock.baseHighPrice.toFixed(2)}`,
          educationalNote: '🎯 ACTION: WAIT. Base forming - watch for breakout above or breakdown below this range.'
        });
      }
    }
  }

  // ===== RESOLUTION PHASE PROCESSING =====
  function processResolutionPhase(stock, memeMultiplier) {
    const news = getNews();

    if (stock.resolutionDirection === 'breakout') {
      // Recovery rally
      const recoveryStrength = 0.02 + random() * 0.02;
      stock.sentimentOffset = recoveryStrength * memeMultiplier;
      stock.shortReportTransitionEffect = recoveryStrength;
    } else {
      // Continued decline
      const declineStrength = -(0.02 + random() * 0.03);
      stock.sentimentOffset = declineStrength * memeMultiplier;
      stock.shortReportTransitionEffect = declineStrength;
    }

    if (stock.shortReportDaysLeft <= 0) {
      // Pattern complete
      const finalOutcome = stock.resolutionDirection === 'breakout' ? 'REVERSAL' : 'DECLINE CONFIRMED';
      const priceChange = ((stock.price - stock.preReportPrice) / stock.preReportPrice * 100).toFixed(1);
      const startPrice = stock.preReportPrice;
      const endPrice = stock.price;

      // Log BEFORE clearing state so we have access to preReportPrice
      console.log(`[SSR] ${getDate()}: ${stock.symbol} COMPLETE (${finalOutcome}) [$${endPrice.toFixed(2)} Δ${priceChange >= 0 ? '+' : ''}${priceChange}% from $${startPrice.toFixed(2)}]`);

      news.push({
        headline: `${stock.symbol} short report saga concludes: ${finalOutcome}`,
        description: stock.resolutionDirection === 'breakout'
          ? `Shares have recovered from the short attack, now ${priceChange}% from pre-report price. ` +
            `${stock.shortSeller.name}'s thesis appears discredited.`
          : `Shares remain depressed at ${priceChange}% from pre-report levels. ` +
            `${stock.shortSeller.name}'s allegations appear validated.`,
        sentiment: stock.resolutionDirection === 'breakout' ? 'positive' : 'negative',
        relatedStock: stock.symbol,
        newsType: 'short_report_resolution',
        finalOutcome: stock.resolutionDirection,
        educationalNote: stock.resolutionDirection === 'breakout'
          ? `🎯 ACTION: SELL NOW to lock in profits. The short attack pattern is COMPLETE - no more upside from this event. ` +
            `Next: Look for new opportunities elsewhere.`
          : `🎯 ACTION: SELL if holding, DO NOT BUY. The short seller was RIGHT - expect continued decline. ` +
            `Next: Wait 6+ months for true bottom, or move on to other stocks.`
      });

      // Clear state AFTER logging
      clearShortReportState(stock);
    }
  }

  // ========== NEWS GENERATION ==========
  // Brendel & Ryans (2021): Response types and their market interpretation
  function generateRebuttalNews(stock) {
    const news = getNews();
    
    const rebuttalDescriptions = {
      detailed: {
        headline: `${stock.symbol} issues DETAILED rebuttal citing specific documents`,
        description: `Company provides point-by-point response referencing "page 42 of the 10-K" and ` +
          `third-party verification. ${stock.auditorName} ${stock.auditorQuality === 'big4' ? 'reaffirms' : 'reviewing'} the books.`,
        sentiment: 'positive',
        educationalNote: '🎯 ACTION: PREPARE TO BUY. Data-driven rebuttal = 85% reversal setup. ' +
          'Wait for insider buying + base formation, then BUY!'
      },
      generic: {
        headline: `${stock.symbol} "categorically denies" allegations`,
        description: `Company uses opinion words: "baseless," "unfounded," "malicious short attack." ` +
          `No specific data provided to counter ${stock.shortSeller.name}'s claims.`,
        sentiment: 'negative',
        educationalNote: '🎯 ACTION: DO NOT BUY. Generic denial = RED FLAG (-14% avg). ' +
          'Opinion words without data = management has no defense. Avoid.'
      },
      investigation: {
        headline: `🚨 ${stock.symbol} launches INTERNAL INVESTIGATION into allegations`,
        description: `Company announces special committee to review ${stock.shortSeller.name}'s claims. ` +
          `This is NOT the same as a rebuttal - it confirms there is something to investigate.`,
        sentiment: 'very_negative',
        educationalNote: '🎯 ACTION: SELL IMMEDIATELY if holding. Internal investigation = -24% avg. ' +
          'High delisting risk. EXIT NOW and do not look back.'
      },
      none: {
        headline: stock.auditorQuality === 'big4' 
          ? `${stock.symbol} remains SILENT - Big 4 auditor ${stock.auditorName} unchanged`
          : `${stock.symbol} SILENT on allegations after ${CONSTANTS.DURATION.rebuttalWindow.max} days`,
        description: stock.auditorQuality === 'big4'
          ? `No official response, but ${stock.auditorName} (Big 4) has not resigned. ` +
            `Market interprets as "noise not worth acknowledging."`
          : `No company response to ${stock.shortSeller.name}'s report. Without Big 4 backing, ` +
            `silence may indicate inability to refute allegations.`,
        sentiment: stock.auditorQuality === 'big4' ? 'neutral' : 'very_negative',
        educationalNote: stock.auditorQuality === 'big4'
          ? '🎯 ACTION: WAIT AND WATCH. Big 4 silence = could go either way. Wait for more signals.'
          : '🎯 ACTION: SELL or AVOID. No Big 4 + no response = market assumes guilt. Exit.'
      }
    };

    const rebuttal = rebuttalDescriptions[stock.rebuttalQuality];
    
    news.push({
      headline: rebuttal.headline,
      description: rebuttal.description,
      sentiment: rebuttal.sentiment,
      relatedStock: stock.symbol,
      newsType: 'rebuttal',
      rebuttalQuality: stock.rebuttalQuality,
      auditorInfo: `Auditor: ${stock.auditorName} (${stock.auditorQuality === 'big4' ? 'Big 4' : 'Boutique'})`,
      educationalNote: rebuttal.educationalNote
    });
  }

  // ========== TUTORIAL HINTS ==========
  // Aligned with Gold Standard 85% Setup Criteria
  function getTutorialHint(newsItem) {
    if (!newsItem) return null;

    // Short report initial
    if (newsItem.isShortReport) {
      return {
        type: '🔴 SHORT SELLER ATTACK',
        description: newsItem.reportType === 'fraud'
          ? 'FRAUD allegations are extremely dangerous - only 10% of targets recover. DO NOT buy the dip! Wait for Gold Standard signals.'
          : 'VALUATION reports have ~40% reversal rate. Still risky, but watch for Gold Standard signals.',
        implication: 'Brendel & Ryans (2021): Only 31% of companies respond. Watch HOW they respond.',
        action: '⛔ DO NOT BUY. Wait for Gold Standard signals before entering.',
        timing: 'TIMING WINDOWS: Day 1-2 generic denial expected. Day 3-5 is Gold Standard for DATA rebuttal. After Day 7 with no response = bearish.',
        catalyst: '🏆 SSR Gold Standard: (1) DATA rebuttal within 5 days citing specific docs, (2) NO internal investigation, (3) Insider buying after rebuttal'
      };
    }

    // Short report updates (stabilization, generic denial, etc.)
    if (newsItem.newsType === 'short_report_update') {
      // Check if this is a generic denial
      if (newsItem.headline && newsItem.headline.includes('denies')) {
        return {
          type: '⚠️ GENERIC DENIAL - NOT A BUY SIGNAL',
          description: 'Company issued immediate denial using opinion words ("baseless", "categorically denies").',
          implication: 'Generic denials are RED FLAGS. 28% of firms respond this way, but it does NOT indicate truth.',
          action: '⛔ DO NOT BUY. This is NOT the Gold Standard. Wait for DATA rebuttal.',
          timing: 'Watch for Day 3-5: Does company provide POINT-BY-POINT data rebuttal?',
          catalyst: '❌ MISSING: Gold Standard requires DATA rebuttal citing specific documents (10-K pages, GPS logs, etc.)'
        };
      }
      // Stabilization news
      return {
        type: '📊 SHARES STABILIZING - WATCH FOR SIGNALS',
        description: 'Initial panic selling has subsided. Now waiting for company response.',
        implication: 'Stock is in "discovery" phase. Outcome depends on rebuttal quality.',
        action: '⏳ DO NOT BUY YET. Wait for: (1) Data rebuttal, (2) Insider buying, (3) Big 4 auditor statement.',
        timing: 'Day 1-2: Expect generic denial. Day 3-5: Gold Standard rebuttal window. Day 7+: No response = bearish.',
        catalyst: '🔍 WATCH FOR: Rebuttal quality is key. Only DATA rebuttals matter, not opinion words.'
      };
    }

    // Insider buying
    if (newsItem.isInsiderBuying) {
      return {
        type: '💰 INSIDER BUYING DETECTED',
        description: 'Executives buying with personal money (Code P) believe allegations are false.',
        implication: 'Strong reversal signal! Check for cluster buying (3+).',
        action: '⏳ Wait for data rebuttal or auditor confirmation.',
        timing: 'Need cluster buying (3+) for Gold Standard.',
        catalyst: '🎯 Insider piece of Gold Standard: Need Cluster (3+) Open Market Buys (Code P) with >10% wealth commitment'
      };
    }

    // Rebuttal
    if (newsItem.newsType === 'rebuttal') {
      const hints = {
        detailed: {
          type: '📋 DETAILED DATA REBUTTAL - GOLD STANDARD ✓',
          description: 'Company provided POINT-BY-POINT counter-evidence with DATA.',
          implication: 'This is a Gold Standard signal! Still wait for base confirmation.',
          action: '⏳ Wait for base formation and breakout.',
          timing: 'Base typically forms in 10-14 days.',
          catalyst: '🏆 GOLD STANDARD MET: Point-by-point data rebuttal addresses allegations directly with evidence'
        },
        generic: {
          type: '⚠️ WEAK REBUTTAL - NOT GOLD STANDARD',
          description: 'Generic denial without data is a RED FLAG.',
          implication: 'Does NOT meet Gold Standard. Stock likely to make new lows.',
          action: '⛔ DO NOT BUY. Wait for better signals.',
          timing: 'Watch for new lows in coming days.',
          catalyst: '❌ MISSING: Gold Standard requires DATA rebuttal addressing each allegation point-by-point'
        },
        none: {
          type: '🚨 NO REBUTTAL - DANGER',
          description: 'Company silence is extremely bearish.',
          implication: 'Cannot meet Gold Standard without rebuttal. 90%+ chance of permanent loss.',
          action: '⛔ STAY AWAY. Do not average down.',
          timing: 'Expect continued decline.',
          catalyst: '❌ FAILED: No rebuttal = cannot meet Gold Standard'
        }
      };
      return hints[newsItem.rebuttalQuality] || null;
    }

    // Auditor confirmation (new hint type)
    if (newsItem.newsType === 'auditor_confirmation') {
      const isBig4 = ['Deloitte', 'PwC', 'EY', 'KPMG'].includes(newsItem.auditorName);
      return {
        type: isBig4 ? '✅ BIG 4 AUDITOR CONFIRMS - GOLD STANDARD ✓' : '📋 AUDITOR CONFIRMS (non-Big 4)',
        description: isBig4 
          ? `${newsItem.auditorName} (Big 4) reaffirmed the books.`
          : `${newsItem.auditorName} confirmed books, but not a Big 4 firm.`,
        implication: isBig4 
          ? 'This is a GOLD STANDARD signal for SSR reversal!'
          : 'Partial confidence only - not a Big 4 firm.',
        action: isBig4 ? '📈 Consider buying on breakout.' : '⏳ Wait for additional signals.',
        timing: isBig4 ? 'Watch for base breakout.' : 'May need Big 4 confirmation.',
        catalyst: isBig4 
          ? '🏆 GOLD STANDARD MET: Big 4 Auditor (Deloitte/PwC/EY/KPMG) reaffirmation is strongest SSR signal'
          : '⚠️ PARTIAL: Gold Standard requires Big 4 Auditor. Non-Big 4 confirmation is weaker.'
      };
    }

    // Base pattern
    if (newsItem.newsType === 'base_update') {
      return {
        type: '📊 TWO-WEEK BASE FORMING',
        description: 'Price consolidating in tight range.',
        implication: 'Check: Has company issued data rebuttal? Big 4 auditor involved?',
        action: '⏳ Watch for breakout. Key signals: No new lows, Tight trading range.',
        timing: 'Base formation typically 10-14 days.',
        catalyst: '🔄 BASE FORMING: But Gold Standard also needs data rebuttal OR Big 4 auditor confirmation'
      };
    }

    // Breakout
    if (newsItem.newsType === 'breakout') {
      return {
        type: '📈 BREAKOUT CONFIRMED',
        description: 'High-volume breakout above base resistance.',
        implication: 'If Gold Standard signals present, this is a strong entry.',
        action: '📈 Consider BUYING if Gold Standard met.',
        timing: 'Enter now if signals confirmed.',
        catalyst: '✅ ENTRY POINT: Breakout + Gold Standard (data rebuttal/Big 4 auditor) = 85% success setup'
      };
    }

    // Breakdown
    if (newsItem.newsType === 'breakdown') {
      return {
        type: '📉 BASE FAILED - BREAKDOWN',
        description: 'Short seller thesis validated. Gold Standard signals were missing.',
        implication: 'Expect 50-80% permanent loss.',
        action: '⛔ DO NOT BUY. Cut losses if holding.',
        timing: 'Further decline expected.',
        catalyst: '📚 LESSON: Without Gold Standard (data rebuttal + Big 4 auditor), most SSR targets fail'
      };
    }

    // Resolution (saga concludes)
    if (newsItem.newsType === 'short_report_resolution') {
      if (newsItem.finalOutcome === 'breakout') {
        return {
          type: '✅ SHORT REPORT SAGA RESOLVED - REVERSAL',
          description: 'Company successfully defended against short attack. Gold Standard criteria were met.',
          implication: 'Stock has recovered - the dip was a buying opportunity for those who waited for confirmation.',
          action: '📚 Review what worked: Data rebuttal? Big 4 auditor? Insider buying?',
          timing: 'Pattern complete. Normal trading resumes.',
          catalyst: '🎓 LESSON: Patience + Gold Standard signals = successful SSR reversal trade'
        };
      } else {
        return {
          type: '❌ SHORT REPORT SAGA RESOLVED - DECLINE CONFIRMED',
          description: 'Short seller thesis validated. Allegations had merit.',
          implication: 'Those who "bought the dip" suffered permanent capital loss.',
          action: '📚 Review what was missing: No data rebuttal? No insider buying? Generic denial?',
          timing: 'Pattern complete. Damage is permanent.',
          catalyst: '🎓 LESSON: Without Gold Standard (data rebuttal + Big 4 auditor + insider buying), SSR targets rarely recover'
        };
      }
    }

    return null;
  }

  // ========== UTILITY FUNCTIONS ==========
  function clearShortReportState(stock) {
    stock.shortReportPhase = null;
    stock.shortReportDaysLeft = 0;
    stock.shortSeller = null;
    stock.reportType = null;
    stock.reportCrashMagnitude = 0;
    stock.preReportPrice = 0;
    stock.shortReportLow = 0;
    // DON'T reset shortReportTransitionEffect - it was set for this day's price move
    stock.insiderBuying = false;
    stock.insiderBuyingAmount = null;
    stock.insiderBuyingTitle = null;
    stock.rebuttalQuality = null;
    stock.auditorQuality = null;
    stock.auditorName = null;
    stock.reversalProbability = 0;
    stock.willReverse = false;
    stock.resolutionDirection = null;
    stock.baseDays = 0;
    stock.baseHighPrice = 0;
    stock.baseLowPrice = 0;
    stock.baseRangePercent = 0;
    stock.volatilityBoost = Math.max(0, (stock.volatilityBoost || 0) - 0.3);
  }

  function getPhaseInfo(stock) {
    if (!stock.shortReportPhase) return null;

    return {
      phase: stock.shortReportPhase,
      daysLeft: stock.shortReportDaysLeft,
      reportType: stock.reportType,
      shortSeller: stock.shortSeller?.name,
      insiderBuying: stock.insiderBuying,
      rebuttalQuality: stock.rebuttalQuality,
      auditorQuality: stock.auditorQuality,
      reversalProbability: stock.reversalProbability,
      baseDays: stock.baseDays,
      baseRange: stock.baseHighPrice && stock.baseLowPrice 
        ? `${stock.baseLowPrice.toFixed(2)} - ${stock.baseHighPrice.toFixed(2)}`
        : null
    };
  }

  // ========== PUBLIC API ==========
  return {
    init: init,
    CONSTANTS: CONSTANTS,
    
    // Main functions
    triggerShortReport: triggerShortReport,
    checkShortReportEvents: checkShortReportEvents,
    processShortReport: processShortReport,
    
    // Utility functions
    getTutorialHint: getTutorialHint,
    getPhaseInfo: getPhaseInfo,
    calculateReversalProbability: calculateReversalProbability,
    
    // Testing utilities
    _test: {
      clearShortReportState: clearShortReportState,
      processInitialCrashPhase: processInitialCrashPhase,
      processRebuttalPhase: processRebuttalPhase,
      processBaseBuildingPhase: processBaseBuildingPhase,
      processResolutionPhase: processResolutionPhase,
      generateRebuttalNews: generateRebuttalNews
    },
    
    // Reset for testing
    _reset: function() {
      deps = {
        stocks: null,
        todayNews: null,
        getMemeMultiplier: null,
        randomChoice: null,
        isEventTypeEnabled: null,
        random: Math.random
      };
    }
  };
})();

// ========== BACKWARDS COMPATIBILITY ==========
// Global functions for existing code
function triggerShortReport(stock, shortSeller) {
  return SSR.triggerShortReport(stock, shortSeller);
}

function checkShortReportEvents() {
  return SSR.checkShortReportEvents();
}

function processShortReport() {
  return SSR.processShortReport();
}

function getShortReportTutorialHint(newsItem) {
  return SSR.getTutorialHint(newsItem);
}

// Export for Node.js testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = SSR;
}
