// ===== SHORT SELLER REPORT SYSTEM (EMPIRICALLY-BASED) =====
// Based on academic research: Ljungqvist & Qin (2021), Wong & Zhao (2017), Putniņš (2024)
//
// EMPIRICAL FOUNDATIONS:
// - Activist short sellers are "informed" traders, not manipulators (2-5% manipulation rate)
// - Average -20% over 4 years for targeted companies (Ljungqvist & Qin)
// - Fraud allegations: ~10% reversal probability
// - Valuation-only reports: ~40% reversal probability
// - 13.6% average drop in first 3 days for severe misconduct allegations
// - Companies with Big 4 auditors have higher survival rates
//
// SIGNAL INTEGRATION:
// - Insider buying signals from InsiderTrading module (Lakonishok & Lee 2001)
// - Cluster buying (3+ insiders) has 2x power (Hjort & Bapkas 2024)
// - Insider SELLING is NOISE - not used as signal
//
// KEY DETECTABLE SIGNALS (for educational gameplay):
// 1. Report Type: Fraud vs Valuation (binary, massive impact on outcome)
// 2. Insider Buying: Detected via InsiderTrading module (strong reversal signal)
// 3. Cluster Buying: 3+ insiders = strongest signal
// 4. Rebuttal Quality: Detailed vs Generic denial
// 5. Auditor Quality: Big 4 vs Boutique
// 6. Two-Week Base: 10-14 day consolidation pattern
//
// EDUCATIONAL PURPOSE:
// Teaches players fundamental analysis skills:
// - Distinguishing fraud from overvaluation
// - Reading insider behavior signals
// - Understanding auditor credibility
// - Patience (waiting for base formation)
// - Risk assessment (different from technical DCB analysis)
//
// ARCHITECTURE:
// This module uses dependency injection for testability.

const SSR = (function() {
  'use strict';

  // ========== EMPIRICALLY-BASED CONSTANTS ==========
  const CONSTANTS = {
    // ========== GOLD STANDARD 85% SETUP ==========
    // The highest probability SSR reversal requires ONE of these criteria
    GOLD_STANDARD: {
      description: 'Point-by-point DATA rebuttal OR Big 4 Auditor reaffirms books',
      requirements: {
        dataRebuttal: true,          // Company must provide DATA, not generic denial
        pointByPoint: true,          // Must address EACH allegation specifically
        big4Auditor: ['Deloitte', 'PwC', 'EY', 'KPMG'], // Big 4 firms only
        auditorAction: 'reaffirm',   // Auditor must REAFFIRM the books
        successRate: 0.85            // 85% success when criteria met
      },
      educationalNote: 'Generic denials are RED FLAGS. Only data-driven rebuttals or Big 4 auditor support matter.'
    },
    
    // Report type determines outcome probability
    REPORT_TYPES: {
      fraud: {
        probability: 0.40,           // 40% of reports allege fraud
        reversalChance: 0.10,        // Only 10% reverse (very dangerous)
        initialDrop: { min: 0.20, max: 0.35 },  // 20-35% initial drop
        longTermDecline: { min: 0.50, max: 0.80 },  // 50-80% permanent loss if true
        description: 'alleges accounting fraud or fake revenue'
      },
      valuation: {
        probability: 0.60,           // 60% are valuation-based
        reversalChance: 0.40,        // 40% reverse at fair value
        initialDrop: { min: 0.15, max: 0.25 },  // 15-25% initial drop
        fairValueDiscount: { min: 0.20, max: 0.35 },  // Settles at 20-35% below peak
        description: 'claims stock is overvalued'
      }
    },

    // Insider buying signals (from InsiderTrading module - Lakonishok & Lee 2001)
    // NOTE: Actual insider events generated by InsiderTrading module
    // These constants define how SSR responds to those signals
    INSIDER_BUYING: {
      reversalBoost: 0.30,           // +30% to reversal probability for insider buy
      clusterBoost: 0.15,            // +15% additional for cluster buying (3+ insiders)
      // Legacy fields for backward compatibility (events now from InsiderTrading module)
      probability: 0.25,             // Probability InsiderTrading generates buy during SSR
      amounts: ['$500K', '$1M', '$2M', '$5M'],
      titles: ['CEO', 'CFO', 'Chairman', 'Director']
    },

    // Auditor quality (Big 4 vs boutique)
    AUDITOR: {
      big4: {
        probability: 0.45,           // 45% have Big 4 auditors
        reversalBoost: 0.15,         // +15% to reversal probability
        names: ['PwC', 'Deloitte', 'EY', 'KPMG']
      },
      boutique: {
        probability: 0.55,           // 55% have smaller auditors
        reversalPenalty: 0.10,       // -10% from reversal probability
        names: ['Local CPA', 'Regional Firm', 'Offshore Auditor']
      }
    },

    // Company rebuttal quality
    REBUTTAL: {
      detailed: {
        probability: 0.30,           // 30% provide detailed rebuttals
        reversalBoost: 0.10,         // +10% to reversal probability
        description: 'point-by-point rebuttal with supporting data'
      },
      generic: {
        probability: 0.50,           // 50% give generic denials
        reversalPenalty: 0.05,       // -5% from reversal probability
        description: 'denies all allegations without specifics'
      },
      none: {
        probability: 0.20,           // 20% don't respond
        reversalPenalty: 0.15,       // -15% from reversal probability
        description: 'no response from company'
      }
    },

    // Two-week base pattern (technical confirmation)
    BASE_PATTERN: {
      minDays: 10,                   // Minimum 10 days
      maxDays: 14,                   // Maximum 14 days
      breakoutProbability: 0.60,     // 60% breakout if base forms properly
      volumeContraction: 0.4         // Volume drops to 40% of crash volume
    },

    // Duration for various phases (in days)
    DURATION: {
      initialCrash: { min: 2, max: 4 },      // 2-4 days of selling
      rebuttalWindow: { min: 3, max: 5 },    // 3-5 days for company response
      baseBuilding: { min: 10, max: 14 },    // 10-14 day consolidation
      resolution: { min: 5, max: 10 }        // 5-10 days for breakout/breakdown
    },

    // Volume patterns
    VOLUME: {
      reportDay: 5.0,                // 500% volume on report day
      panic: 3.0,                    // 300% during panic selling
      baseBuilding: 0.4,             // 40% during consolidation
      breakout: 2.0,                 // 200% on breakout
      breakdown: 2.5                 // 250% on breakdown
    },

    // Short seller firms (for news generation)
    SHORT_SELLERS: [
      { name: 'Hindenburg Research', reputation: 'high', specialty: 'fraud' },
      { name: 'Muddy Waters', reputation: 'high', specialty: 'fraud' },
      { name: 'Citron Research', reputation: 'medium', specialty: 'valuation' },
      { name: 'Wolfpack Research', reputation: 'medium', specialty: 'fraud' },
      { name: 'Spruce Point', reputation: 'medium', specialty: 'valuation' },
      { name: 'Grizzly Research', reputation: 'low', specialty: 'valuation' }
    ]
  };

  // ========== DEPENDENCIES (INJECTED) ==========
  let deps = {
    stocks: null,
    todayNews: null,
    getMemeMultiplier: null,
    randomChoice: null,
    isEventTypeEnabled: null,
    random: Math.random
  };

  // ========== INITIALIZATION ==========
  function init(dependencies) {
    if (dependencies.stocks !== undefined) deps.stocks = dependencies.stocks;
    if (dependencies.todayNews !== undefined) deps.todayNews = dependencies.todayNews;
    if (dependencies.getMemeMultiplier !== undefined) deps.getMemeMultiplier = dependencies.getMemeMultiplier;
    if (dependencies.randomChoice !== undefined) deps.randomChoice = dependencies.randomChoice;
    if (dependencies.isEventTypeEnabled !== undefined) deps.isEventTypeEnabled = dependencies.isEventTypeEnabled;
    if (dependencies.random !== undefined) deps.random = dependencies.random;

    return SSR;
  }

  // ========== HELPER FUNCTIONS ==========
  function getStocks() {
    return deps.stocks || (typeof stocks !== 'undefined' ? stocks : []);
  }

  function getNews() {
    return deps.todayNews || (typeof todayNews !== 'undefined' ? todayNews : []);
  }

  function getMemeMultiplier(stock) {
    if (deps.getMemeMultiplier) return deps.getMemeMultiplier(stock);
    if (typeof window !== 'undefined' && typeof window.getMemeMultiplier === 'function') {
      return window.getMemeMultiplier(stock);
    }
    return (stock.isMeme || stock.volatility > 0.05) ? 1.5 : 1.0;
  }

  function randomChoice(arr) {
    if (deps.randomChoice) return deps.randomChoice(arr);
    if (typeof window !== 'undefined' && typeof window.randomChoice === 'function') {
      return window.randomChoice(arr);
    }
    return arr[Math.floor(deps.random() * arr.length)];
  }

  function isEventTypeEnabled(eventType) {
    if (deps.isEventTypeEnabled) return deps.isEventTypeEnabled(eventType);
    if (typeof window !== 'undefined' && typeof window.isEventTypeEnabled === 'function') {
      return window.isEventTypeEnabled(eventType);
    }
    return true;
  }

  function random() {
    return deps.random();
  }

  // ========== CALCULATE REVERSAL PROBABILITY ==========
  // Combines all signals into a final reversal probability
  function calculateReversalProbability(stock, verbose = true) {
    const baseReversalChance = stock.reportType === 'fraud' 
      ? CONSTANTS.REPORT_TYPES.fraud.reversalChance 
      : CONSTANTS.REPORT_TYPES.valuation.reversalChance;
    
    let runningProb = baseReversalChance;
    
    // Build calculation breakdown for logging
    const breakdown = [];
    breakdown.push(`  Base (${stock.reportType}): ${(baseReversalChance * 100).toFixed(0)}%`);
    
    // Insider buying - now checked via InsiderBuying module (separate from InsiderSelling)
    // Uses module if available, falls back to stock.insiderBuying flag
    const insiderBoost = (typeof InsiderBuying !== 'undefined' && InsiderBuying.getInsiderBoost)
      ? InsiderBuying.getInsiderBoost(stock)
      : { hasBuySignal: stock.insiderBuying || false, isClusterBuy: false, buyCount: 0 };
    
    if (insiderBoost.isClusterBuy) {
      // Cluster buying = strongest signal (Hjort & Bapkas 2024)
      const boost = CONSTANTS.INSIDER_BUYING.reversalBoost + CONSTANTS.INSIDER_BUYING.clusterBoost;
      runningProb += boost;
      breakdown.push(`  + CLUSTER Insider Buying (${insiderBoost.buyCount} insiders): +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else if (insiderBoost.hasBuySignal || stock.insiderBuying) {
      const boost = CONSTANTS.INSIDER_BUYING.reversalBoost;
      runningProb += boost;
      const details = stock.insiderBuyingTitle && stock.insiderBuyingAmount 
        ? `(${stock.insiderBuyingTitle} ${stock.insiderBuyingAmount})` 
        : `(${insiderBoost.buyCount || 1} insider${insiderBoost.buyCount > 1 ? 's' : ''})`;
      breakdown.push(`  + Insider Buying ${details}: +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else {
      breakdown.push(`  + Insider Buying: NONE (+0%)`);
    }
    
    // Auditor quality
    if (stock.auditorQuality === 'big4') {
      const boost = CONSTANTS.AUDITOR.big4.reversalBoost;
      runningProb += boost;
      breakdown.push(`  + Auditor (${stock.auditorName} - Big 4): +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else {
      const penalty = CONSTANTS.AUDITOR.boutique.reversalPenalty;
      runningProb -= penalty;
      breakdown.push(`  + Auditor (${stock.auditorName} - Boutique): -${(penalty * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    }
    
    // Rebuttal quality
    if (stock.rebuttalQuality === 'detailed') {
      const boost = CONSTANTS.REBUTTAL.detailed.reversalBoost;
      runningProb += boost;
      breakdown.push(`  + Rebuttal (DETAILED): +${(boost * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else if (stock.rebuttalQuality === 'generic') {
      const penalty = CONSTANTS.REBUTTAL.generic.reversalPenalty;
      runningProb -= penalty;
      breakdown.push(`  + Rebuttal (GENERIC): -${(penalty * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    } else if (stock.rebuttalQuality === 'none') {
      const penalty = CONSTANTS.REBUTTAL.none.reversalPenalty;
      runningProb -= penalty;
      breakdown.push(`  + Rebuttal (NONE): -${(penalty * 100).toFixed(0)}% → ${(runningProb * 100).toFixed(0)}%`);
    }
    
    // Clamp between 0.05 and 0.75
    const finalProb = Math.max(0.05, Math.min(0.75, runningProb));
    
    if (runningProb !== finalProb) {
      breakdown.push(`  CLAMPED: ${(runningProb * 100).toFixed(0)}% → ${(finalProb * 100).toFixed(0)}% (range: 5%-75%)`);
    }
    
    breakdown.push(`  ═══════════════════════════`);
    breakdown.push(`  FINAL REVERSAL PROBABILITY: ${(finalProb * 100).toFixed(0)}%`);
    
    // Log the breakdown
    if (verbose) {
      console.log(`[SSR] ${stock.symbol} Reversal Probability Calculation:`);
      breakdown.forEach(line => console.log(line));
    }
    
    return finalProb;
  }

  // ========== TRIGGER SHORT REPORT ==========
  function triggerShortReport(stock, shortSeller = null) {
    if (stock.shortReportPhase || stock.crashPhase) return false;

    const memeMultiplier = getMemeMultiplier(stock);

    // Select short seller
    const seller = shortSeller || randomChoice(CONSTANTS.SHORT_SELLERS);
    stock.shortSeller = seller;

    // Determine report type (fraud vs valuation)
    const isFraud = random() < CONSTANTS.REPORT_TYPES.fraud.probability;
    stock.reportType = isFraud ? 'fraud' : 'valuation';
    const reportConfig = CONSTANTS.REPORT_TYPES[stock.reportType];

    // Determine auditor quality
    stock.auditorQuality = random() < CONSTANTS.AUDITOR.big4.probability ? 'big4' : 'boutique';
    stock.auditorName = stock.auditorQuality === 'big4' 
      ? randomChoice(CONSTANTS.AUDITOR.big4.names)
      : randomChoice(CONSTANTS.AUDITOR.boutique.names);

    // Calculate initial crash magnitude
    const crashMagnitude = reportConfig.initialDrop.min + 
      random() * (reportConfig.initialDrop.max - reportConfig.initialDrop.min);

    // Store pre-crash state
    stock.preReportPrice = stock.price;
    stock.reportCrashMagnitude = crashMagnitude;
    stock.shortReportPhase = 'initial_crash';
    stock.shortReportDaysLeft = CONSTANTS.DURATION.initialCrash.min + 
      Math.floor(random() * (CONSTANTS.DURATION.initialCrash.max - CONSTANTS.DURATION.initialCrash.min + 1));

    // These will be determined later
    stock.insiderBuying = false;
    stock.insiderBuyingAmount = null;
    stock.insiderBuyingTitle = null;
    stock.rebuttalQuality = null;
    stock.baseDays = 0;
    stock.baseHighPrice = 0;
    stock.baseLowPrice = Infinity;

    // Volume spike on report
    stock.volumeMultiplier = CONSTANTS.VOLUME.reportDay;
    stock.volumeTrend = 'spike';

    // Apply immediate crash impact
    stock.sentimentOffset = -(crashMagnitude * 0.7) * memeMultiplier;
    stock.volatilityBoost = (stock.volatilityBoost || 0) + 0.6 * memeMultiplier;
    stock.shortReportTransitionEffect = -(crashMagnitude * 0.5 + random() * crashMagnitude * 0.2);

    console.log(`[SSR] Short report triggered for ${stock.symbol} by ${seller.name}: ${stock.reportType.toUpperCase()}`);

    return true;
  }

  // ========== CHECK FOR NEW SHORT REPORTS ==========
  function checkShortReportEvents() {
    const stockList = getStocks();
    const news = getNews();

    // Very rare event: 0.5% per stock per day
    stockList.forEach(stock => {
      if (!stock.shortReportPhase && !stock.crashPhase && random() < 0.005) {
        const seller = randomChoice(CONSTANTS.SHORT_SELLERS);

        triggerShortReport(stock, seller);

        // Generate initial report news
        const reportTypeDesc = CONSTANTS.REPORT_TYPES[stock.reportType].description;
        
        // Empirical NLP: "Hard Information" with specific accounting terms (Loughran & McDonald 2011)
        // Keywords: "Exposed," "Phantom," "Fabricated," "Investigation," "Whistleblower," "Audit"
        const fraudHeadlines = [
          `🔴 ${seller.name}: "${stock.symbol} Fabricated 40% of Reported Revenue"`,
          `🔴 ${seller.name} EXPOSES ${stock.symbol}: "Phantom Inventory, Fake Invoices"`,
          `🔴 WHISTLEBLOWER: ${seller.name} Report on ${stock.symbol} Cites Internal Documents`
        ];
        const valuationHeadlines = [
          `🔴 ${seller.name}: "${stock.symbol} Worth 70% Less" - Detailed Analysis`,
          `🔴 ${seller.name} TARGETS ${stock.symbol}: "Massively Overvalued" - Price Target $0`
        ];
        const headline = stock.reportType === 'fraud'
          ? fraudHeadlines[Math.floor(Math.random() * fraudHeadlines.length)]
          : valuationHeadlines[Math.floor(Math.random() * valuationHeadlines.length)];
        
        news.push({
          headline: headline,
          description: `Activist short seller ${seller.name} releases damaging report that ${reportTypeDesc}. ` +
            `Stock halted briefly as trading volume explodes.`,
          sentiment: 'very_negative',
          relatedStock: stock.symbol,
          newsType: 'short_report',
          isShortReport: true,
          // Educational data
          reportType: stock.reportType,
          volumeIndicator: 'EXTREME (5x normal)',
          auditorInfo: `Auditor: ${stock.auditorName}`,
          educationalNote: stock.reportType === 'fraud' 
            ? '⚠️ FRAUD allegations are serious - only 10% of these reverse. Wait for insider response!'
            : '📊 VALUATION reports have ~40% reversal rate. Watch for insider buying and fair value support.'
        });
      }
    });
  }

  // ========== MAIN PROCESSING FUNCTION ==========
  function processShortReport() {
    const stockList = getStocks();

    stockList.forEach(stock => {
      if (!stock.shortReportPhase) return;

      if (!isEventTypeEnabled('short_report')) {
        clearShortReportState(stock);
        return;
      }

      const memeMultiplier = getMemeMultiplier(stock);

      // Apply pending transition effects
      if (stock.pendingTransitionEffect) {
        stock.shortReportTransitionEffect = stock.pendingTransitionEffect;
        stock.pendingTransitionEffect = 0;
      }

      stock.shortReportDaysLeft--;

      // Route to appropriate phase handler
      switch (stock.shortReportPhase) {
        case 'initial_crash':
          processInitialCrashPhase(stock, memeMultiplier);
          break;
        case 'rebuttal_window':
          processRebuttalPhase(stock, memeMultiplier);
          break;
        case 'base_building':
          processBaseBuildingPhase(stock, memeMultiplier);
          break;
        case 'resolution':
          processResolutionPhase(stock, memeMultiplier);
          break;
      }
    });
  }

  // ===== INITIAL CRASH PHASE PROCESSING =====
  function processInitialCrashPhase(stock, memeMultiplier) {
    const news = getNews();

    if (stock.shortReportDaysLeft <= 0) {
      // Record the initial crash low
      stock.shortReportLow = stock.price;

      // Transition to rebuttal window
      stock.shortReportPhase = 'rebuttal_window';
      stock.shortReportDaysLeft = CONSTANTS.DURATION.rebuttalWindow.min + 
        Math.floor(random() * (CONSTANTS.DURATION.rebuttalWindow.max - CONSTANTS.DURATION.rebuttalWindow.min + 1));

      // Decrease volume but stay elevated
      stock.volumeMultiplier = CONSTANTS.VOLUME.panic;
      stock.volumeTrend = 'elevated';

      // Determine if insiders will buy (KEY SIGNAL)
      if (random() < CONSTANTS.INSIDER_BUYING.probability) {
        stock.insiderBuying = true;
        stock.insiderBuyingAmount = randomChoice(CONSTANTS.INSIDER_BUYING.amounts);
        stock.insiderBuyingTitle = randomChoice(CONSTANTS.INSIDER_BUYING.titles);
        stock.insiderBuyingDay = 1 + Math.floor(random() * stock.shortReportDaysLeft);
      }

      console.log(`[SSR] ${stock.symbol} entering REBUTTAL WINDOW (insider buying: ${stock.insiderBuying})`);
      
      // Generate news
      news.push({
        headline: `${stock.symbol} shares stabilize after ${(stock.reportCrashMagnitude * 100).toFixed(0)}% plunge`,
        description: `Trading remains volatile as investors await company response to ${stock.shortSeller.name}'s allegations.`,
        sentiment: 'negative',
        relatedStock: stock.symbol,
        newsType: 'short_report_update',
        volumeIndicator: 'HIGH (3x normal)',
        educationalNote: 'Watch for: 1) Company rebuttal quality, 2) Insider buying, 3) Auditor statement'
      });
    } else {
      // Continue crash
      stock.sentimentOffset = -(0.08 + random() * 0.06) * memeMultiplier;
    }
  }

  // ===== REBUTTAL PHASE PROCESSING =====
  function processRebuttalPhase(stock, memeMultiplier) {
    const news = getNews();
    const daysInPhase = (CONSTANTS.DURATION.rebuttalWindow.max - stock.shortReportDaysLeft);

    // Check for insider buying event
    if (stock.insiderBuying && daysInPhase === stock.insiderBuyingDay) {
      news.push({
        headline: `💰 ${stock.symbol} ${stock.insiderBuyingTitle} BUYS ${stock.insiderBuyingAmount} in shares`,
        description: `Company insider makes significant personal investment following short attack. ` +
          `This is a major bullish signal - insiders rarely buy with personal money unless confident.`,
        sentiment: 'positive',
        relatedStock: stock.symbol,
        newsType: 'insider_buying',
        isInsiderBuying: true,
        volumeIndicator: 'MODERATE',
        educationalNote: '✅ BULLISH SIGNAL: Insider buying $1M+ suggests allegations may be exaggerated or false.'
      });

      // Modest positive effect
      stock.pendingTransitionEffect = 0.03 + random() * 0.02;
    }

    // On last day of rebuttal window, determine rebuttal quality
    if (stock.shortReportDaysLeft <= 0) {
      // Determine rebuttal quality
      const rebuttalRoll = random();
      if (rebuttalRoll < CONSTANTS.REBUTTAL.detailed.probability) {
        stock.rebuttalQuality = 'detailed';
      } else if (rebuttalRoll < CONSTANTS.REBUTTAL.detailed.probability + CONSTANTS.REBUTTAL.generic.probability) {
        stock.rebuttalQuality = 'generic';
      } else {
        stock.rebuttalQuality = 'none';
      }

      // Generate rebuttal news
      generateRebuttalNews(stock);

      // Calculate final reversal probability
      stock.reversalProbability = calculateReversalProbability(stock);

      // Determine actual outcome based on probability
      stock.willReverse = random() < stock.reversalProbability;

      // Transition to base building phase
      stock.shortReportPhase = 'base_building';
      stock.shortReportDaysLeft = CONSTANTS.DURATION.baseBuilding.min + 
        Math.floor(random() * (CONSTANTS.DURATION.baseBuilding.max - CONSTANTS.DURATION.baseBuilding.min + 1));
      stock.baseDays = 0;
      stock.baseHighPrice = stock.price;
      stock.baseLowPrice = stock.price;
      stock.baseAnchorPrice = stock.price; // Anchor for mean reversion during base

      // Volume contracts during base building - KEY for tight range
      stock.volumeMultiplier = CONSTANTS.VOLUME.baseBuilding;
      stock.volumeTrend = 'contracting';
      
      // CRITICAL: Reduce volatility significantly during base building
      // This is what creates the "tight range" consolidation pattern
      stock.volatilityBoost = Math.max(0, (stock.volatilityBoost || 0) * 0.3);

      console.log(`[SSR] ${stock.symbol} entering BASE BUILDING (reversal prob: ${(stock.reversalProbability * 100).toFixed(0)}%, will reverse: ${stock.willReverse})`);
    } else {
      // Volatile trading during rebuttal phase
      stock.sentimentOffset = (random() - 0.55) * 0.04 * memeMultiplier;
    }
  }

  // ===== BASE BUILDING PHASE PROCESSING =====
  function processBaseBuildingPhase(stock, memeMultiplier) {
    const news = getNews();
    
    // Track the base range
    stock.baseDays++;
    stock.baseHighPrice = Math.max(stock.baseHighPrice, stock.price);
    stock.baseLowPrice = Math.min(stock.baseLowPrice, stock.price);

    // Calculate range tightness (volatility contraction)
    const rangePercent = stock.baseHighPrice > 0 
      ? (stock.baseHighPrice - stock.baseLowPrice) / stock.baseHighPrice 
      : 0;
    stock.baseRangePercent = rangePercent;

    // Is the base forming properly? (range < 15% and enough days)
    // Loosened from 10% to 15% to account for normal volatility
    const isValidBase = rangePercent < 0.15 && stock.baseDays >= CONSTANTS.BASE_PATTERN.minDays;

    if (stock.shortReportDaysLeft <= 0) {
      // Time to resolve - breakout or breakdown
      stock.shortReportPhase = 'resolution';
      stock.shortReportDaysLeft = CONSTANTS.DURATION.resolution.min + 
        Math.floor(random() * (CONSTANTS.DURATION.resolution.max - CONSTANTS.DURATION.resolution.min + 1));

      // Log base validation for debugging
      console.log(`[SSR] ${stock.symbol} Base Analysis:`);
      console.log(`  Base Days: ${stock.baseDays} (min required: ${CONSTANTS.BASE_PATTERN.minDays})`);
      console.log(`  Range: $${stock.baseLowPrice.toFixed(2)} - $${stock.baseHighPrice.toFixed(2)}`);
      console.log(`  Range %: ${(rangePercent * 100).toFixed(1)}% (max for valid: 15%)`);
      console.log(`  Is Valid Base: ${isValidBase}`);
      console.log(`  Will Reverse (from probability): ${stock.willReverse}`);

      // Determine direction: 
      // - If willReverse is true AND base is valid = high confidence breakout
      // - If willReverse is true BUT base invalid = still breakout but weaker (empirical prob won)
      // - If willReverse is false = breakdown regardless of base quality
      if (stock.willReverse) {
        stock.resolutionDirection = 'breakout';
        stock.volumeMultiplier = CONSTANTS.VOLUME.breakout;
        stock.volumeTrend = 'increasing';
        
        const confidence = isValidBase ? 'HIGH-PROBABILITY' : 'MODERATE';
        news.push({
          headline: `📈 ${stock.symbol} BREAKS OUT above resistance on high volume`,
          description: `After ${stock.baseDays} days of consolidation, shares surge above the base high of $${stock.baseHighPrice.toFixed(2)}. ` +
            `Volume confirms institutional buying.${isValidBase ? '' : ' Base was volatile but buying pressure won out.'}`,
          sentiment: 'positive',
          relatedStock: stock.symbol,
          newsType: 'breakout',
          volumeIndicator: 'HIGH (2x normal)',
          educationalNote: `✅ ${confidence} ENTRY: ${isValidBase ? '14-day tight base + ' : ''}High-volume breakout${isValidBase ? ' = 60%+ success rate.' : '.'}`
        });
      } else {
        stock.resolutionDirection = 'breakdown';
        stock.volumeMultiplier = CONSTANTS.VOLUME.breakdown;
        stock.volumeTrend = 'increasing';
        
        news.push({
          headline: `📉 ${stock.symbol} BREAKS DOWN below support, new lows likely`,
          description: `Base pattern fails as shares crash through $${stock.baseLowPrice.toFixed(2)} support. ` +
            `Short seller's thesis appears validated.`,
          sentiment: 'very_negative',
          relatedStock: stock.symbol,
          newsType: 'breakdown',
          volumeIndicator: 'HIGH (2.5x normal)',
          educationalNote: '⚠️ BASE FAILURE: Reversal probability was too low based on signals.'
        });
      }

      console.log(`[SSR] ${stock.symbol} entering RESOLUTION (${stock.resolutionDirection})`);
    } else {
      // During base building - tight range, low volume
      // TIGHT RANGE consolidation - mean reversion to anchor price
      // This creates the "two-week base" pattern empirically observed
      const anchorPrice = stock.baseAnchorPrice || stock.price;
      const priceDeviation = (stock.price - anchorPrice) / anchorPrice;
      
      // Mean reversion: pull price back toward anchor if it drifts too far
      // This simulates the "absorption of selling pressure" mentioned in research
      let meanReversionForce = 0;
      if (Math.abs(priceDeviation) > 0.03) { // If price drifted more than 3%
        meanReversionForce = -priceDeviation * 0.3; // Pull back 30% of the way
      }
      
      // Small random noise (±1%) plus mean reversion
      const randomNoise = (random() - 0.5) * 0.02;
      stock.sentimentOffset = (randomNoise + meanReversionForce) * memeMultiplier;
      
      // Also dampen the transition effect during base building
      stock.shortReportTransitionEffect = (stock.shortReportTransitionEffect || 0) * 0.5;

      // Generate mid-base news occasionally
      if (stock.baseDays === 7) {
        news.push({
          headline: `${stock.symbol} trading in tight range as dust settles`,
          description: `Volume has contracted significantly. Analysts watching for breakout or breakdown.`,
          sentiment: 'neutral',
          relatedStock: stock.symbol,
          newsType: 'base_update',
          volumeIndicator: 'LOW (40% of normal)',
          baseRange: `$${stock.baseLowPrice.toFixed(2)} - $${stock.baseHighPrice.toFixed(2)}`,
          educationalNote: 'The "Two-Week Base" pattern: 10-14 days of tight range = absorption of selling pressure.'
        });
      }
    }
  }

  // ===== RESOLUTION PHASE PROCESSING =====
  function processResolutionPhase(stock, memeMultiplier) {
    const news = getNews();

    if (stock.resolutionDirection === 'breakout') {
      // Recovery rally
      const recoveryStrength = 0.02 + random() * 0.02;
      stock.sentimentOffset = recoveryStrength * memeMultiplier;
      stock.shortReportTransitionEffect = recoveryStrength;
    } else {
      // Continued decline
      const declineStrength = -(0.02 + random() * 0.03);
      stock.sentimentOffset = declineStrength * memeMultiplier;
      stock.shortReportTransitionEffect = declineStrength;
    }

    if (stock.shortReportDaysLeft <= 0) {
      // Pattern complete
      const finalOutcome = stock.resolutionDirection === 'breakout' ? 'REVERSAL' : 'DECLINE CONFIRMED';
      const priceChange = ((stock.price - stock.preReportPrice) / stock.preReportPrice * 100).toFixed(1);

      news.push({
        headline: `${stock.symbol} short report saga concludes: ${finalOutcome}`,
        description: stock.resolutionDirection === 'breakout'
          ? `Shares have recovered from the short attack, now ${priceChange}% from pre-report price. ` +
            `${stock.shortSeller.name}'s thesis appears discredited.`
          : `Shares remain depressed at ${priceChange}% from pre-report levels. ` +
            `${stock.shortSeller.name}'s allegations appear validated.`,
        sentiment: stock.resolutionDirection === 'breakout' ? 'positive' : 'negative',
        relatedStock: stock.symbol,
        newsType: 'short_report_resolution',
        finalOutcome: stock.resolutionDirection,
        educationalNote: stock.resolutionDirection === 'breakout'
          ? '📚 Key lesson: Patience + insider signals + base formation = safer entry.'
          : '📚 Key lesson: Fraud allegations + no insider buying + weak rebuttal = stay away.'
      });

      // Clear state
      clearShortReportState(stock);
      console.log(`[SSR] ${stock.symbol} pattern COMPLETE (${finalOutcome})`);
    }
  }

  // ========== NEWS GENERATION ==========
  function generateRebuttalNews(stock) {
    const news = getNews();
    
    const rebuttalDescriptions = {
      detailed: {
        headline: `${stock.symbol} issues DETAILED rebuttal with supporting evidence`,
        description: `Company provides point-by-point response to ${stock.shortSeller.name}'s allegations with auditor confirmation and third-party data.`,
        sentiment: 'neutral',
        educationalNote: '✅ BULLISH: Detailed rebuttals with data suggest allegations may be exaggerated.'
      },
      generic: {
        headline: `${stock.symbol} DENIES allegations in brief statement`,
        description: `Company issues generic denial: "We categorically deny all allegations and stand by our accounting practices."`,
        sentiment: 'negative',
        educationalNote: '⚠️ BEARISH: Generic denials without specifics often precede new lows.'
      },
      none: {
        headline: `${stock.symbol} SILENT on short seller allegations`,
        description: `No official company response to ${stock.shortSeller.name}'s report after ${CONSTANTS.DURATION.rebuttalWindow.max} days.`,
        sentiment: 'very_negative',
        educationalNote: '🚨 VERY BEARISH: Silence often indicates company cannot refute allegations.'
      }
    };

    const rebuttal = rebuttalDescriptions[stock.rebuttalQuality];
    
    news.push({
      headline: rebuttal.headline,
      description: rebuttal.description,
      sentiment: rebuttal.sentiment,
      relatedStock: stock.symbol,
      newsType: 'rebuttal',
      rebuttalQuality: stock.rebuttalQuality,
      auditorInfo: `Auditor: ${stock.auditorName} (${stock.auditorQuality === 'big4' ? 'Big 4' : 'Boutique'})`,
      educationalNote: rebuttal.educationalNote
    });
  }

  // ========== TUTORIAL HINTS ==========
  // Aligned with Gold Standard 85% Setup Criteria
  function getTutorialHint(newsItem) {
    if (!newsItem) return null;

    // Short report initial
    if (newsItem.isShortReport) {
      return {
        title: '🔴 SHORT SELLER ATTACK',
        message: newsItem.reportType === 'fraud'
          ? 'FRAUD allegations are extremely dangerous - only 10% of targets recover. DO NOT buy the dip! Wait for Gold Standard signals.'
          : 'VALUATION reports have ~40% reversal rate. Still risky, but watch for Gold Standard signals.',
        severity: 'high',
        keySignals: ['Point-by-point data rebuttal', 'Big 4 Auditor reaffirmation', 'Insider cluster buying', 'VIX decreasing'],
        goldStandard: '🏆 SSR Gold Standard: Point-by-point DATA rebuttal OR Big 4 Auditor (Deloitte/PwC/EY/KPMG) reaffirms books',
        nlpHint: '📰 HARD INFO KEYWORDS (permanent damage): "Exposed," "Phantom," "Fabricated," "Whistleblower," "Investigation," "Audit." ' +
          'Loughran & McDonald (2011): Reports with specific % claims and accounting terms = 90% NO REVERSAL. ' +
          'Wait for DATA rebuttal, not generic denial!'
      };
    }

    // Insider buying
    if (newsItem.isInsiderBuying) {
      return {
        title: '💰 INSIDER BUYING DETECTED',
        message: 'Strong reversal signal! Executives buying with personal money (Code P) believe allegations are false. Check for cluster buying (3+).',
        severity: 'medium',
        keySignals: ['Wait for data rebuttal or auditor confirmation', 'Need cluster buying (3+) for Gold Standard'],
        goldStandard: '🎯 Insider piece of Gold Standard: Need Cluster (3+) Open Market Buys (Code P) with >10% wealth commitment'
      };
    }

    // Rebuttal
    if (newsItem.newsType === 'rebuttal') {
      const hints = {
        detailed: {
          title: '📋 DETAILED DATA REBUTTAL - GOLD STANDARD ✓',
          message: 'Company provided POINT-BY-POINT counter-evidence with DATA. This is a Gold Standard signal! Still wait for base confirmation.',
          severity: 'low',
          goldStandard: '🏆 GOLD STANDARD MET: Point-by-point data rebuttal addresses allegations directly with evidence'
        },
        generic: {
          title: '⚠️ WEAK REBUTTAL - NOT GOLD STANDARD',
          message: 'Generic denial without data is a RED FLAG. Does NOT meet Gold Standard. Stock likely to make new lows.',
          severity: 'medium',
          goldStandard: '❌ MISSING: Gold Standard requires DATA rebuttal addressing each allegation point-by-point'
        },
        none: {
          title: '🚨 NO REBUTTAL - DANGER',
          message: 'Company silence is extremely bearish. Cannot meet Gold Standard without rebuttal. STAY AWAY.',
          severity: 'high',
          goldStandard: '❌ FAILED: No rebuttal = cannot meet Gold Standard. 90%+ chance of permanent loss.'
        }
      };
      return hints[newsItem.rebuttalQuality] || null;
    }

    // Auditor confirmation (new hint type)
    if (newsItem.newsType === 'auditor_confirmation') {
      const isBig4 = ['Deloitte', 'PwC', 'EY', 'KPMG'].includes(newsItem.auditorName);
      return {
        title: isBig4 ? '✅ BIG 4 AUDITOR CONFIRMS - GOLD STANDARD ✓' : '📋 AUDITOR CONFIRMS (non-Big 4)',
        message: isBig4 
          ? `${newsItem.auditorName} (Big 4) reaffirmed the books. This is a GOLD STANDARD signal for SSR reversal!`
          : `${newsItem.auditorName} confirmed books, but not a Big 4 firm. Partial confidence only.`,
        severity: isBig4 ? 'low' : 'medium',
        goldStandard: isBig4 
          ? '🏆 GOLD STANDARD MET: Big 4 Auditor (Deloitte/PwC/EY/KPMG) reaffirmation is strongest SSR signal'
          : '⚠️ PARTIAL: Gold Standard requires Big 4 Auditor. Non-Big 4 confirmation is weaker.'
      };
    }

    // Base pattern
    if (newsItem.newsType === 'base_update') {
      return {
        title: '📊 TWO-WEEK BASE FORMING',
        message: 'Price consolidating in tight range. Check: Has company issued data rebuttal? Big 4 auditor involved?',
        severity: 'low',
        keySignals: ['No new lows', 'Tight trading range', 'Data rebuttal issued?', 'Big 4 auditor?'],
        goldStandard: '🔄 BASE FORMING: But Gold Standard also needs data rebuttal OR Big 4 auditor confirmation'
      };
    }

    // Breakout
    if (newsItem.newsType === 'breakout') {
      return {
        title: '📈 BREAKOUT CONFIRMED',
        message: 'High-volume breakout above base resistance. If Gold Standard signals present, this is a strong entry.',
        severity: 'low',
        goldStandard: '✅ ENTRY POINT: Breakout + Gold Standard (data rebuttal/Big 4 auditor) = 85% success setup'
      };
    }

    // Breakdown
    if (newsItem.newsType === 'breakdown') {
      return {
        title: '📉 BASE FAILED - BREAKDOWN',
        message: 'Short seller thesis validated. Gold Standard signals were missing. Expect 50-80% permanent loss.',
        severity: 'high',
        goldStandard: '📚 LESSON: Without Gold Standard (data rebuttal + Big 4 auditor), most SSR targets fail'
      };
    }

    return null;
  }

  // ========== UTILITY FUNCTIONS ==========
  function clearShortReportState(stock) {
    stock.shortReportPhase = null;
    stock.shortReportDaysLeft = 0;
    stock.shortSeller = null;
    stock.reportType = null;
    stock.reportCrashMagnitude = 0;
    stock.preReportPrice = 0;
    stock.shortReportLow = 0;
    stock.shortReportTransitionEffect = 0;
    stock.insiderBuying = false;
    stock.insiderBuyingAmount = null;
    stock.insiderBuyingTitle = null;
    stock.rebuttalQuality = null;
    stock.auditorQuality = null;
    stock.auditorName = null;
    stock.reversalProbability = 0;
    stock.willReverse = false;
    stock.resolutionDirection = null;
    stock.baseDays = 0;
    stock.baseHighPrice = 0;
    stock.baseLowPrice = 0;
    stock.baseRangePercent = 0;
    stock.volatilityBoost = Math.max(0, (stock.volatilityBoost || 0) - 0.3);
  }

  function getPhaseInfo(stock) {
    if (!stock.shortReportPhase) return null;

    return {
      phase: stock.shortReportPhase,
      daysLeft: stock.shortReportDaysLeft,
      reportType: stock.reportType,
      shortSeller: stock.shortSeller?.name,
      insiderBuying: stock.insiderBuying,
      rebuttalQuality: stock.rebuttalQuality,
      auditorQuality: stock.auditorQuality,
      reversalProbability: stock.reversalProbability,
      baseDays: stock.baseDays,
      baseRange: stock.baseHighPrice && stock.baseLowPrice 
        ? `${stock.baseLowPrice.toFixed(2)} - ${stock.baseHighPrice.toFixed(2)}`
        : null
    };
  }

  // ========== PUBLIC API ==========
  return {
    init: init,
    CONSTANTS: CONSTANTS,
    
    // Main functions
    triggerShortReport: triggerShortReport,
    checkShortReportEvents: checkShortReportEvents,
    processShortReport: processShortReport,
    
    // Utility functions
    getTutorialHint: getTutorialHint,
    getPhaseInfo: getPhaseInfo,
    calculateReversalProbability: calculateReversalProbability,
    
    // Testing utilities
    _test: {
      clearShortReportState: clearShortReportState,
      processInitialCrashPhase: processInitialCrashPhase,
      processRebuttalPhase: processRebuttalPhase,
      processBaseBuildingPhase: processBaseBuildingPhase,
      processResolutionPhase: processResolutionPhase,
      generateRebuttalNews: generateRebuttalNews
    },
    
    // Reset for testing
    _reset: function() {
      deps = {
        stocks: null,
        todayNews: null,
        getMemeMultiplier: null,
        randomChoice: null,
        isEventTypeEnabled: null,
        random: Math.random
      };
    }
  };
})();

// ========== BACKWARDS COMPATIBILITY ==========
// Global functions for existing code
function triggerShortReport(stock, shortSeller) {
  return SSR.triggerShortReport(stock, shortSeller);
}

function checkShortReportEvents() {
  return SSR.checkShortReportEvents();
}

function processShortReport() {
  return SSR.processShortReport();
}

function getShortReportTutorialHint(newsItem) {
  return SSR.getTutorialHint(newsItem);
}

// Export for Node.js testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = SSR;
}
