import {provinceTerrain} from './campaign-fidelity.mjs';
import {provinceDirection} from './geography.mjs';
// Original province layouts with offset-column hex geometry and revised battle rules.
export const TERRAIN=['Plain','Jungle','Hill','Mountain','Water','Castle','Palace'];
export const WEATHER={sunny:'Clear',fewclouds:'Few clouds',cloudy:'Cloudy',rain:'Rain'};
export const FIRE_WEATHER={sunny:1,fewclouds:.8,cloudy:.7,rain:0};
export const fireChance=(int,weather)=>Math.min(.95,(.25+int/150)*(FIRE_WEATHER[weather]??0));
export const DIRECTIONS=[{q:-1,even:-1,odd:0,label:'Upper left',arrow:'↖'},{q:0,even:-1,odd:-1,label:'Up',arrow:'↑'},{q:1,even:-1,odd:0,label:'Upper right',arrow:'↗'},{q:-1,even:0,odd:1,label:'Lower left',arrow:'↙'},{q:0,even:1,odd:1,label:'Down',arrow:'↓'},{q:1,even:0,odd:1,label:'Lower right',arrow:'↘'}];
const WIND_CLOCKWISE=[0,1,2,5,4,3];
export const windLabel=n=>n===0?'Calm':DIRECTIONS[n-1]?.arrow+' '+DIRECTIONS[n-1]?.label;
export const windStrengthLabel=n=>['Calm','Breeze','Strong','Gale'][n]||'Breeze';
export const terrainCost=t=>[2,3,3,Infinity,3,3,3][t]??Infinity;
export const tilePoint=(q,r)=>({x:(q-6)*1.5,z:(r-5.5+(q&1)*.5)*Math.sqrt(3)});
export const hexPoint=tilePoint;
export const inside=(q,r)=>Number.isInteger(q)&&Number.isInteger(r)&&q>=0&&q<13&&r>=0&&r<12;
export const direction=(q,r,i)=>({q:q+DIRECTIONS[i].q,r:r+((q&1)?DIRECTIONS[i].odd:DIRECTIONS[i].even)});
const cube=(q,r)=>{const z=r-(q-(q&1))/2;return [q,-q-z,z];};
export function distance(a,b){const x=cube(a.q,a.r),y=cube(b.q,b.r);return Math.max(...x.map((n,i)=>Math.abs(n-y[i])));}
export const neighbors=(q,r)=>DIRECTIONS.map((_,i)=>direction(q,r,i)).filter(p=>inside(p.q,p.r));
export const ambushAdjacent=(a,b)=>Math.max(Math.abs(a.q-b.q),Math.abs(a.r-b.r))===1;
export const living=b=>b.units.filter(u=>u.soldiers>0&&!u.routed&&!u.fled&&!u.captured);
export const visibleUnit=(b,u,side=b.side)=>u.side===side||b.phase==='deployment'||b.terrain[u.r*13+u.q]!==1||living(b).some(v=>v.side===side&&v.placed&&ambushAdjacent(u,v));
export const at=(b,q,r)=>living(b).find(u=>u.placed&&u.q===q&&u.r===r);
export const ownerFor=(b,side)=>b[side==='attack'?'attacker':'defender'];
export const unitOwner=(b,u)=>u.allyOwner!==undefined&&u.side===u.originalSide&&!u.betrayed?u.allyOwner:ownerFor(b,u.side);
export const controllerSide=b=>b.challenge?b.units.find(u=>u.id===b.challenge.target).side:b.side;
export const isLeader=(b,u)=>b.leaders[u.side]===u.id;
export function entryEdge(q,r,i){
 if(i===1)return r===0;if(i===4)return r===11;
 if(i===0)return (q===0&&r<=5)||(r===0&&q<=6);
 if(i===2)return (q===12&&r<=5)||(r===0&&q>=6);
 if(i===3)return (q===0&&r>=6)||(r===11&&q<=6);
 if(i===5)return (q===12&&r>=6)||(r===11&&q>=6);
 return false;
}
export function placementCells(b,side,unit=null,entry=side==='attack'?(unit?.entryDirection??b.entryDirection):null){const cells=[];for(let r=0;r<12;r++)for(let q=0;q<13;q++){const occupied=at(b,q,r);if(!Number.isFinite(terrainCost(b.terrain[r*13+q]))||b.fire[r*13+q]||(occupied&&occupied.id!==unit?.id))continue;if(side==='attack'&&b.terrain[r*13+q]===6)continue;if(entry!==null&&!entryEdge(q,r,entry))continue;cells.push({q,r});}return cells;}
export function reachable(b,u){
 if(b.phase!=='battle'||!u.placed||u.ordered||u.fled||u.captured)return [];
 const start=u.r*13+u.q,costs=new Map([[start,0]]),paths=new Map([[start,[]]]),queue=[{q:u.q,r:u.r,c:0}];
 while(queue.length){queue.sort((a,z)=>a.c-z.c);const n=queue.shift();if(n.c!==costs.get(n.r*13+n.q))continue;if(n.c>0&&living(b).some(v=>v.side!==u.side&&v.placed&&distance(n,v)===1))continue;for(const v of neighbors(n.q,n.r)){const i=v.r*13+v.q,c=n.c+terrainCost(b.terrain[i]);if(c>u.mobility||at(b,v.q,v.r)||b.fire[i]||c>=(costs.get(i)??Infinity))continue;costs.set(i,c);paths.set(i,[...paths.get(n.r*13+n.q),v]);queue.push({...v,c});}}
 return [...costs].filter(([,c])=>c>0).map(([i,c])=>({q:i%13,r:Math.floor(i/13),cost:c,path:paths.get(i)}));
}
export function setWeather(b,weather){if(!Object.hasOwn(WEATHER,weather))throw Error('Choose clear, few clouds, cloudy or rain.');b.weather=weather;if(weather==='rain')b.fire={};}
function rollWeather(game){const n=game.random();return n<.43?'sunny':n<.7?'fewclouds':n<.85?'cloudy':'rain';}
// Retreats reserve a destination until battle settlement, including after save/load.
export function retreatOptions(game,unit){const b=game.s.battle;if(!b||!unit)return [];const source=unit.allyOwner!==undefined&&!unit.betrayed?unit.origin:b.source,owner=unitOwner(b,unit);return game.province(b.target).neighbors.map(id=>game.province(id)).filter(p=>
 (p.id===source?unit.side==='attack'&&p.owner===owner:p.owner===255&&!p.officers.length)&&
 !b.units.some(v=>v.fled&&v.retreatProvince===p.id&&unitOwner(b,v)!==owner));}
export function newUnit(game,id,side,origin){const o=game.officer(id);return {id,side,originalSide:side,origin,q:null,r:null,placed:false,soldiers:o.soldiers,startSoldiers:o.soldiers,morale:Math.max(45,o.training),war:o.war,int:o.int,training:o.training,weapons:o.weapons,mobility:2+(o.hasHorse?1:0),ordered:false,orderDay:0,routed:false,fled:false,captured:false};}
export function spawnBattle(game,source,target,ids,food,terrain){terrain=provinceTerrain(target,terrain);
 if(!Array.isArray(terrain)||terrain.length!==156||!terrain.includes(6))throw Error('The original province terrain map is unavailable.');
 const defenders=target.officers.filter(id=>game.officer(id).soldiers>0).sort((a,z)=>(z===game.ruler(target.owner).leader)-(a===game.ruler(target.owner).leader)||(z===target.governor)-(a===target.governor)||game.officer(z).soldiers-game.officer(a).soldiers).slice(0,10),i=terrain.indexOf(6);
 const b={rulesVersion:5,entryDirection:provinceDirection(target,source),phase:'deployment',deployment:{attack:false,defend:false},source:source.id,target:target.id,attacker:source.owner,defender:target.owner,side:'attack',day:1,completedDays:0,weather:rollWeather(game),wind:game.int(0,6),windStrength:1,terrain:[...terrain],fire:{},palace:{q:i%13,r:Math.floor(i/13)},food:{attack:food,defend:target.food},units:[],events:[],selected:ids[0],outcome:null,actionSerial:0,challenge:null,challengeIssued:[],challengeWar:80,rulers:{attack:game.ruler(source.owner).leader,defend:game.ruler(target.owner).leader},leaders:{attack:ids.includes(game.ruler(source.owner).leader)?game.ruler(source.owner).leader:ids[0],defend:defenders.includes(game.ruler(target.owner).leader)?game.ruler(target.owner).leader:defenders.includes(target.governor)?target.governor:defenders[0]??null}};
 b.windStrength=b.wind===0?0:game.int(1,3);b.units=[...ids.map(id=>newUnit(game,id,'attack',source.id)),...defenders.map(id=>newUnit(game,id,'defend',target.id))];
 const month=game.s.year*12+game.s.month-1,plan=(game.s.jointPlans||[]).find(p=>p.ruler===source.owner&&p.enemy===target.id&&p.expires>=month&&game.ruler(source.owner).alliances.includes(p.ally)&&!game.ruler(p.ally).alliances.includes(target.owner));
 if(plan){let count=0;const selected=plan.officers?new Set(plan.officers):null;for(const province of target.neighbors.map(id=>game.province(id)).filter(p=>p.owner===plan.ally)){
 const candidates=province.officers.filter(id=>(selected?selected.has(id):id!==game.ruler(plan.ally).leader)&&!game.officer(id).acted&&!game.officer(id).sick&&!game.officer(id).injured&&game.officer(id).soldiers>0).slice(0,Math.max(0,province.officers.length-1));
 for(const id of candidates){if(living(b).filter(u=>u.side==='attack').length>=10||count>=(selected?5:2))break;const entry=provinceDirection(target,province),spot=placementCells(b,'attack',null,entry)[0];if(!spot)continue;const unit=newUnit(game,id,'attack',province.id);Object.assign(unit,{...spot,placed:true,allyOwner:plan.ally,entryDirection:entry});b.units.push(unit);game.officer(id).acted=true;count++;if(!selected){const rice=Math.min(2000,province.food,3000000-b.food.attack);province.food-=rice;b.food.attack+=rice;b.contributions??=[];b.contributions.push({owner:plan.ally,province:province.id,side:'attack',food:rice,gold:0});}}
 }
 if(count&&selected&&game.province(plan.supplyProvince).owner===plan.ally){const home=game.province(plan.supplyProvince),rice=Math.min(plan.food,home.food,3000000-b.food.attack),gold=Math.min(plan.gold,home.gold);home.food-=rice;home.gold-=gold;b.food.attack+=rice;b.allyGold=gold;b.contributions??=[];b.contributions.push({owner:plan.ally,province:home.id,side:'attack',food:rice,gold});}
 if(!count){game.ruler(plan.ally).trust=Math.max(0,game.ruler(plan.ally).trust-5);b.events.push(`${game.ruler(plan.ally).name} failed to honor the promised support; trust fell by 5.`);}
 game.s.jointPlans=game.s.jointPlans.filter(p=>p!==plan);b.events.push(`${game.ruler(plan.ally).name} sent ${count} joint invasion units.`);
 }
 for(const u of b.units.filter(u=>u.side==='defend')){const o=game.officer(u.id);if((o.spyFor===source.owner||o.betrayalFor===source.owner&&o.betrayalUntil>=month)&&living(b).filter(v=>v.side==='attack').length<10&&living(b).filter(v=>v.side==='attack'&&!v.placed).length<placementCells(b,'attack').length){u.side='attack';u.betrayed=true;delete o.betrayalFor;delete o.betrayalUntil;b.events.push(`${o.name} switched sides under a secret pact.`);}}refreshLeader(b,'defend');
 if(placementCells(b,'attack').length<ids.length)throw Error(`This approach has ${placementCells(b,'attack').length} passable entry hexes. Send fewer units.`);return b;
}
function event(b,text){b.events.unshift(text);b.events=b.events.slice(0,50);return text;}
function cue(b,type,u,args={}){b.actionSerial=(b.actionSerial||0)+1;b.lastAction={type,unit:u?.id??null,sequence:b.actionSerial,...args};}
function route(b){for(const u of b.units)if(u.soldiers<=0||u.morale<=10)u.routed=true;}
export function outcome(b){
 if(b.outcome)return b.outcome;
 for(const side of ['attack','defend']){const ruler=b.units.find(u=>u.id===b.rulers[side]);if(ruler?.captured)return b.outcome={winner:side==='attack'?'defend':'attack',reason:'The opposing ruler was captured.'};if(!living(b).some(u=>u.side===side))return b.outcome={winner:side==='attack'?'defend':'attack',reason:b.units.filter(u=>u.side===side).every(u=>u.fled)?'Every opposing unit fled.':'The opposing army has no fighting soldiers.'};}
 if(b.phase==='battle'){for(const side of ['attack','defend']){if(b.food[side]===0)return b.outcome={winner:side==='attack'?'defend':'attack',reason:'The opposing army has exhausted its food.'};const commander=b.units.find(u=>u.id===b.leaders[side]);if(commander&&(commander.captured||commander.fled||commander.routed||commander.soldiers===0||commander.side!==side))return b.outcome={winner:side==='attack'?'defend':'attack',reason:'The opposing army commander was defeated.'};}}
 if(b.phase==='battle'&&living(b).some(u=>u.placed&&u.side==='attack'&&distance(u,b.palace)===0))return b.outcome={winner:'attack',reason:'The palace was occupied.'};
 return null;
}
function refreshLeader(b,side){if(!living(b).some(u=>u.side===side&&u.id===b.leaders[side]))b.leaders[side]=living(b).find(u=>u.side===side)?.id??null;}
function strike(game,u,target,factor=1,retaliate=1){const b=game.s.battle,tile=b.terrain[target.r*13+target.q],cover=[1,.72,.8,0,1.15,.6,.5][tile]??1,arms=.65+.35*Math.min(1,u.weapons/Math.max(1,u.soldiers)),power=u.soldiers*(.4+u.war/100)*(.45+u.training/100)*(.4+u.morale/100)*arms,loss=Math.min(target.soldiers,Math.max(30,Math.floor(power*.13*cover*factor*(.85+game.random()*.3))));target.soldiers-=loss;target.morale=Math.max(0,target.morale-6-Math.floor(loss/Math.max(1,target.startSoldiers)*70));const reply=Math.min(u.soldiers,Math.floor(target.soldiers*.035*(.5+target.war/100)*retaliate));u.soldiers-=reply;if(reply)u.morale=Math.max(0,u.morale-3);route(b);if(target.routed){target.captured=true;target.capturedBy=ownerFor(b,u.side);}return {loss,reply};}
export const jointAttackers=(b,u,target)=>living(b).filter(v=>v.placed&&v.side===u.side&&!v.ordered&&distance(v,target)===1);
function ambush(game,mover,triggered){const b=game.s.battle;for(const hidden of living(b).filter(v=>v.placed&&v.side!==mover.side&&b.terrain[v.r*13+v.q]===1&&ambushAdjacent(v,mover)&&!triggered.has(v.id))){triggered.add(hidden.id);const {loss}=strike(game,hidden,mover,1.25,0);event(b,`${game.officer(hidden.id).name} ambushed ${game.officer(mover.id).name} from jungle: ${loss} losses.`);b.lastAmbush={unit:hidden.id,target:mover.id,day:b.day,sequence:b.actionSerial+1};if(mover.routed)break;}}
function moveAlong(game,u,path){const b=game.s.battle,triggered=new Set();let spent=0;for(const step of path){u.q=step.q;u.r=step.r;spent+=terrainCost(b.terrain[step.r*13+step.q]);ambush(game,u,triggered);if(u.routed||living(b).some(v=>v.side!==u.side&&v.placed&&distance(u,v)===1))break;}u.mobility=Math.max(0,u.mobility-spent);return spent;}
export function reinforcementOptions(game,side=game.s.battle.side){const b=game.s.battle,owner=ownerFor(b,side);return game.s.provinces.filter(p=>p.owner===owner&&(p.neighbors.includes(b.target)||(side==='defend'&&p.id===b.target))).flatMap(p=>{const reserve=p.officers.filter(id=>!b.units.some(u=>u.id===id));if(reserve.length<(p.id===b.target?1:2))return [];return reserve.filter(id=>!game.officer(id).acted&&!game.officer(id).sick&&!game.officer(id).injured&&game.officer(id).soldiers>0).map(id=>({province:p.id,officer:id,soldiers:game.officer(id).soldiers,food:p.food}));});}
function answerChallenge(game,accept){const b=game.s.battle,c=b.challenge,u=living(b).find(u=>u.id===c.challenger),v=living(b).find(u=>u.id===c.target);if(!u||!v)throw Error('The challenged generals are unavailable.');let text;if(!accept){let deserters=0;for(const unit of living(b).filter(x=>x.side===v.side)){const lost=Math.min(unit.soldiers,Math.ceil(unit.soldiers*.05));unit.soldiers-=lost;deserters+=lost;unit.morale=Math.max(0,unit.morale-5);}text=`${game.officer(v.id).name} refused the challenge. ${deserters} soldiers deserted that army.`;}else{const a=u.war+game.int(-10,10),z=v.war+game.int(-10,10),winner=a>=z?u:v,loser=winner===u?v:u;if(winner.war<loser.war){winner.war=Math.min(100,winner.war+1);game.officer(winner.id).war=winner.war;}loser.captured=true;loser.capturedBy=ownerFor(b,winner.side);loser.routed=true;winner.soldiers=Math.max(1,winner.soldiers-Math.ceil(winner.soldiers*.1));v.ordered=true;v.orderDay=b.day;text=`${game.officer(winner.id).name} won the personal challenge and captured ${game.officer(loser.id).name}.`;}
 b.challenge=null;route(b);cue(b,'challenge',u);event(b,text);outcome(b);return text;}
export function act(game,action,args={}){
 const b=game.s.battle;if(!b||b.outcome)throw Error('No active battle.');
 if(b.challenge){if(action!=='challengeResponse'||typeof args.accept!=='boolean')throw Error('Answer the pending personal challenge first.');return answerChallenge(game,args.accept);}
 if(action==='challengeResponse')throw Error('There is no pending personal challenge.');
 if(action==='retreat'){const leader=living(b).find(u=>u.id===b.leaders[b.side]);if(!leader)throw Error('No commander can order retreat.');return act(game,'flee',{unit:leader.id,confirmArmy:true});}
 if(action==='place'){if(b.phase!=='deployment')throw Error('Initial placement is complete.');const u=living(b).find(u=>u.id===Number(args.unit)&&u.side===b.side);if(!u||!placementCells(b,u.side,u).some(p=>p.q===Number(args.q)&&p.r===Number(args.r)))throw Error('Choose a highlighted deployment hex. Invaders must use the highlighted approach edge.');Object.assign(u,{q:Number(args.q),r:Number(args.r),placed:true});cue(b,'place',u);b.selected=living(b).find(v=>v.side===b.side&&!v.placed)?.id??u.id;return event(b,`${game.officer(u.id).name} deployed at ${u.q+1},${u.r+1}.`);}
 if(action==='deploy'){if(b.phase!=='deployment')throw Error('Initial placement is complete.');if(living(b).some(u=>u.side===b.side&&!u.placed))throw Error('Place every unit in this army before confirming.');b.deployment[b.side]=true;if(!b.deployment.defend){b.side='defend';b.selected=living(b).find(u=>u.side==='defend')?.id??null;}else{b.phase='battle';b.side='attack';b.selected=living(b).find(u=>u.side==='attack')?.id??null;}return event(b,b.phase==='battle'?'Day 1: battle begins.':'Defending army: place your units.');}
 if(b.phase!=='battle')throw Error('Place both armies before issuing battle commands.');
 if(action==='view'){const target=b.units.find(u=>u.id===Number(args.target));if(!target||!visibleUnit(b,target))throw Error('Choose a visible battlefield unit to view.');const bank=b.gold;if(target.side!==b.side){if(bank[b.side]<100)throw Error('Viewing an enemy general costs 100 gold.');bank[b.side]-=100;}b.inspected={unit:target.id,side:b.side};return event(b,`${game.officer(target.id).name} inspected${target.side!==b.side?' for 100 gold':''}.`);}
 if(action==='end')return advance(game);
 const u=living(b).find(u=>u.id===Number(args.unit));if(!u||u.side!==b.side||!u.placed)throw Error('Choose a deployed unit on the current side.');if(u.ordered)throw Error('This unit has already completed its daily order.');
 const target=living(b).find(v=>v.id===Number(args.target)),q=Number(args.q),r=Number(args.r);let text,participants=[u];
 if(action==='move'){const move=reachable(b,u).find(p=>p.q===q&&p.r===r);if(!move)throw Error('Choose a highlighted hex within this unit’s mobility.');const cost=moveAlong(game,u,move.path);text=`${game.officer(u.id).name} moved to ${u.q+1},${u.r+1}, spending ${cost} mobility${u.routed?' and was ambushed into defeat':''}.`;
 }else if(action==='moveEnemy'){if(!target||target.side===u.side||!target.placed)throw Error('Choose a hostile general to taunt.');const steps=neighbors(target.q,target.r).filter(p=>!at(b,p.q,p.r)&&!b.fire[p.r*13+p.q]&&terrainCost(b.terrain[p.r*13+p.q])<=target.mobility).sort((a,z)=>distance(a,u)-distance(z,u));const step=steps.find(p=>distance(p,u)<distance(target,u));if(!step)throw Error('The enemy cannot afford a hex toward this unit.');if(game.random()<Math.max(.1,Math.min(.85,.4+(u.int-target.int)/180))){moveAlong(game,target,[step]);text=`${game.officer(target.id).name} fell for the taunt and moved toward ${game.officer(u.id).name}.`;}else text='The enemy ignored the taunt.';
 }else if(['attack','charge','simultaneous'].includes(action)){if(!target||target.side===u.side||!target.placed||distance(u,target)!==1)throw Error('Choose an enemy in one of the six neighbouring hexes.');if(action==='simultaneous'){participants=jointAttackers(b,u,target);if(participants.length<2)throw Error('A simultaneous attack needs two ready friendly units beside the enemy.');}let loss=0,reply=0;if(action==='charge'){for(let n=0;n<3&&!target.routed&&!u.routed;n++){const hit=strike(game,u,target,.9,2);loss+=hit.loss;reply+=hit.reply;}}else for(const friend of participants){if(target.routed)break;const hit=strike(game,friend,target,1,1/participants.length);loss+=hit.loss;reply+=hit.reply;}text=`${action==='simultaneous'?participants.length+' units':game.officer(u.id).name} ${action==='charge'?'charged':'attacked'}: ${loss} enemy losses, ${reply} own losses.`;if(action==='charge'&&!u.routed&&u.soldiers>0){
 const i=DIRECTIONS.findIndex((_,i)=>{const p=direction(u.q,u.r,i);return p.q===target.q&&p.r===target.r;}),destination=target.soldiers<=0?{q:target.q,r:target.r}:direction(target.q,target.r,i);
 const clear=inside(destination.q,destination.r)&&Number.isFinite(terrainCost(b.terrain[destination.r*13+destination.q]))&&!at(b,destination.q,destination.r);
 if(clear&&(target.soldiers<=0||game.random()<.5)){Object.assign(u,destination);ambush(game,u,new Set());text+=target.soldiers<=0?' The charging unit occupied the defeated enemy’s hex.':' The charging unit broke through to the hex beyond the enemy.';}
 }
 }else if(action==='fireball'||action==='fire'){if(!inside(q,r)||distance(u,{q,r})!==1||[3,4,9,99].includes(b.terrain[r*13+q]))throw Error('Choose a dry neighbouring hex for the fireball.');if(b.weather==='rain')throw Error('Fire cannot be lit in rain.');const chance=fireChance(u.int,b.weather);if(game.random()<chance){b.fire[r*13+q]=3;text='The fireball ignited the ground.';}else text='The fireball failed to ignite.';
 }else if(action==='wait'){u.mobility=Math.min(1000,u.mobility+1);text=`${game.officer(u.id).name} waited without moving. Mobility +1, now ${u.mobility}.`;
 }else if(action==='flee'){if(isLeader(b,u)&&args.confirmArmy!==true)throw Error('Confirm that the commander’s flight will withdraw the entire army.');if(isLeader(b,u)){for(const v of living(b).filter(v=>v.side===u.side))v.fled=true;text='The commander fled; the entire army withdrew.';}else{const destination=retreatOptions(game,u).find(p=>p.id===Number(args.province));if(!destination)throw Error('Choose the attacker’s source province (attackers only) or an unoccupied connected province.');if(living(b).some(v=>v.side!==u.side&&v.placed&&distance(u,v)===1)&&game.random()*100<Math.max(5,Math.min(40,45-(u.int+u.war)/5))){u.captured=true;u.routed=true;text=`${game.officer(u.id).name} was intercepted while attempting to flee.`;}else{u.retreatProvince=destination.id;u.fled=true;text=`${game.officer(u.id).name} retreated to ${destination.name} with this unit.`;}}
 }else if(action==='challenge'){if(b.day!==1||u.war<b.challengeWar||b.challengeIssued.length>0)throw Error(`Personal challenges require day 1, war ${b.challengeWar}+ and an unused challenge.`);if(!target||target.side===u.side||!target.placed)throw Error('Choose an opposing general for the challenge.');b.challenge={challenger:u.id,target:target.id};b.challengeIssued.push(u.id);text=`${game.officer(u.id).name} challenged ${game.officer(target.id).name} to personal combat.`;
 }else if(action==='bribe'){if(!isLeader(b,u))throw Error('Only the army commander can offer a bribe.');if(!target||target.side===u.side||b.rulers[target.side]===target.id)throw Error('Choose an enemy general other than the ruler.');const bank=b.gold,gold=Number(args.gold);if(!Number.isInteger(gold)||gold<100||gold>bank[u.side])throw Error('Offer at least 100 gold from this army’s treasury.');if(living(b).filter(v=>v.side===u.side).length>=10)throw Error('This army already has ten active units.');const oldSide=target.side,chance=Math.max(.05,Math.min(.9,.1+(100-game.officer(target.id).loyalty)/180+(u.int-target.int)/250+gold/Math.max(3000,target.soldiers*3)));bank[u.side]-=gold;if(game.random()<chance){target.side=u.side;target.betrayed=true;target.ordered=true;target.orderDay=b.day;target.morale=Math.max(45,target.morale);if(b.leaders[oldSide]!==target.id)refreshLeader(b,oldSide);text=`${game.officer(target.id).name} accepted ${gold} gold and joined this army.`;}else text=`${game.officer(target.id).name} refused the ${gold}-gold bribe.`;
 }else if(action==='reinforce'){if(b.units.length>=40||living(b).filter(v=>v.side===u.side).length>=10)throw Error('This army cannot receive another unit.');const option=reinforcementOptions(game,u.side).find(o=>o.province===Number(args.province)&&o.officer===Number(args.officer));if(!option)throw Error('Choose a ready reserve commander from an adjacent friendly province; leave an officer behind.');const support=game.province(option.province),rice=Number(args.food??0);if(!Number.isInteger(rice)||rice<0||rice>support.food||rice+b.food[u.side]>3000000)throw Error('Choose an available amount of rice within the army’s capacity.');const entry=support.id===b.target?null:provinceDirection(game.province(b.target),support),cells=placementCells(b,u.side,null,entry),spot=args.q===undefined?cells.sort((a,z)=>distance(a,b.palace)-distance(z,b.palace))[0]:cells.find(p=>p.q===q&&p.r===r);if(!spot)throw Error('Choose a feasible reinforcement entry hex.');const unit=newUnit(game,option.officer,u.side,support.id);Object.assign(unit,{...spot,placed:true,ordered:true,orderDay:b.day});support.food-=rice;b.food[u.side]+=rice;game.officer(unit.id).acted=true;b.units.push(unit);text=`${game.officer(unit.id).name} reinforced this army with ${unit.soldiers} soldiers and ${rice} rice.`;
 }else throw Error('Unknown battle command.');
 for(const v of participants){v.ordered=true;v.orderDay=b.day;}cue(b,action,u,{q:Number.isInteger(q)?q:null,r:Number.isInteger(r)?r:null,target:target?.id??null});route(b);event(b,text);outcome(b);return text;
}
function dailyEffects(game){const b=game.s.battle;for(const side of ['attack','defend']){const need=Math.ceil(living(b).filter(u=>u.side===side).reduce((n,u)=>n+u.soldiers,0)/20),shortage=b.food[side]<need;b.food[side]=Math.max(0,b.food[side]-need);if(shortage){for(const u of living(b).filter(u=>u.side===side))u.morale=Math.max(0,u.morale-15);event(b,`${side==='attack'?'Invaders':'Defenders'} ran short of rice.`);}}
 const fires={};if(b.weather!=='rain')for(const [key,turns]of Object.entries(b.fire)){const i=Number(key),q=i%13,r=Math.floor(i/13),unit=at(b,q,r);if(unit){const lost=Math.min(unit.soldiers,Math.max(100,Math.ceil(unit.soldiers*.3)));unit.soldiers-=lost;unit.morale=Math.max(0,unit.morale-20);event(b,`${game.officer(unit.id).name} lost ${lost} soldiers to fire.`);}if(turns>1)fires[i]=Math.max(fires[i]||0,turns-1);if(b.wind>0&&b.windStrength>0){let previous={q,r};for(let step=0;step<b.windStrength;step++){const next=direction(previous.q,previous.r,b.wind-1),ni=next.r*13+next.q;if(!inside(next.q,next.r)||[3,4,9,99].includes(b.terrain[ni]))break;if(game.random()<[0,.4,.8,.98][b.windStrength])fires[ni]=3;previous=next;}if(b.windStrength>=2)for(const offset of [-1,1]){const next=direction(q,r,WIND_CLOCKWISE[(WIND_CLOCKWISE.indexOf(b.wind-1)+offset+6)%6]),ni=next.r*13+next.q;if(inside(next.q,next.r)&&![3,4,9,99].includes(b.terrain[ni])&&game.random()<(b.windStrength===3?.7:.4))fires[ni]=3;}}}b.fire=fires;route(b);
}
function advance(game){const b=game.s.battle;for(const u of living(b).filter(u=>u.side===b.side&&!u.ordered)){u.mobility=Math.min(1000,u.mobility+1);u.ordered=true;u.orderDay=b.day;}if(b.side==='defend'){dailyEffects(game);b.completedDays=b.day;if(outcome(b))return event(b,b.outcome.reason);if(b.day===30){b.suspended=true;return event(b,'Thirty days elapsed; warfare continues next month.');}b.day++;setWeather(b,rollWeather(game));b.wind=game.int(0,6);b.windStrength=b.wind===0?0:game.int(1,3);event(b,`Day ${b.day}: ${WEATHER[b.weather]}; ${windStrengthLabel(b.windStrength)} wind ${windLabel(b.wind)}${b.weather==='rain'?'; all fires extinguished':''}.`);}
 b.side=b.side==='attack'?'defend':'attack';for(const u of living(b).filter(u=>u.side===b.side))u.ordered=u.orderDay===b.day;b.selected=living(b).find(u=>u.side===b.side)?.id??null;outcome(b);return event(b,`Day ${b.day}: ${b.side==='attack'?'Invading':'Defending'} army’s orders.`);
}
export function aiBattle(game,intelligence=60){const b=game.s.battle;if(b.challenge){const u=b.units.find(u=>u.id===b.challenge.challenger),v=b.units.find(u=>u.id===b.challenge.target);return act(game,'challengeResponse',{accept:v.war>=u.war-5});}if(b.phase==='deployment'){const u=living(b).find(u=>u.side===b.side&&!u.placed);if(!u)return act(game,'deploy');const cells=placementCells(b,u.side,u).sort((a,z)=>distance(a,b.palace)-distance(z,b.palace));return act(game,'place',{unit:u.id,...cells[0]});}
 const units=living(b).filter(u=>u.side===b.side&&!u.ordered);if(!units.length)return act(game,'end');const u=units.sort((a,z)=>intelligence>=50?z.war-a.war:0)[0],enemies=living(b).filter(v=>v.side!==u.side&&v.placed&&visibleUnit(b,v,u.side)),adjacent=enemies.filter(v=>distance(u,v)===1).sort((a,z)=>a.soldiers-z.soldiers);
 if(b.day===1&&intelligence>=75&&u.war>=b.challengeWar&&!b.challengeIssued.includes(u.id)){const opponent=enemies.find(v=>v.war<u.war-10);if(opponent)return act(game,'challenge',{unit:u.id,target:opponent.id});}
 if(adjacent.length){const target=adjacent[0];if(intelligence>=50&&jointAttackers(b,u,target).length>1)return act(game,'simultaneous',{unit:u.id,target:target.id});if(intelligence>=75&&u.soldiers>target.soldiers*1.5)return act(game,'charge',{unit:u.id,target:target.id});if(intelligence>=75&&u.int>=70&&b.weather!=='rain'&&[1,5].includes(b.terrain[target.r*13+target.q])&&!b.fire[target.r*13+target.q]&&target.soldiers>u.soldiers&&game.random()<.3)return act(game,'fireball',{unit:u.id,q:target.q,r:target.r});return act(game,'attack',{unit:u.id,target:target.id});}
 const own=living(b).filter(v=>v.side===u.side).reduce((n,v)=>n+v.soldiers,0),hostile=enemies.reduce((n,v)=>n+v.soldiers,0);if(intelligence>=75&&own<hostile*.7&&b.units.length<40&&living(b).filter(v=>v.side===u.side).length<10){const option=reinforcementOptions(game,u.side).sort((a,z)=>z.soldiers-a.soldiers)[0];if(option&&placementCells(b,u.side).length)return act(game,'reinforce',{unit:u.id,...option,food:Math.min(option.food,5000,3000000-b.food[u.side])});}
 const goal=u.side==='attack'?b.palace:enemies.sort((a,z)=>distance(u,a)-distance(u,z))[0]||b.palace,moves=reachable(b,u);if(moves.length){moves.sort((a,z)=>distance(a,goal)-distance(z,goal));const spot=intelligence>=50?moves[0]:moves[game.int(0,moves.length-1)];if(distance(spot,goal)<distance(u,goal)||intelligence<50)return act(game,'move',{unit:u.id,...spot});}return act(game,'wait',{unit:u.id});
}
export function validateBattle(b,state,terrains){
 if(!b)return;if(!b.gold){b.gold={attack:state.provinces[b.source-1]?.gold??0,defend:state.provinces[b.target-1]?.gold??0};if(state.provinces[b.source-1])state.provinces[b.source-1].gold=0;if(state.provinces[b.target-1])state.provinces[b.target-1].gold=0;}
 const legacy=b.rulesVersion===undefined||b.rulesVersion===2;
 if(legacy){if(!Number.isInteger(b.day)||b.day<1||b.day>31)throw Error('Invalid legacy battle day.');b.phase='battle';b.deployment={attack:true,defend:true};b.rulesVersion=3;b.completedDays=Math.min(30,b.completedDays??b.day-1);b.day=Math.min(30,b.day);if(b.weather==='clear')b.weather='sunny';b.wind=[0,1,2,3,1,3,4,5,6][b.wind]??0;b.windStrength=b.wind===0?0:1;b.challenge=null;b.challengeIssued=[];b.challengeWar=80;b.rulers={attack:state.rulers.find(r=>r.id===b.attacker)?.leader,defend:state.rulers.find(r=>r.id===b.defender)?.leader};b.leaders={attack:b.units.find(u=>u.side==='attack'&&u.id===b.rulers.attack)?.id??b.units.find(u=>u.side==='attack')?.id??null,defend:b.units.find(u=>u.side==='defend'&&u.id===b.rulers.defend)?.id??b.units.find(u=>u.side==='defend')?.id??null};if(terrains[b.target-1])b.terrain=[...terrains[b.target-1]];const index=b.terrain.indexOf(6);b.palace={q:index%13,r:Math.floor(index/13)};const occupied=new Set();for(const u of b.units){if(!inside(u.q,u.r))throw Error('Invalid legacy unit coordinates.');u.origin=u.side==='attack'?b.source:b.target;u.originalSide=u.side;u.placed=true;u.mobility=2;u.ordered=u.ap===0;u.orderDay=u.ordered?b.day:0;u.fled=false;u.captured=false;delete u.ap;if(!Number.isFinite(terrainCost(b.terrain[u.r*13+u.q]))||occupied.has(u.r*13+u.q)){const spots=[];for(let r=0;r<12;r++)for(let q=0;q<13;q++)if(Number.isFinite(terrainCost(b.terrain[r*13+q]))&&!occupied.has(r*13+q))spots.push({q,r});const spot=spots.sort((a,z)=>distance(a,u)-distance(z,u))[0];if(!spot)throw Error('No safe hex for the legacy unit.');Object.assign(u,spot);}occupied.add(u.r*13+u.q);}b.fire=Object.fromEntries(Object.entries(b.fire||{}).filter(([i])=>![3,4,9,99].includes(b.terrain[i])));delete b.city;delete b.walls;}
 const entry=provinceDirection(state.provinces[b.target-1],state.provinces[b.source-1]);
 if(b.rulesVersion===3){b.rulesVersion=4;b.entryDirection=entry;if(b.phase==='deployment'){let changed=false;for(const u of b.units.filter(u=>u.side==='attack'&&u.placed))if(!entryEdge(u.q,u.r,entry)){Object.assign(u,{placed:false,q:null,r:null});changed=true;}if(changed){b.side='attack';b.deployment.attack=false;b.selected=living(b).find(u=>u.side==='attack'&&!u.placed)?.id??b.selected;}}}
 if(b.rulesVersion===4){if(b.weather==='stormy')b.weather='cloudy';b.rulesVersion=5;}
 if(b.entryDirection!==entry)throw Error('Invalid province approach direction.');
 if(b.rulesVersion!==5||!state.provinces[b.source-1]||!state.provinces[b.target-1]||b.source===b.target||!state.provinces[b.source-1].neighbors.includes(b.target)||state.provinces[b.source-1].owner!==b.attacker||state.provinces[b.target-1].owner!==b.defender||!['attack','defend'].includes(b.side)||!['deployment','battle'].includes(b.phase)||!Number.isInteger(b.day)||b.day<1||b.day>30||!Number.isInteger(b.completedDays)||b.completedDays<0||b.completedDays>30||b.completedDays>b.day||(!b.outcome&&!b.suspended&&b.completedDays!==b.day-1)||!Object.hasOwn(WEATHER,b.weather)||!Number.isInteger(b.wind)||b.wind<0||b.wind>6||!Number.isInteger(b.windStrength)||b.windStrength<0||b.windStrength>3||!Number.isInteger(b.challengeWar)||b.challengeWar<0||b.challengeWar>100)throw Error('Invalid battlefield.');
 if(!Array.isArray(b.terrain)||b.terrain.length!==156||b.terrain.some(t=>![0,1,2,3,4,5,6,9,99].includes(t))||!b.fire||Object.entries(b.fire).some(([i,n])=>!/^\d+$/.test(i)||Number(i)>155||!Number.isInteger(n)||n<1||n>3||[3,4,9,99].includes(b.terrain[Number(i)]))||!b.palace||!inside(b.palace.q,b.palace.r)||b.terrain[b.palace.r*13+b.palace.q]!==6)throw Error('Invalid battlefield terrain.');if(terrains[b.target-1]&&b.terrain.some((t,i)=>t!==provinceTerrain(state.provinces[b.target-1],terrains[b.target-1])[i]))throw Error('The province terrain must match the original map.');
 if(b.phase==='deployment'&&(b.day!==1||b.completedDays!==0||b.deployment?.defend||(b.side==='attack'&&b.deployment?.attack)||(b.side==='defend'&&!b.deployment?.attack)))throw Error('Invalid deployment phase.');if(!b.deployment||typeof b.deployment.attack!=='boolean'||typeof b.deployment.defend!=='boolean'||(b.phase==='battle'&&(!b.deployment.attack||!b.deployment.defend)))throw Error('Invalid deployment state.');if(b.weather==='rain')b.fire={};
 if(b.initialStores)for(const side of ['attack','defend'])for(const k of ['gold','food'])if(!Number.isInteger(b.initialStores[side]?.[k])||b.initialStores[side][k]<0||b.initialStores[side][k]>(k==='gold'?30000:3000000))throw Error('Invalid initial field supplies.');if(b.contributions&&(!Array.isArray(b.contributions)||b.contributions.length>40||b.contributions.some(c=>!state.rulers.some(r=>r.id===c.owner)||!state.provinces[c.province-1]||!['attack','defend'].includes(c.side)||!Number.isInteger(c.gold)||c.gold<0||c.gold>30000||!Number.isInteger(c.food)||c.food<0||c.food>3000000)))throw Error('Invalid allied contributions.');
 for(const side of ['attack','defend']){if(!Number.isInteger(b.gold?.[side])||b.gold[side]<0||b.gold[side]>30000||!Number.isInteger(b.food?.[side])||b.food[side]<0||b.food[side]>3000000||b.rulers?.[side]!==state.rulers.find(r=>r.id===ownerFor(b,side))?.leader)throw Error('Invalid army data.');}
 if(!Array.isArray(b.units)||!b.units.length||b.units.length>40)throw Error('Invalid armies.');const seen=new Set(),occupied=new Set();for(const u of b.units){if(seen.has(u.id)||!Number.isInteger(u.id)||!['attack','defend'].includes(u.side)||!['attack','defend'].includes(u.originalSide)||!state.provinces[u.origin-1]?.officers.includes(u.id)||state.provinces[u.origin-1].owner!==(u.allyOwner??ownerFor(b,u.originalSide)))throw Error('Invalid battle officer.');if(u.origin!==b.target&&!state.provinces[b.target-1].neighbors.includes(u.origin))throw Error('An army must come from a connected province.');if(u.allyOwner===undefined&&u.entryDirection!==undefined)throw Error('Only allied support has its own deployment direction.');if(u.betrayed!==undefined&&typeof u.betrayed!=='boolean')throw Error('Invalid unit allegiance.');if(u.side!==u.originalSide&&u.betrayed!==true)throw Error('A changed allegiance requires a betrayal record.');if(u.allyOwner!==undefined&&(!state.rulers.find(r=>r.id===ownerFor(b,u.originalSide))?.alliances.includes(u.allyOwner)||u.entryDirection!==provinceDirection(state.provinces[b.target-1],state.provinces[u.origin-1])))throw Error('Invalid allied invasion unit.');seen.add(u.id);for(const [key,max]of Object.entries({soldiers:10000,startSoldiers:10000,morale:100,war:100,int:100,training:100,weapons:10000,mobility:1000,orderDay:30}))if(!Number.isInteger(u[key])||u[key]<0||u[key]>max)throw Error('Invalid battle unit.');for(const key of ['placed','ordered','routed','fled','captured'])if(typeof u[key]!=='boolean')throw Error('Invalid unit state.');if(u.placed){if(b.phase==='deployment'&&u.side==='attack'&&!entryEdge(u.q,u.r,u.entryDirection??b.entryDirection))throw Error('An invader must deploy on the province’s approach edge.');if(!inside(u.q,u.r)||!Number.isFinite(terrainCost(b.terrain[u.r*13+u.q])))throw Error('Unit on impassable terrain.');if(!u.routed&&!u.fled&&!u.captured&&u.soldiers>0){const k=u.r*13+u.q;if(occupied.has(k))throw Error('Overlapping battle units.');occupied.add(k);}}else if(b.phase!=='deployment'||u.q!==null||u.r!==null)throw Error('Invalid reserve position.');}
 for(const u of b.units)if(u.retreatProvince!==undefined&&(!u.fled||!Number.isInteger(u.retreatProvince)||!retreatOptions({s:state,province:id=>state.provinces[id-1]},u).some(p=>p.id===u.retreatProvince)))throw Error('Invalid retreat destination.');
 for(const side of ['attack','defend'])if(living(b).filter(u=>u.side===side).length>10)throw Error('An army may have at most ten active units.');
 for(const side of ['attack','defend'])if(b.leaders?.[side]!==null&&!b.units.some(u=>u.id===b.leaders?.[side]&&u.side===side))throw Error('Invalid army commander.');if(!Array.isArray(b.challengeIssued)||new Set(b.challengeIssued).size!==b.challengeIssued.length||b.challengeIssued.some(id=>!seen.has(id)))throw Error('Invalid challenge history.');if(b.challenge){const u=b.units.find(u=>u.id===b.challenge.challenger),v=b.units.find(u=>u.id===b.challenge.target);if(b.phase!=='battle'||b.day!==1||!u||!v||u.side===v.side||u.side!==b.side||!u.placed||!v.placed||u.war<b.challengeWar||u.captured||v.captured)throw Error('Invalid pending challenge.');}
 b.events=Array.isArray(b.events)?b.events.filter(t=>typeof t==='string').map(t=>t.slice(0,500)).slice(0,50):[];if(b.outcome&&(!['attack','defend'].includes(b.outcome.winner)||typeof b.outcome.reason!=='string'))throw Error('Invalid battle result.');
}
