import {runMonthlyEvents,validateMonthlyState,EVENT_TYPES} from './monthly-events.mjs';
import {Game as Domestic,createCampaign as baseCreate,validateSave as baseValidate,clamp,DEFAULT_RULES} from './engine.mjs';
import {applyGeography} from './geography.mjs';
import {NEW_ORDERS,executeProvinceOrder,validateProvinceOrders,updateVisitors,covertUpkeep,hireCapacity} from './province-rules.mjs';
import {spawnBattle,act,aiBattle,outcome,validateBattle,WEATHER,setWeather,controllerSide,ownerFor,unitOwner,living} from './battle.mjs';
export {DEFAULT_RULES};export const AI_DEFAULTS={intelligence:60,aggression:55};
const clone=v=>JSON.parse(JSON.stringify(v));
export const activeRulers=s=>s.rulers.filter(r=>s.provinces.some(p=>p.owner===r.id));
export function createCampaign(scenario,humans=[0],difficulty=2){if(typeof humans==='number')humans=[humans];if(!Array.isArray(humans)||humans.length>12||new Set(humans).size!==humans.length||humans.some(id=>!activeRulers(scenario).some(r=>r.id===id)))throw Error('Choose up to 12 distinct active rulers.');const first=humans[0]??activeRulers(scenario)[0].id;const s=baseCreate(scenario,first,difficulty);Object.assign(s,{version:2,humanRulers:humans,completed:[],ai:{...AI_DEFAULTS},aiRulers:{},paused:false,speed:600,battle:null});s.settings.sound=true;s.settings.music=true;s.settings.battleView="personal";validateMonthlyState(s);validateProvinceOrders(s);applyGeography(s);return s;}
export class Game extends Domestic{
 constructor(s,rules={},terrains=[]){super(s,rules);this.terrains=terrains;applyGeography(s);updateVisitors(this);if(s.turn===1&&!s.lastReport&&!s.monthlyState?.applied){const report={year:s.year,month:s.month,gold:0,food:0,events:[],details:[]};runMonthlyEvents(this,report,{initial:true});s.lastReport=report;for(const e of report.details)super.record(e.text,e.kind);}if(s.battle?.outcome)this.resolveBattle();else if(s.battle&&!this.battleDetailed())this.resolveUnwatchedBattle();}
 endMonth(){const report=super.endMonth();covertUpkeep(this);return report;}
 isHuman(id=this.s.player){return this.s.humanRulers.includes(id);}
 battleDetailed(){const b=this.s.battle;if(!b)return false;if(this.s.settings.battleView==='all')return true;return this.s.humanRulers.some(id=>{const r=this.ruler(id);return (id===b.attacker&&b.units.some(u=>u.side==='attack'&&u.id===r.leader))||(id===b.defender&&this.province(b.target).officers.includes(r.leader));});}
 battleOwner(){return this.s.battle?ownerFor(this.s.battle,controllerSide(this.s.battle)):this.s.player;}
 battleHuman(){return this.battleDetailed()&&this.isHuman(this.battleOwner());}
 resolveUnwatchedBattle(){if(!this.s.battle||this.battleDetailed())return false;const b=this.s.battle;for(let n=0;n<1500&&!b.outcome;n++)aiBattle(this,this.aiFor(ownerFor(b,controllerSide(b))).intelligence);if(!b.outcome)throw Error('The automatic battle exceeded its turn limit.');this.resolveBattle();return true;}
 aiFor(id=this.s.player){return {...this.s.ai,...this.s.aiRulers[id]};}
 normalize(){for(const p of this.s.provinces){if(!p.officers.length){p.owner=255;p.governor=null;}else if(!p.officers.includes(p.governor))p.governor=p.officers[0];}for(const r of this.s.rulers){const own=this.s.provinces.filter(p=>p.owner===r.id);const leaderHome=own.find(p=>p.officers.includes(r.leader));if(leaderHome)r.home=leaderHome.id;else if(own.length&&!own.some(p=>p.id===r.home))r.home=own[0].id;if(r.advisor!==null&&!own.some(p=>p.officers.includes(r.advisor)))r.advisor=null;}applyGeography(this.s);}
 record(text,type='order'){const result=super.record(text,type);delete this.s.eventPreview;this.s.lastEvent={kind:type==='war'?'war':type==='diplomacy'?'diplomacy':type==='prison'?'prison':type==='month'?'month':type==='history'?'history':'council',title:type==='war'?'Campaign report':type==='diplomacy'?'Diplomatic audience':type==='prison'?'Messenger detained':type==='month'?'Monthly council':type==='history'?'Historical chronicle':'Council report',text,officer:this.s.portraitOfficer??this.province(this.s.selected).governor};return result;}
 execute(type,args={}){if(this.s.battle)throw Error('Finish the battle before issuing province orders.');if(this.s.campaignEnded)throw Error('This campaign ended when your ruler went into exile.');if(type==='attack')return this.invade(args);const settlement=type==='move'&&this.province(args.target).owner===255;const result=NEW_ORDERS.has(type)?executeProvinceOrder(this,type,args):super.execute(type,args);if(type!=='selfExile')this.s.selected=Number(args.province);this.s.portraitOfficer=args.officer===undefined?this.province(args.province).governor:Number(args.officer);this.s.lastEvent.officer=this.s.portraitOfficer;if(settlement){this.s.lastEvent.art='occupation';this.s.lastEvent.title='佔地為王 · Territory occupied';this.s.lastEvent.province=Number(args.target);}if(type==='diplomacy'||type==='diplomaticMission'){this.s.lastEvent.kind='diplomacy';this.s.lastEvent.title='Diplomatic audience';}if(type==='healing')this.s.lastEvent.art='medical';return result;}
 invade(args){const before=clone(this.s);try{return this.invadeReady(args);}catch(error){this.s=before;throw error;}}
 invadeReady(args){if(this.s.battle)throw Error('Finish the existing battle first.');const p=this.owned(args.province),target=this.province(args.target);if(!p.neighbors.includes(target.id)||target.owner===255||target.owner===p.owner)throw Error('Attack an adjacent enemy province.');if(this.ruler().alliances.includes(target.owner))throw Error('End the alliance before attacking this ruler.');const ids=(args.officers||[Number(args.officer)]).map(Number);if(!ids.length||ids.length>10||new Set(ids).size!==ids.length||ids.length>=p.officers.length)throw Error('Choose 1–10 commanders and leave at least one officer to govern.');for(const id of ids){const o=this.ready(p,id);if(!o.soldiers)throw Error('Every commander needs soldiers.');}const food=this.amount(args.food,Math.min(3000000,p.food));const b=spawnBattle(this,p,target,ids,food,this.terrains[target.id-1]||Array(156).fill(0));p.food-=food;for(const id of ids)this.officer(id).acted=true;this.s.battle=b;this.s.selected=target.id;this.record(`${this.ruler().name} invaded ${target.name}.`,'war');this.s.lastEvent.art='war';this.s.lastEvent.province=target.id;this.s.lastEvent.title='出兵戰爭 · Troops deployed';if(outcome(b))this.resolveBattle();else if(!this.battleDetailed())this.resolveUnwatchedBattle();return this.s.battle?'The armies entered the battlefield.':this.s.lastEvent.text;}
 battleAction(action,args={}){const message=act(this,action,args);if(this.s.battle.outcome)this.resolveBattle();return message;}
 resolveBattle(){
 const b=this.s.battle;if(!b?.outcome)return;const source=this.province(b.source),target=this.province(b.target),attackWon=b.outcome.winner==='attack',winner=attackWon?b.attacker:b.defender,decisions=new Map(),prisoners=[];
 const refuge=(owner,origin=null)=>{const home=origin?this.province(origin):null;if(home?.owner===owner&&!(attackWon&&home.id===target.id))return home;return target.neighbors.map(id=>this.province(id)).find(p=>p.owner===owner&&!(attackWon&&p.id===target.id))||null;};
 const captive=(id)=>{decisions.set(id,{province:target,owner:255,prisonerOf:winner});if(!prisoners.includes(id))prisoners.push(id);};
 if(attackWon)for(const id of target.officers){const home=refuge(b.defender);if(home)decisions.set(id,{province:home,owner:b.defender});else captive(id);}
 for(const u of b.units){const o=this.officer(u.id);o.soldiers=u.soldiers;if(u.soldiers>0&&u.soldiers<u.startSoldiers/2&&!u.captured){o.injured=true;o.illMonths=o.medicalBook?1:3;}o.training=clamp(o.training+2);o.acted=true;const owner=unitOwner(b,u),won=u.side===b.outcome.winner;
  if(u.fled&&u.retreatProvince!==undefined){const destination=this.province(u.retreatProvince);if(destination.owner!==255&&destination.owner!==owner)throw Error('The retreat destination has been occupied.');destination.owner=owner;decisions.set(u.id,{province:destination,owner});continue;}
  if(u.captured&&!won){captive(u.id);continue;}
  if(u.allyOwner!==undefined&&!u.betrayed){const home=refuge(owner,u.origin);if(home)decisions.set(u.id,{province:home,owner});else captive(u.id);continue;}
  if(won&&!u.fled&&!u.routed){decisions.set(u.id,{province:target,owner});continue;}
  const home=refuge(owner,u.origin);if(home)decisions.set(u.id,{province:home,owner});else if(!won)captive(u.id);else decisions.set(u.id,{province:source,owner});
 }
 for(const [id,d]of decisions){const o=this.officer(id);for(const p of this.s.provinces)for(const key of ['officers','unclaimed','hidden'])p[key]=p[key].filter(n=>n!==id);o.owner=d.owner;delete o.prisonerOf;if(d.prisonerOf!==undefined){d.province.unclaimed.push(id);o.prisonerOf=d.prisonerOf;o.soldiers=Math.floor(o.soldiers*.5);}else{d.province.officers.push(id);if(b.units.find(u=>u.id===id)?.betrayed)o.loyalty=Math.max(40,Math.min(90,o.loyalty));}}
 source.food=Math.min(3000000,source.food+b.food.attack);target.food=b.food.defend;if(attackWon){target.owner=b.attacker;target.loyalty=Math.max(20,target.loyalty-20);target.castle=Math.floor(target.castle*.75);}target.governor=target.officers.includes(this.ruler(target.owner).leader)?this.ruler(target.owner).leader:target.officers[0]??null;
 if(attackWon)for(const owner of new Set(b.units.filter(u=>u.allyOwner!==undefined).map(u=>u.allyOwner))){const troops=b.units.filter(u=>u.allyOwner===owner).reduce((n,u)=>n+u.startSoldiers,0),home=this.province(this.ruler(owner).home),gold=Math.min(source.gold,Math.ceil(troops/1000)*10),rice=Math.min(source.food,Math.ceil(troops/1000)*100);source.gold-=gold;source.food-=rice;home.gold=Math.min(30000,home.gold+gold);home.food=Math.min(3000000,home.food+rice);}
 this.s.lastBattle={...b.outcome,target:target.id,day:b.day,attacker:b.attacker,defender:b.defender,captured:prisoners};this.record(`${target.name}: ${this.ruler(winner).name} won. ${b.outcome.reason}`,'war');this.s.lastEvent.art=attackWon?'occupation':'war';this.s.lastEvent.province=target.id;if(attackWon)this.s.lastEvent.title='佔地為王 · Territory occupied';this.s.battle=null;this.normalize();if(prisoners.length){delete this.s.lastEvent.art;this.s.lastEvent.kind='prison';this.s.lastEvent.title='Generals captured';}
 }
 finishFactionTurn(){if(this.s.campaignEnded)throw Error('This campaign has ended.');if(this.s.battle)throw Error('Finish the battle first.');const pID=this.s.player;for(const p of this.s.provinces.filter(p=>p.owner===pID&&p.delegate!=='manual'))for(const id of p.officers){const o=this.officer(id);if(o.acted)continue;try{if(p.delegate==='people'&&p.loyalty<90&&p.food>=3000)super.execute('relief',{province:p.id,officer:id,amount:3000});else if(p.gold>=100)super.execute(p.land<p.flood?'develop':'flood',{province:p.id,officer:id,amount:100});}catch{}}
 if(!this.s.completed.includes(pID))this.s.completed.push(pID);let next=activeRulers(this.s).find(r=>!this.s.completed.includes(r.id));let report=null;if(!next){report=this.endMonth();for(const e of report.details)this.record(e.text,e.kind);this.s.completed=[];this.normalize();next=activeRulers(this.s)[0];}if(next){this.s.player=next.id;this.s.selected=next.home;this.s.portraitOfficer=null;}return report;}
 aiStep(){if(this.s.campaignEnded)return false;if(this.s.battle){const b=this.s.battle;if(this.battleHuman())return false;if(!this.battleDetailed())return this.resolveUnwatchedBattle();aiBattle(this,this.aiFor(ownerFor(b,controllerSide(b))).intelligence);if(b.outcome)this.resolveBattle();return true;}if(this.isHuman())return false;const ai=this.aiFor(),provinces=this.s.provinces.filter(p=>p.owner===this.s.player),smart=ai.intelligence>=50;
 for(const p of provinces){let ready=p.officers.map(id=>this.officer(id)).filter(o=>!o.acted&&!o.sick&&!o.injured);if(!ready.length)continue;ready.sort((a,b)=>smart?b.int-a.int:0);const o=smart?ready[0]:ready[this.int(0,ready.length-1)];const army=ready.filter(o=>o.soldiers>0).sort((a,b)=>b.soldiers-a.soldiers).slice(0,Math.min(5,p.officers.length-1));const strength=army.reduce((n,o)=>n+o.soldiers*(.5+o.training/100),0);const enemies=p.neighbors.map(id=>this.province(id)).filter(q=>q.owner!==255&&q.owner!==p.owner&&!this.ruler().alliances.includes(q.owner)).sort((a,b)=>a.officers.reduce((n,id)=>n+this.officer(id).soldiers,0)-b.officers.reduce((n,id)=>n+this.officer(id).soldiers,0));
 const enemy=enemies[0],enemyStrength=enemy?.officers.reduce((n,id)=>n+this.officer(id).soldiers*(.5+this.officer(id).training/100),0)||0;
 try{if(ai.aggression>0&&army.length&&p.food>5000&&enemy&&strength>enemyStrength*(smart?1.25:0.65)&&this.random()<ai.aggression/100){this.invade({province:p.id,target:enemy.id,officers:army.map(o=>o.id),food:Math.min(p.food,Math.max(6000,Math.floor(strength)))});return true;}
 const neutral=p.neighbors.map(id=>this.province(id)).find(q=>q.owner===255);if(neutral&&p.officers.length>1){this.execute('move',{province:p.id,officer:o.id,target:neutral.id,gold:Math.min(200,p.gold),food:Math.min(5000,p.food)});return true;}
 if(p.unclaimed.length&&p.gold>=100){this.execute('recruit',{province:p.id,officer:o.id,target:p.unclaimed[0]});return true;}
 if(smart&&p.loyalty<65&&p.food>5000){this.execute('relief',{province:p.id,officer:o.id,amount:3000});return true;}
 if(smart&&p.food<5000&&p.merchant&&p.gold>100){this.execute('trade',{province:p.id,mode:'buy',amount:Math.min(10000,p.gold*p.ricePrice)});o.acted=true;return true;}
 if(ai.aggression>30&&o.soldiers<4000&&p.gold>=200&&p.food>10000&&p.population>=20000){const hundreds=Math.min(10,Math.floor((10000-o.soldiers)/100),hireCapacity(this,p));if(hundreds>=1){const allocations=Object.fromEntries(p.officers.map(id=>[id,this.officer(id).soldiers]));allocations[o.id]+=hundreds*100;this.execute('hireArmy',{province:p.id,officer:o.id,hundreds,allocations});return true;}}
 if(ai.aggression>50&&o.soldiers>0&&o.training<70){this.execute('trainArmy',{province:p.id,officer:o.id});return true;}
 if(p.gold>=100&&(p.land<100||p.flood<100)){this.execute(smart?(p.land<p.flood?'develop':'flood'):(this.random()<.5&&p.land<100?'develop':p.flood<100?'flood':'develop'),{province:p.id,officer:o.id,amount:100});return true;}
 if(p.hidden.length){this.execute('search',{province:p.id,officer:o.id});return true;}
 }catch{}o.acted=true;return true;}
 this.finishFactionTurn();return true;}
 cheat(kind,id,values){const before=clone(this.s);try{const integer=(key,value,max,min=0)=>{if(!Number.isInteger(Number(value))||Number(value)<min||Number(value)>max)throw Error(`${key} must be ${min}–${max}.`);return Number(value);};
 if(kind==='ai'){const ai=id==='global'?this.s.ai:(this.s.aiRulers[id]??={});for(const [key,v]of Object.entries(values)){if(!['intelligence','aggression'].includes(key))throw Error('Unknown AI attribute.');ai[key]=integer(key,v,100);}}
 else if(kind==='officer'){const o=this.officer(id),bounds={int:100,war:100,charm:100,loyalty:100,training:100,soldiers:10000,weapons:10000,compatibility:255,virtue:100,ambition:100};for(const [key,v]of Object.entries(values)){if(key==='acted')o.acted=!!v;else if(key in bounds)o[key]=integer(key,v,bounds[key]);else throw Error('Unknown officer attribute.');}}
 else if(kind==='province'){const p=this.province(id),bounds={gold:30000,food:3000000,population:3000000,land:100,flood:100,loyalty:100,castle:100,horses:100,ricePrice:120};for(const [key,v]of Object.entries(values)){if(key==='owner'){const owner=Number(v);if(owner!==255&&!this.s.rulers.some(r=>r.id===owner))throw Error('Choose an existing ruler.');if(owner===255){for(const oid of p.officers){this.officer(oid).owner=255;p.unclaimed.push(oid);}p.officers=[];p.governor=null;}else{if(!p.officers.length){const oid=p.unclaimed.shift()??p.hidden.shift();if(oid===undefined)throw Error('Place an officer here before assigning a ruler.');p.officers.push(oid);p.governor=oid;}for(const oid of p.officers)this.officer(oid).owner=owner;}p.owner=owner;
 }else if(key==='merchant')p.merchant=!!v;else if(key==='resetActions'){if(v){for(const oid of p.officers)this.officer(oid).acted=false;p.taxed=false;}}else if(key in bounds)p[key]=integer(key,v,bounds[key],key==='ricePrice'?1:0);else throw Error('Unknown province attribute.');}}
 else if(kind==='battle'){const b=this.s.battle;if(!b)throw Error('No active battle.');for(const [key,v]of Object.entries(values)){if(key==='weather'){if(!Object.hasOwn(WEATHER,v))throw Error('Choose a listed weather condition.');setWeather(b,v);}else if(key==='wind')b.wind=integer(key,v,6);else if(key==='windStrength')b.windStrength=integer(key,v,3);else if(key==='challengeWar')b.challengeWar=integer(key,v,100);else if(key==='day'){b.day=integer(key,v,30,1);b.completedDays=b.day-1;}else if(key==='ordered'){const u=b.units.find(u=>u.id===Number(id));if(!u)throw Error('Choose a battle unit.');u.ordered=!!v;u.orderDay=u.ordered?b.day:0;}else if(key==='attackFood'||key==='defendFood')b.food[key==='attackFood'?'attack':'defend']=integer(key,v,3000000);else{const u=b.units.find(u=>u.id===Number(id));if(!u||!['soldiers','morale','mobility','war','int'].includes(key))throw Error('Choose a battle unit and attribute.');u[key]=integer(key,v,key==='soldiers'?10000:['morale','war','int'].includes(key)?100:1000);u.routed=u.soldiers===0||u.morale<=10;}}if(b.wind===0)b.windStrength=0;validateBattle(b,this.s,this.terrains);outcome(b);if(b.outcome)this.resolveBattle();}
 else throw Error('Unknown cheat panel.');if(this.s.battle&&['province','officer'].includes(kind))throw Error('During battle, edit units and supplies from the Battle tab.');this.normalize();this.record(`Testing HUD updated ${kind} ${id}.`,'cheat');return true;
 }catch(e){this.s=before;throw e;}}
}
export function validateSave(raw,scenarios,terrains=[]){const s=clone(raw),version=s?.version,media={sound:raw?.settings?.sound!==false,music:raw?.settings?.music!==false,battleView:raw?.settings?.battleView==='all'?'all':'personal'};if(![1,2].includes(version))throw Error('This is not a compatible RTK2 save.');s.version=1;baseValidate(s,scenarios);s.version=2;Object.assign(s.settings,media);
 for(let i=0;i<41;i++){const t=scenarios[s.scenarioId].provinces[i];for(const key of ['seat','seatZh','geo'])s.provinces[i][key]=clone(t[key]);}if(version===1){Object.assign(s,{humanRulers:[s.player],completed:[],ai:{...AI_DEFAULTS},aiRulers:{},paused:false,speed:600,battle:null});}
 if(!Array.isArray(s.humanRulers)||s.humanRulers.length>12||new Set(s.humanRulers).size!==s.humanRulers.length||s.humanRulers.some(id=>!s.rulers.some(r=>r.id===id))||!Array.isArray(s.completed)||new Set(s.completed).size!==s.completed.length||s.completed.some(id=>!s.rulers.some(r=>r.id===id)))throw Error('Invalid player configuration.');
 for(const ai of [s.ai,...Object.values(s.aiRulers||{})])for(const key of ['intelligence','aggression'])if(ai[key]!==undefined&&(!Number.isInteger(ai[key])||ai[key]<0||ai[key]>100))throw Error('Invalid AI settings.');if(!s.ai||!Number.isInteger(s.ai.intelligence)||!Number.isInteger(s.ai.aggression)||!s.aiRulers||Object.keys(s.aiRulers).some(id=>!s.rulers.some(r=>String(r.id)===id)))throw Error('Invalid AI configuration.');s.paused=!!s.paused;s.speed=[100,300,600,1200].includes(s.speed)?s.speed:600;validateBattle(s.battle,s,terrains);if(s.lastEvent){if(!['diplomacy','prison','war','council','month','history'].includes(s.lastEvent.kind)||typeof s.lastEvent.title!=='string'||typeof s.lastEvent.text!=='string')throw Error('Invalid event data.');const art=s.lastEvent.art,province=s.lastEvent.province;if(art!==undefined&&!EVENT_TYPES.includes(art))throw Error('Invalid event artwork.');s.lastEvent={art,province:Number.isInteger(province)&&s.provinces[province-1]?province:null,kind:s.lastEvent.kind,title:s.lastEvent.title.slice(0,150),text:s.lastEvent.text.slice(0,3000),officer:Number.isInteger(s.lastEvent.officer)&&s.officers[s.lastEvent.officer]?s.lastEvent.officer:null};}delete s.eventPreview;s.portraitOfficer=Number.isInteger(s.portraitOfficer)&&s.officers[s.portraitOfficer]?s.portraitOfficer:null;validateMonthlyState(s);validateProvinceOrders(s);applyGeography(s);return s;
}
