"""Build js/landmask.js: a 1-degree land/sea bitmask for the dotted world map.

Source: Natural Earth 110m land polygons (public domain).
Usage:  python tools/build_landmask.py [path/to/ne_110m_land.geojson]
"""
import base64
import json
import sys
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "landmask.js"

SOURCES = [
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson",
    "https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json",
]

HI_W, HI_H = 3600, 1800   # 0.1 deg raster
W, H = 360, 180           # 1 deg output
COVERAGE = 0.35           # fraction of a cell that must be land
SOUTH_CUTOFF = -60        # drop Antarctica for a cleaner dotted look


def load_geojson(path_arg):
    if path_arg:
        return json.loads(Path(path_arg).read_text(encoding="utf-8"))
    last = None
    for url in SOURCES:
        try:
            with urllib.request.urlopen(url, timeout=60) as r:
                return json.loads(r.read().decode("utf-8"))
        except Exception as e:  # try next mirror
            last = e
            print(f"download failed: {url}\n  {e}", file=sys.stderr)
    raise SystemExit(f"could not fetch land polygons ({last})")


def to_px(pt):
    lon, lat = pt[0], pt[1]
    return ((lon + 180.0) / 360.0 * HI_W, (90.0 - lat) / 180.0 * HI_H)


def rasterize(geojson):
    from PIL import ImageDraw
    img = Image.new("L", (HI_W, HI_H), 0)
    draw = ImageDraw.Draw(img)
    for feat in geojson["features"]:
        geom = feat["geometry"]
        if geom["type"] == "Polygon":
            polys = [geom["coordinates"]]
        elif geom["type"] == "MultiPolygon":
            polys = geom["coordinates"]
        else:
            continue
        for poly in polys:
            ext = [to_px(p) for p in poly[0]]
            if len(ext) >= 3:
                draw.polygon(ext, fill=255)
            for hole in poly[1:]:
                pts = [to_px(p) for p in hole]
                if len(pts) >= 3:
                    draw.polygon(pts, fill=0)
    return img


def main():
    gj = load_geojson(sys.argv[1] if len(sys.argv) > 1 else None)
    hi = rasterize(gj)
    lo = hi.resize((W, H), Image.BOX)  # average coverage per 1-deg cell
    px = lo.load()
    bits = bytearray((W * H + 7) // 8)
    land = 0
    for i in range(H):
        lat = 90 - (i + 0.5)
        if lat < SOUTH_CUTOFF:
            continue
        for j in range(W):
            if px[j, i] / 255.0 >= COVERAGE:
                k = i * W + j
                bits[k >> 3] |= 1 << (k & 7)
                land += 1
    b64 = base64.b64encode(bytes(bits)).decode("ascii")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by tools/build_landmask.py from Natural Earth 110m land (public domain).\n"
        "// Row-major bitmask, 1 deg cells, row 0 = lat 90..89, col 0 = lon -180..-179.\n"
        f"export const LANDMASK = {{ width: {W}, height: {H}, data: \"{b64}\" }};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({land} land cells, {len(b64)} chars)")


if __name__ == "__main__":
    main()
